// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/activities.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/activities.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const ACTIVITIES: ResourceGroup = {
  id: 'activities',
  label: 'Activities',
  description: 'Log and manage CRM activities (calls, meetings, notes) linked to contacts, deals, and customers.',
  endpoints: [
    {
      method: 'GET',
      path: '/activities',
      toolName: 'list_activities',
      description: 'List CRM activity log entries (free-text notes and one-line records of calls, meetings, sms, emails, tasks) anchored to contacts/companies/opportunities. Use for "recent notes", "what was logged", "activity history on this deal/contact". DO NOT use for phone-specific queries — list_phone_call_logs returns the actual call records with duration, recording, direction. DO NOT use for inbox queries — list_email_threads / list_sms_conversations / list_bookings / list_transcripts have richer per-channel data.',
      scopes: ['activities:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: 'Max activities (1-100, default 25)', in: 'query' },
        { name: 'after', type: 'string', required: false, description: 'Pagination cursor', in: 'query' },
        { name: 'contact_id', type: 'string', required: false, description: 'Filter to activities on a specific contact', in: 'query' },
        { name: 'customer_id', type: 'string', required: false, description: 'Filter to activities on a specific company', in: 'query' },
        { name: 'deal_id', type: 'string', required: false, description: 'Filter to activities on a specific opportunity', in: 'query' },
        { name: 'task_id', type: 'string', required: false, description: 'Filter to activities logged from a specific task', in: 'query' },
        { name: 'activity_type', type: 'string', required: false, description: 'Filter by type (call, meeting, note, email)', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/activities" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/activities',
      toolName: 'log_activity',
      description: 'Log an activity (call, meeting, note, email) against a contact, company, opportunity, or task. Use after a phone call, meeting, or to add a note. When task_id is set, the activity appears on the task detail page AND on the linked opportunity timeline.',
      scopes: ['activities:write'],
      isWrite: true,
      params: [
        { name: 'activity_type', type: 'string', required: true, description: 'Type: call, meeting, note, email, sms, task', in: 'body' },
        { name: 'subject', type: 'string', required: false, description: 'Short title / summary', in: 'body' },
        { name: 'description', type: 'string', required: false, description: 'Detail / notes content', in: 'body' },
        { name: 'contact_id', type: 'string', required: false, description: 'UUID of the contact this is about', in: 'body' },
        { name: 'customer_id', type: 'string', required: false, description: 'UUID of the company this is about', in: 'body' },
        { name: 'deal_id', type: 'string', required: false, description: 'UUID of the opportunity this is about', in: 'body' },
        { name: 'deal_ids', type: 'array', required: false, description: 'Multiple opportunity UUIDs to fan out', in: 'body' },
        { name: 'task_id', type: 'string', required: false, description: 'UUID of the task this activity came from. Shows on the task detail page; pair with deal_id to also surface on the opportunity timeline.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/activities" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"activity_type":"...","subject":"...","description":"..."}'`,
    },
    {
      method: 'GET',
      path: '/activities/:activity_id',
      toolName: 'get_activity',
      description: 'Fetch a single activity by UUID — the full record including description, occurred_at, and linked entities.',
      scopes: ['activities:read'],
      isWrite: false,
      params: [
        { name: 'activity_id', type: 'string', required: true, description: 'UUID of the activity', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/activities/:activity_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/activities/:activity_id',
      toolName: 'update_activity',
      description: 'Update an activity. Pass only the fields you want to change. Pass deal_ids array to replace linked opportunities atomically.',
      scopes: ['activities:write'],
      isWrite: true,
      params: [
        { name: 'activity_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'activity_type', type: 'string', required: false, description: '', in: 'body' },
        { name: 'subject', type: 'string', required: false, description: '', in: 'body' },
        { name: 'description', type: 'string', required: false, description: '', in: 'body' },
        { name: 'contact_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'customer_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'task_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'deal_ids', type: 'array', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/activities/:activity_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"activity_type":"...","subject":"...","description":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/activities/:activity_id',
      toolName: 'delete_activity',
      description: 'Delete an activity by UUID. Destructive.',
      scopes: ['activities:delete'],
      isWrite: true,
      params: [
        { name: 'activity_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/activities/:activity_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
