// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/agent-proposals.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/agent-proposals.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const AGENT_PROPOSALS: ResourceGroup = {
  id: 'agent-proposals',
  label: 'Agent Proposals',
  description: 'Agent action proposals submitted by AI agents for human review and approval. Agents submit proposals when they identify an action that should be taken but requires a human decision. Proposals surface in the Agent Hub at /auto/agent-hub?tab=proposals.',
  endpoints: [
    {
      method: 'GET',
      path: '/agent-proposals',
      toolName: 'list_agent_proposals',
      description: 'List agent action proposals. Filter by status (pending, approved, rejected) and agent_name.',
      scopes: ['agent-ops:read'],
      isWrite: false,
      params: [
        { name: 'status', type: 'string', required: false, description: '', in: 'query' },
        { name: 'agent_name', type: 'string', required: false, description: '', in: 'query' },
        { name: 'category', type: 'string', required: false, description: '', in: 'query' },
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/agent-proposals" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{
  "data": [
    {
      "id": "f1a2b3c4-...",
      "company_id": "ebeff86e-...",
      "agent_name": "project-manager",
      "category": "enable",
      "priority": "high",
      "title": "Enable welcome automation",
      "description": "The welcome sequence is disabled. 3 clients received no onboarding email.",
      "context": { "affected_deals": 3, "pipeline": "Fulfillment Kickoff" },
      "proposed_action": { "tool": "enable_automation", "params": { "id": "auto-uuid" } },
      "options": null,
      "status": "pending",
      "answer": null,
      "answered_by": null,
      "answered_at": null,
      "execution_result": null,
      "executed_at": null,
      "expires_at": "2026-04-20T00:00:00Z",
      "created_at": "2026-04-13T23:00:00Z",
      "updated_at": "2026-04-13T23:00:00Z"
    }
  ],
  "meta": { "url": "https://app.trustpager.com/auto/agent-hub?tab=proposals" }
}`,
    },
    {
      method: 'POST',
      path: '/agent-proposals',
      toolName: 'create_agent_proposal',
      description: 'Create a new agent action proposal for human review.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'agent_name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'category', type: 'string', required: true, description: '', in: 'body' },
        { name: 'title', type: 'string', required: true, description: '', in: 'body' },
        { name: 'proposed_action', type: 'object', required: true, description: '', in: 'body' },
        { name: 'rationale', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `{
  "agent_name": "project-manager",
  "category": "enable",
  "priority": "high",
  "title": "Enable welcome automation",
  "description": "The welcome sequence automation has been disabled for 5 days. 3 new clients received no onboarding email.",
  "context": { "affected_deals": 3, "pipeline": "Fulfillment Kickoff", "days_disabled": 5 },
  "proposed_action": { "tool": "enable_automation", "params": { "id": "auto-uuid" } }
}`,
      responseExample: `{
  "data": {
    "id": "f1a2b3c4-...",
    "status": "pending",
    "expires_at": "2026-04-20T00:00:00Z"
  },
  "meta": { "url": "https://app.trustpager.com/auto/agent-hub?tab=proposals" }
}`,
    },
    {
      method: 'GET',
      path: '/agent-proposals/:proposal_id',
      toolName: 'get_agent_proposal',
      description: 'Fetch a single agent proposal by UUID.',
      scopes: ['agent-ops:read'],
      isWrite: false,
      params: [
        { name: 'proposal_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/agent-proposals/:proposal_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/agent-proposals/:proposal_id/approve',
      toolName: 'approve_agent_proposal',
      description: 'Approve an agent proposal — EVE handler executes it.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'proposal_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/agent-proposals/:proposal_id/approve" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/agent-proposals/:proposal_id/reject',
      toolName: 'reject_agent_proposal',
      description: 'Reject an agent proposal with optional reason.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'proposal_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'reason', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/agent-proposals/:proposal_id/reject" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"reason":"..."}'`,
    },
    {
      method: 'POST',
      path: '/agent-proposals/:proposal_id/execute-result',
      toolName: 'report_agent_proposal_execution',
      description: 'EVE handler reports the result of executing an approved proposal.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'proposal_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'status', type: 'string', required: true, description: '', in: 'body' },
        { name: 'result', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/agent-proposals/:proposal_id/execute-result" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"status":"...","result":"..."}'`,
    },
  ],
};
