// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/agent-ops.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/agent-ops.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const AGENT_OPS: ResourceGroup = {
  id: 'agent-ops',
  label: 'Agent Ops',
  description: 'Observability and management for AI agent infrastructure. Covers: registry, run log, signals, metrics, tool log, report runs, alert rules, fired alerts, and the aggregated dashboard. All routes require agent-ops:read (reads) or agent-ops:write (writes/actions).',
  endpoints: [
    {
      method: 'GET',
      path: '/agent-ops/registry',
      toolName: 'list_agent_registry',
      description: 'List the agent registry — every agent identity that can act on the workspace.',
      scopes: ['agent-ops:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/agent-ops/registry" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{
  "data": [
    {
      "id": "880b909e-aa2f-4d8c-8372-073921a9d947",
      "company_id": "ebeff86e-...",
      "name": "nurture-agent",
      "display_name": "Nurture Agent",
      "agent_type": "scheduled_task",
      "status": "active",
      "schedule": "0 6 * * *",
      "timezone": "Australia/Sydney",
      "capabilities": ["email", "sms"],
      "created_at": "2026-05-01T00:00:00Z",
      "updated_at": "2026-05-19T06:20:00Z"
    }
  ],
  "pagination": { "has_more": false }
}`,
    },
    {
      method: 'POST',
      path: '/agent-ops/registry',
      toolName: 'create_agent_registry',
      description: 'Register a new agent.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'display_name', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `{
  "name": "weekly-report",
  "display_name": "Weekly Report Agent",
  "agent_type": "cron_report",
  "schedule": "0 9 * * 1",
  "timezone": "Australia/Sydney",
  "capabilities": ["email", "notepad"]
}`,
      responseExample: `{
  "data": {
    "id": "a1b2c3d4-...",
    "company_id": "ebeff86e-...",
    "name": "weekly-report",
    "display_name": "Weekly Report Agent",
    "status": "active",
    "created_at": "2026-05-19T07:00:00Z"
  }
}`,
    },
    {
      method: 'GET',
      path: '/agent-ops/registry/:registry_id',
      toolName: 'get_agent_registry',
      description: 'Fetch an agent registry entry.',
      scopes: ['agent-ops:read'],
      isWrite: false,
      params: [
        { name: 'registry_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/agent-ops/registry/:registry_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/agent-ops/registry/:registry_id',
      toolName: 'update_agent_registry',
      description: 'Update an agent registry entry.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'registry_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/agent-ops/registry/:registry_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/agent-ops/registry/:registry_id',
      toolName: 'delete_agent_registry',
      description: 'Delete an agent registry entry.',
      scopes: ['agent-ops:delete'],
      isWrite: true,
      params: [
        { name: 'registry_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/agent-ops/registry/:registry_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/agent-ops/runs',
      toolName: 'list_agent_runs',
      description: 'List agent execution runs.',
      scopes: ['agent-ops:read'],
      isWrite: false,
      params: [
        { name: 'agent_name', type: 'string', required: false, description: '', in: 'query' },
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/agent-ops/runs" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{
  "data": [
    {
      "id": "run-uuid",
      "agent_name": "nurture-agent",
      "task_type": "manual",
      "status": "completed",
      "duration_ms": 12400,
      "started_at": "2026-05-19T06:00:00Z",
      "completed_at": "2026-05-19T06:00:12Z",
      "output_summary": "Sent 3 follow-up emails"
    }
  ]
}`,
    },
    {
      method: 'POST',
      path: '/agent-ops/runs',
      toolName: 'create_agent_run',
      description: 'Log a new agent run.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'agent_name', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/agent-ops/runs" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"agent_name":"..."}'`,
      responseExample: `{ "data": { "id": "run-uuid", "agent_name": "nurture-agent", "status": "started" } }`,
    },
    {
      method: 'PATCH',
      path: '/agent-ops/runs/:run_id|str',
      toolName: 'update_agent_run',
      description: 'Update an agent run.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'run_id', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/agent-ops/runs/:run_id|str" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"run_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/agent-ops/signals',
      toolName: 'list_agent_signals',
      description: 'List inter-agent signals.',
      scopes: ['agent-ops:read'],
      isWrite: false,
      params: [
        { name: 'for_agent', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/agent-ops/signals" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{ "data": [] }`,
    },
    {
      method: 'POST',
      path: '/agent-ops/signals',
      toolName: 'create_agent_signal',
      description: 'Send an inter-agent signal.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'for_agent', type: 'string', required: true, description: '', in: 'body' },
        { name: 'created_by', type: 'string', required: true, description: '', in: 'body' },
        { name: 'signal', type: 'object', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/agent-ops/signals" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"for_agent":"...","created_by":"...","signal":"..."}'`,
      responseExample: `{ "data": { "id": "signal-uuid", "for_agent": "ops-report", "signal": "screenshot_request" } }`,
    },
    {
      method: 'PATCH',
      path: '/agent-ops/signals/:signal_id',
      toolName: 'update_agent_signal',
      description: 'Update a signal (e.g. mark as consumed).',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'signal_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/agent-ops/signals/:signal_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/agent-ops/metrics',
      toolName: 'list_agent_metrics',
      description: 'List daily agent metrics.',
      scopes: ['agent-ops:read'],
      isWrite: false,
      params: [
        { name: 'agent_name', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/agent-ops/metrics" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/agent-ops/metrics',
      toolName: 'upsert_agent_metrics',
      description: 'Upsert a metric row.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'agent_name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'run_date', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/agent-ops/metrics" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"agent_name":"...","run_date":"..."}'`,
    },
    {
      method: 'GET',
      path: '/agent-ops/tool-log',
      toolName: 'list_agent_tool_log',
      description: 'List agent tool-call log entries.',
      scopes: ['agent-ops:read'],
      isWrite: false,
      params: [
        { name: 'agent_name', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/agent-ops/tool-log" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/agent-ops/tool-log',
      toolName: 'create_agent_tool_log',
      description: 'Log an agent tool call.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'tool_name', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/agent-ops/tool-log" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"tool_name":"..."}'`,
    },
    {
      method: 'GET',
      path: '/agent-ops/reports',
      toolName: 'list_agent_report_runs',
      description: 'List agent report-run history.',
      scopes: ['agent-ops:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/agent-ops/reports" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/agent-ops/reports',
      toolName: 'create_agent_report_run',
      description: 'Create an agent report-run entry.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'report_name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'run_date', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/agent-ops/reports" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"report_name":"...","run_date":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/agent-ops/reports/:report_id',
      toolName: 'update_agent_report_run',
      description: 'Update an agent report-run.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'report_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/agent-ops/reports/:report_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/agent-ops/alert-rules',
      toolName: 'list_agent_alert_rules',
      description: 'List agent alert rules.',
      scopes: ['agent-ops:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/agent-ops/alert-rules" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{ "data": [] }`,
    },
    {
      method: 'POST',
      path: '/agent-ops/alert-rules',
      toolName: 'create_agent_alert_rule',
      description: 'Create an agent alert rule.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'rule_type', type: 'string', required: true, description: '', in: 'body' },
        { name: 'threshold', type: 'number', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/agent-ops/alert-rules" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"rule_type":"...","threshold":"..."}'`,
      responseExample: `{ "data": { "id": "rule-uuid", "rule_type": "consecutive_failures", "threshold": {"max_failures": 2}, "enabled": true } }`,
    },
    {
      method: 'PATCH',
      path: '/agent-ops/alert-rules/:rule_id',
      toolName: 'update_agent_alert_rule',
      description: 'Update an agent alert rule.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'rule_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/agent-ops/alert-rules/:rule_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/agent-ops/alert-rules/:rule_id',
      toolName: 'delete_agent_alert_rule',
      description: 'Delete an agent alert rule.',
      scopes: ['agent-ops:delete'],
      isWrite: true,
      params: [
        { name: 'rule_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/agent-ops/alert-rules/:rule_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/agent-ops/alerts',
      toolName: 'list_agent_alerts',
      description: 'List fired agent alerts.',
      scopes: ['agent-ops:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/agent-ops/alerts" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{ "data": [] }`,
    },
    {
      method: 'POST',
      path: '/agent-ops/alerts',
      toolName: 'create_agent_alert',
      description: 'Record a fired agent alert.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'agent_name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'alert_type', type: 'string', required: true, description: '', in: 'body' },
        { name: 'message', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/agent-ops/alerts" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"agent_name":"...","alert_type":"...","message":"..."}'`,
    },
    {
      method: 'POST',
      path: '/agent-ops/alerts/:alert_id/acknowledge',
      toolName: 'acknowledge_agent_alert',
      description: 'Acknowledge a fired agent alert.',
      scopes: ['agent-ops:write'],
      isWrite: true,
      params: [
        { name: 'alert_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/agent-ops/alerts/:alert_id/acknowledge" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/agent-ops/dashboard',
      toolName: 'get_agent_dashboard',
      description: 'Get the aggregated agent operations dashboard.',
      scopes: ['agent-ops:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/agent-ops/dashboard" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{
  "data": {
    "agents": [
      {
        "id": "880b909e-...",
        "name": "nurture-agent",
        "display_name": "Nurture Agent",
        "agent_type": "scheduled_task",
        "status": "active",
        "last_run_at": "2026-05-19T06:00:00Z",
        "last_success_at": "2026-05-19T06:00:00Z",
        "last_failure_at": null,
        "consecutive_failures": 0,
        "schedule": "0 6 * * *"
      }
    ],
    "today_runs": [],
    "pending_signals": [],
    "report_runs": [],
    "summary": {
      "agents_active": 2,
      "agents_total": 2,
      "runs_today": 0,
      "runs_completed": 0,
      "runs_failed": 0,
      "pending_signals": 0,
      "avg_duration_ms": 0
    }
  }
}`,
    },
  ],
};
