// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/ai-instructions.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/ai-instructions.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const AI_INSTRUCTIONS: ResourceGroup = {
  id: 'ai-instructions',
  label: 'AI Instructions',
  description: 'Structured behavioral instructions for AI agents. Call once per session, cache the result. Free (0 credits).',
  endpoints: [
    {
      method: 'GET',
      path: '/ai-instructions',
      toolName: 'get_ai_instructions',
      description: 'Get structured behavioural instructions for AI agents using this workspace API. Free read — cache once per session.',
      scopes: [],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/ai-instructions" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
