// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/ai.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/ai.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const AI: ResourceGroup = {
  id: 'ai',
  label: 'AI',
  description: 'AI-powered features including text editing, call coaching, needs analysis, form filling, pipeline generation, image generation, reference-guided image editing, text-to-speech generation, and AI tool generators (form, document, whiteboard, website page) that create fully-structured workspace assets from a plain-language prompt.',
  endpoints: [
    {
      method: 'POST',
      path: '/ai/edit-text',
      toolName: 'ai_edit_text',
      description: 'Rewrite, refine, or transform a block of text. Use for "make this more formal", "shorten this", "fix grammar". Costs credits.',
      scopes: ['ai:use'],
      isWrite: true,
      params: [
        { name: 'text', type: 'string', required: true, description: '', in: 'body' },
        { name: 'instruction', type: 'string', required: true, description: '', in: 'body' },
        { name: 'tone', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/edit-text" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"text":"...","instruction":"...","tone":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/call-coaching',
      toolName: 'ai_call_coaching',
      description: 'Analyze a phone call transcript for coaching feedback. Costs credits.',
      scopes: ['ai:use'],
      isWrite: true,
      params: [
        { name: 'transcript_id', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/call-coaching" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"transcript_id":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/transcript-summary',
      toolName: 'ai_transcript_summary',
      description: 'Summarise a call or meeting transcript — key topics, decisions, action items. Costs credits.',
      scopes: ['ai:use'],
      isWrite: true,
      params: [
        { name: 'transcript_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'focus', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/transcript-summary" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"transcript_id":"...","focus":"..."}'`,
      responseExample: `{
  "data": {
    "transcript_id": "uuid",
    "title": "Demo Call - Acme Corp",
    "occurred_at": "2026-04-17T09:00:00Z",
    "duration_minutes": 42,
    "participant_count": 3,
    "type": "zoom_call",
    "source": "Zoom",
    "sentiment": "positive",
    "summary": "Strong interest in workflow automation. Client asked about Xero integration and API access. Decision expected by end of April.",
    "key_topics": ["automation", "Xero integration", "pricing", "timeline"],
    "key_quotes": [
      { "quote": "This would save us 3 hours a day", "context": "After seeing the automation demo", "use": "testimonial" }
    ],
    "feature_gaps": ["Bulk SMS to a segment"],
    "competitor_mentions": [{ "name": "HubSpot", "context": "Currently using, wants to switch" }],
    "impressive_features": ["Pipeline automation", "Document signing"],
    "bugs_reported": [],
    "pricing_feedback": "Pricing is reasonable but wants annual discount",
    "integration_requests": ["Xero", "Zapier"],
    "action_items": ["Send API docs", "Schedule follow-up for April 25"],
    "input_tokens": 4820,
    "output_tokens": 312
  },
  "meta": { "credits_remaining": 9489 }
}`,
    },
    {
      method: 'POST',
      path: '/ai/needs-analysis',
      toolName: 'ai_needs_analysis',
      description: 'Analyse an opportunity — activities, transcripts, notes — to surface needs, objections, next steps. Costs credits.',
      scopes: ['ai:use'],
      isWrite: true,
      params: [
        { name: 'opportunity_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'focus', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/needs-analysis" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"opportunity_id":"...","focus":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/fill-form',
      toolName: 'ai_fill_form',
      description: 'Auto-fill a form from natural-language inputs.',
      scopes: ['ai:use'],
      isWrite: true,
      params: [
        { name: 'form_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'inputs', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/fill-form" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"form_id":"...","inputs":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/generate-pipeline',
      toolName: 'ai_generate_pipeline',
      description: 'Generate a new pipeline (with stages) from a natural-language description.',
      scopes: ['ai:use', 'pipelines:write'],
      isWrite: true,
      params: [
        { name: 'prompt', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/generate-pipeline" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"prompt":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/generate-form',
      toolName: 'ai_generate_form',
      description: 'Generate a form template from a natural-language prompt.',
      scopes: ['ai:use', 'forms:write'],
      isWrite: true,
      params: [
        { name: 'prompt', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/generate-form" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"prompt":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/generate-document',
      toolName: 'ai_generate_document',
      description: 'Generate a new document from a prompt — proposals, scopes, summaries. Returns a document UUID. Costs credits.',
      scopes: ['ai:use', 'documents:write'],
      isWrite: true,
      params: [
        { name: 'prompt', type: 'string', required: true, description: '', in: 'body' },
        { name: 'opportunity_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'contact_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'title', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/generate-document" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"prompt":"...","opportunity_id":"...","contact_id":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/generate-whiteboard',
      toolName: 'ai_generate_whiteboard',
      description: 'Generate a whiteboard layout from a prompt.',
      scopes: ['ai:use'],
      isWrite: true,
      params: [
        { name: 'prompt', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/generate-whiteboard" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"prompt":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/generate-website-page',
      toolName: 'ai_generate_website_page',
      description: 'Generate a website page from a prompt.',
      scopes: ['ai:use', 'websites:write'],
      isWrite: true,
      params: [
        { name: 'prompt', type: 'string', required: true, description: '', in: 'body' },
        { name: 'website_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/generate-website-page" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"prompt":"...","website_id":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/generate-image',
      toolName: 'ai_generate_image',
      description: 'Generate an image from a prompt. Costs credits.',
      scopes: ['ai:use'],
      isWrite: true,
      params: [
        { name: 'prompt', type: 'string', required: true, description: '', in: 'body' },
        { name: 'aspect_ratio', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/generate-image" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"prompt":"...","aspect_ratio":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/edit-image',
      toolName: 'ai_edit_image',
      description: 'Edit an image based on a prompt. Costs credits.',
      scopes: ['ai:use'],
      isWrite: true,
      params: [
        { name: 'image_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'prompt', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/edit-image" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"image_id":"...","prompt":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/upscale-image',
      toolName: 'ai_upscale_image',
      description: 'Upscale an image to higher resolution. Costs credits.',
      scopes: ['ai:use'],
      isWrite: true,
      params: [
        { name: 'image_id', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/upscale-image" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"image_id":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/generate-speech',
      toolName: 'ai_generate_speech',
      description: 'Generate speech audio from text. Costs credits.',
      scopes: ['ai:use'],
      isWrite: true,
      params: [
        { name: 'text', type: 'string', required: true, description: '', in: 'body' },
        { name: 'voice_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/generate-speech" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"text":"...","voice_id":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/generate-music',
      toolName: 'ai_generate_music',
      description: 'Generate music audio from a prompt. Costs credits.',
      scopes: ['ai:use'],
      isWrite: true,
      params: [
        { name: 'prompt', type: 'string', required: true, description: '', in: 'body' },
        { name: 'duration_seconds', type: 'number', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/generate-music" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"prompt":"...","duration_seconds":"..."}'`,
    },
    {
      method: 'POST',
      path: '/ai/generate-embedding',
      toolName: 'ai_generate_embedding',
      description: 'Generate a vector embedding for a text string. Free.',
      scopes: ['ai:use'],
      isWrite: false,
      params: [
        { name: 'text', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/ai/generate-embedding" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"text":"..."}'`,
    },
  ],
};
