// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/approvals.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/approvals.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const APPROVALS: ResourceGroup = {
  id: 'approvals',
  label: 'Approvals',
  description: 'Manage API actions queued for human approval. When an API key has a "with Approval" permission level, write operations are held here until a team member reviews them.',
  endpoints: [
    {
      method: 'GET',
      path: '/approvals',
      toolName: 'list_approvals',
      description: 'List pending approvals — actions queued for human review. Use after a 202 to check what is waiting.',
      scopes: ['approvals:read'],
      isWrite: false,
      params: [
        { name: 'status', type: 'string', required: false, description: 'pending (default), approved, rejected, expired, executed, failed', in: 'query' },
        { name: 'resource', type: 'string', required: false, description: '', in: 'query' },
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/approvals" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{
  "data": [
    {
      "id": "f1a2b3c4-...",
      "company_id": "ebeff86e-...",
      "api_key_id": "key-uuid",
      "resource": "contacts",
      "action": "write",
      "method": "POST",
      "path": "/contacts",
      "status": "pending",
      "request_body": { "first_name": "Jane", "email": "jane@example.com" },
      "target_id": null,
      "created_at": "2026-03-29T04:00:00Z",
      "expires_at": null,
      "resolved_at": null,
      "resolved_by": null
    }
  ],
  "meta": { "limit": 25, "has_more": false, "next_cursor": null, "prev_cursor": null }
}`,
    },
    {
      method: 'GET',
      path: '/approvals/:approval_id',
      toolName: 'get_approval',
      description: 'Fetch a single approval by UUID — full action details, request body, status, reviewer assignment.',
      scopes: ['approvals:read'],
      isWrite: false,
      params: [
        { name: 'approval_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/approvals/:approval_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/approvals/:approval_id/approve',
      toolName: 'approve_action',
      description: 'Approve a pending action and execute it. Destructive — runs the underlying queued operation.',
      scopes: ['approvals:write'],
      isWrite: true,
      params: [
        { name: 'approval_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/approvals/:approval_id/approve" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/approvals/:approval_id/reject',
      toolName: 'reject_action',
      description: 'Reject a pending action. Cancels the queued operation.',
      scopes: ['approvals:write'],
      isWrite: true,
      params: [
        { name: 'approval_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'reason', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/approvals/:approval_id/reject" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"reason":"..."}'`,
    },
    {
      method: 'POST',
      path: '/approvals/:approval_id/assign',
      toolName: 'assign_approval',
      description: 'Reassign a pending approval to a different reviewer. Does not approve or reject.',
      scopes: ['approvals:reassign'],
      isWrite: true,
      params: [
        { name: 'approval_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'primary_assignee_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'secondary_assignee_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/approvals/:approval_id/assign" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"primary_assignee_id":"...","secondary_assignee_id":"..."}'`,
    },
    {
      method: 'POST',
      path: '/approvals/:approval_id/edit',
      toolName: 'update_approval',
      description: 'Rewrite the request_body of a pending approval. Lets agents iterate on AI-drafted content (e.g. fix an email body) without approving.',
      scopes: ['approvals:edit'],
      isWrite: true,
      params: [
        { name: 'approval_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'request_body', type: 'object', required: true, description: 'New request body to replace the queued one', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/approvals/:approval_id/edit" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"request_body":"..."}'`,
    },
  ],
};
