// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/automations.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/automations.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const AUTOMATIONS: ResourceGroup = {
  id: 'automations',
  label: 'Automations',
  description: 'Create and manage workflow automations. Includes sub-resources for triggers, actions, and execution runs. Supports enable/disable and manual triggering.',
  endpoints: [
    {
      method: 'GET',
      path: '/automations',
      toolName: 'list_automations',
      description: 'List automations in the workspace.',
      scopes: ['automations:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl -X GET \\
  "${API_BASE_URL}/automations?limit=10" \\
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{
  "data": [
    {
      "id": "auto-uuid-...",
      "name": "New Lead Welcome Email",
      "trigger_type": "pipeline",
      "enabled": true,
      "priority": 0,
      "created_at": "2026-02-15T12:00:00Z"
    }
  ],
  "pagination": { "limit": 10, "has_more": false, "next_cursor": null, "prev_cursor": null }
}`,
    },
    {
      method: 'POST',
      path: '/automations',
      toolName: 'create_automation',
      description: 'Create a new automation.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'trigger_type', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \\
  "${API_BASE_URL}/automations" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "name": "VIP Lead Welcome",
    "trigger_type": "stage_changed",
    "stage_id": "stage-uuid",
    "conditions": {
      "tags": { "contains": "VIP" },
      "deal.value": { "gte": 5000 },
      "lead_source": { "in": ["Referral", "Website"] }
    },
    "description": "Send welcome email to VIP leads only"
  }'`,
      responseExample: `{
  "data": {
    "id": "auto-uuid-...",
    "name": "VIP Lead Welcome",
    "trigger_type": "stage_changed",
    "stage_id": "stage-uuid",
    "conditions": {
      "tags": { "contains": "VIP" },
      "deal.value": { "gte": 5000 },
      "lead_source": { "in": ["Referral", "Website"] }
    },
    "enabled": false,
    "created_at": "2026-04-18T00:00:00Z"
  }
}`,
    },
    {
      method: 'GET',
      path: '/automations/runs/:run_id',
      toolName: 'get_automation_run',
      description: 'Fetch a single automation run by UUID.',
      scopes: ['automations:read'],
      isWrite: false,
      params: [
        { name: 'run_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/automations/runs/:run_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/automations/action-types',
      toolName: 'list_action_types',
      description: 'Browse every automation action_type with a one-line description. Free read. Use describe_action_type for the full config schema of a specific action.',
      scopes: [],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/automations/action-types" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/automations/action-types/:action_type|str',
      toolName: 'describe_action_type',
      description: 'Return the full config schema, example, warnings, and related actions for one automation action_type. Call this RIGHT BEFORE writing that action via add_automation_action — do not memorise multiple types upfront. Free read.',
      scopes: [],
      isWrite: false,
      params: [
        { name: 'action_type', type: 'string', required: true, description: 'Canonical action_type key, e.g. "add_tasks", "send_custom_email", "move_deal". Aliases (e.g. "set_crm_field" → "set_custom_field") are accepted.', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/automations/action-types/:action_type|str" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/automations/:automation_id',
      toolName: 'get_automation',
      description: 'Fetch an automation by UUID.',
      scopes: ['automations:read'],
      isWrite: false,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/automations/:automation_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/automations/:automation_id',
      toolName: 'update_automation',
      description: 'Update an automation.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/automations/:automation_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/automations/:automation_id',
      toolName: 'delete_automation',
      description: 'Delete an automation.',
      scopes: ['automations:delete'],
      isWrite: true,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/automations/:automation_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/automations/:automation_id/enable',
      toolName: 'enable_automation',
      description: 'Enable an automation.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/automations/:automation_id/enable" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/automations/:automation_id/disable',
      toolName: 'disable_automation',
      description: 'Disable an automation.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/automations/:automation_id/disable" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/automations/:automation_id/trigger',
      toolName: 'trigger_automation',
      description: 'Manually trigger an automation.',
      scopes: ['automations-trigger:trigger'],
      isWrite: true,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'payload', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/automations/:automation_id/trigger" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"payload":"..."}'`,
    },
    {
      method: 'GET',
      path: '/automations/:automation_id/runs',
      toolName: 'list_automation_runs',
      description: 'List historical runs of an automation.',
      scopes: ['automations:read'],
      isWrite: false,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/automations/:automation_id/runs" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/automations/:automation_id/triggers',
      toolName: 'list_automation_triggers',
      description: 'List triggers configured on an automation.',
      scopes: ['automations:read'],
      isWrite: false,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/automations/:automation_id/triggers" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/automations/:automation_id/triggers',
      toolName: 'add_automation_trigger',
      description: 'Add a trigger to an automation.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'trigger_type', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/automations/:automation_id/triggers" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"trigger_type":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/automations/:automation_id/triggers/:trigger_id',
      toolName: 'update_automation_trigger',
      description: 'Update a trigger.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'trigger_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/automations/:automation_id/triggers/:trigger_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/automations/:automation_id/triggers/:trigger_id',
      toolName: 'delete_automation_trigger',
      description: 'Delete a trigger.',
      scopes: ['automations:delete'],
      isWrite: true,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'trigger_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/automations/:automation_id/triggers/:trigger_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/automations/:automation_id/actions',
      toolName: 'list_automation_actions',
      description: 'List actions on an automation.',
      scopes: ['automations:read'],
      isWrite: false,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/automations/:automation_id/actions" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/automations/:automation_id/actions',
      toolName: 'add_automation_action',
      description: 'Add an action to an automation.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'action_type', type: 'string', required: true, description: '', in: 'body' },
        { name: 'sequence', type: 'number', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/automations/:automation_id/actions" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"action_type":"...","sequence":"..."}'`,
    },
    {
      method: 'POST',
      path: '/automations/:automation_id/actions/reorder',
      toolName: 'reorder_automation_actions',
      description: 'Reorder automation actions.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'action_ids', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/automations/:automation_id/actions/reorder" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"action_ids":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/automations/:automation_id/actions/:action_id',
      toolName: 'update_automation_action',
      description: 'Update an automation action.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'action_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/automations/:automation_id/actions/:action_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/automations/:automation_id/actions/:action_id',
      toolName: 'delete_automation_action',
      description: 'Delete an automation action.',
      scopes: ['automations:delete'],
      isWrite: true,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'action_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/automations/:automation_id/actions/:action_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/automations/:automation_id/actions/:action_id/execute',
      toolName: 'execute_automation_action',
      description: 'Execute a single automation action (testing).',
      scopes: ['automations-trigger:trigger'],
      isWrite: true,
      params: [
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'action_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'payload', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/automations/:automation_id/actions/:action_id/execute" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"payload":"..."}'`,
    },
  ],
};
