// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/auto-queues.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/auto-queues.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const AUTO_QUEUES: ResourceGroup = {
  id: 'auto-queues',
  label: 'Auto Queues',
  description: 'Manage Auto Queues for sequenced multi-step workflows (drip campaigns, follow-up sequences). Legacy path /event-queues is also accepted.',
  endpoints: [
    {
      method: 'GET',
      path: '/event-queues',
      toolName: 'list_auto_queues',
      description: 'List automation event queues (drip sequences).',
      scopes: ['automations:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/event-queues" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/event-queues',
      toolName: 'create_auto_queue',
      description: 'Create an automation event queue.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'description', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/event-queues" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","description":"..."}'`,
    },
    {
      method: 'GET',
      path: '/event-queues/:queue_id',
      toolName: 'get_auto_queue',
      description: 'Fetch a queue by UUID with its steps.',
      scopes: ['automations:read'],
      isWrite: false,
      params: [
        { name: 'queue_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/event-queues/:queue_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/event-queues/:queue_id',
      toolName: 'update_auto_queue',
      description: 'Update an event queue.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'queue_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'description', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/event-queues/:queue_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","description":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/event-queues/:queue_id',
      toolName: 'delete_auto_queue',
      description: 'Delete an event queue.',
      scopes: ['automations:delete'],
      isWrite: true,
      params: [
        { name: 'queue_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/event-queues/:queue_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/event-queues/:queue_id/enrollments',
      toolName: 'list_auto_queue_enrollments',
      description: 'List enrollments in an event queue.',
      scopes: ['automations:read'],
      isWrite: false,
      params: [
        { name: 'queue_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/event-queues/:queue_id/enrollments" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/event-queues/:queue_id/board',
      toolName: 'get_auto_queue_board',
      description: 'Read-only kanban-shaped state for an Auto Queue. Returns active enrolments bucketed into columns by the step they last completed (column 0 = "Awaiting Step 1"; column N = after step N), plus terminal counts (completed / cancelled). Use this to answer "where is contact X in queue Y" or "how many contacts are at each step" without grouping per-task rows from list_auto_queue_enrollments client-side. Each column returns up to 50 cards — for terminal-state drill-in, call list_auto_queue_enrollments with status=completed or status=cancelled.',
      scopes: ['automations:read'],
      isWrite: false,
      params: [
        { name: 'queue_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/event-queues/:queue_id/board" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/event-queues/:queue_id/bulk-enroll',
      toolName: 'bulk_enrol_in_auto_queue',
      description: 'Bulk-enrol contacts or deals in an event queue.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'queue_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'entity_type', type: 'string', required: true, description: '', in: 'body' },
        { name: 'entity_ids', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/event-queues/:queue_id/bulk-enroll" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"entity_type":"...","entity_ids":"..."}'`,
    },
    {
      method: 'POST',
      path: '/event-queues/:queue_id/remove-enrollment',
      toolName: 'remove_from_auto_queue',
      description: 'Remove a contact or deal from an auto queue (drip sequence) by cancelling their pending steps. Pass queue_id plus ONE of: enrollment_id (most precise — from get_auto_queue_board cards or list_auto_queue_enrollments), contact_id, or deal_id. This is the direct unenrol — no need to build, enable, and trigger a remove_from_event_queue automation. Returns cancelled_count (the real number of pending steps stopped) and a message; cancelled_count: 0 with an explanatory message means nothing was pending for that enrolment (already completed, already removed, or never enrolled).',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'queue_id', type: 'string', required: true, description: 'The auto queue UUID.', in: 'path' },
        { name: 'enrollment_id', type: 'string', required: false, description: 'Preferred. The enrolment UUID from the board or enrollments list.', in: 'body' },
        { name: 'contact_id', type: 'string', required: false, description: 'Cancel this contact\'s pending steps in the queue.', in: 'body' },
        { name: 'deal_id', type: 'string', required: false, description: 'Cancel this deal\'s pending steps in the queue.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/event-queues/:queue_id/remove-enrollment" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"enrollment_id":"...","contact_id":"...","deal_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/event-queues/:queue_id/steps',
      toolName: 'list_auto_queue_steps',
      description: 'List steps in an event queue.',
      scopes: ['automations:read'],
      isWrite: false,
      params: [
        { name: 'queue_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/event-queues/:queue_id/steps" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/event-queues/:queue_id/steps',
      toolName: 'add_auto_queue_step',
      description: 'Add a step to an event queue.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'queue_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'automation_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'step_order', type: 'number', required: true, description: '', in: 'body' },
        { name: 'delay_minutes', type: 'number', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/event-queues/:queue_id/steps" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"automation_id":"...","step_order":"...","delay_minutes":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/event-queues/:queue_id/steps/:step_id',
      toolName: 'update_auto_queue_step',
      description: 'Update a step in an event queue.',
      scopes: ['automations:write'],
      isWrite: true,
      params: [
        { name: 'queue_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'step_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/event-queues/:queue_id/steps/:step_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/event-queues/:queue_id/steps/:step_id',
      toolName: 'delete_auto_queue_step',
      description: 'Delete a step from an event queue.',
      scopes: ['automations:delete'],
      isWrite: true,
      params: [
        { name: 'queue_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'step_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/event-queues/:queue_id/steps/:step_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
