// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/billing.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/billing.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const BILLING: ResourceGroup = {
  id: 'billing',
  label: 'Billing',
  description: 'View billing plans, credit balance, and pricing.',
  endpoints: [
    {
      method: 'GET',
      path: '/billing/balance',
      toolName: 'get_credit_balance',
      description: 'Get the workspace credit balance.',
      scopes: ['billing:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/billing/balance" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/billing/usage',
      toolName: 'get_billing_usage',
      description: 'Get current period billing usage breakdown.',
      scopes: ['billing:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/billing/usage" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/billing/plan',
      toolName: 'get_billing_plan',
      description: 'Get the workspace current billing plan.',
      scopes: ['billing:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/billing/plan" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
      notes: [
        'status values: trialing (no-card 14-day Pro trial), active, past_due, canceled.',
        'billing_plans.is_permissions_locked: true on the Free plan -- the Permissions settings page is locked and role scopes cannot be edited.',
        'billing_plans.trial_credit_grant: credits automatically granted when a trial starts.',
        'billing_plans.plan_key: free, pro, or enterprise.',
        'trial_end: ISO timestamp when the no-card trial expires. Null for non-trial subscriptions.',
        'Free plan restriction: API access is blocked entirely for free plan workspaces. Every request (including GET /billing/plan) returns HTTP 403 with error code PLAN_REQUIRED and an upgrade_url. Use the Portal UI at /settings/billing to view billing for free plan workspaces.',
        'Trial continuity: when a user on a no-card trial calls create_checkout, remaining trial days carry over to the Stripe subscription rather than granting a fresh 14 days.',
      ],
    },
    {
      method: 'GET',
      path: '/billing/pricing',
      toolName: 'get_billing_pricing',
      description: 'Get the public pricing catalog. Free read.',
      scopes: ['billing:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/billing/pricing" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
