// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/crm-templates.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/crm-templates.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const CRM_TEMPLATES: ResourceGroup = {
  id: 'crm-templates',
  label: 'CRM Templates',
  description: 'Manage reusable CRM templates for emails, messages, and automated communications.',
  endpoints: [
    {
      method: 'GET',
      path: '/crm-templates',
      toolName: 'list_crm_templates',
      description: 'List workspace CRM templates (default custom-field templates for entities).',
      scopes: ['crm-templates:read'],
      isWrite: false,
      params: [
        { name: 'type', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/crm-templates" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/crm-templates',
      toolName: 'create_crm_template',
      description: 'Create a CRM template.',
      scopes: ['crm-templates:write'],
      isWrite: true,
      params: [
        { name: 'type', type: 'string', required: true, description: '', in: 'body' },
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'category', type: 'string', required: false, description: '', in: 'body' },
        { name: 'content', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/crm-templates" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"type":"...","name":"...","category":"..."}'`,
    },
    {
      method: 'GET',
      path: '/crm-templates/:template_id',
      toolName: 'get_crm_template',
      description: 'Fetch a CRM template by UUID.',
      scopes: ['crm-templates:read'],
      isWrite: false,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/crm-templates/:template_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/crm-templates/:template_id',
      toolName: 'update_crm_template',
      description: 'Update a CRM template.',
      scopes: ['crm-templates:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'content', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/crm-templates/:template_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","content":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/crm-templates/:template_id',
      toolName: 'delete_crm_template',
      description: 'Delete a CRM template by UUID.',
      scopes: ['crm-templates:delete'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/crm-templates/:template_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
