// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/crm.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/crm.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const CRM: ResourceGroup = {
  id: 'crm',
  label: 'CRM',
  description: 'crm endpoints.',
  endpoints: [
    {
      method: 'GET',
      path: '/crm/export',
      toolName: 'export_crm_data',
      description: 'Export CRM data (contacts, companies, deals, work-orders) to xlsx or csv. Pass `type` and optional filters via query string. Returns a downloadable file.',
      scopes: [],
      isWrite: false,
      params: [
        { name: 'type', type: 'string', required: true, description: 'contacts, customers, deals, or work-orders', in: 'query' },
        { name: 'format', type: 'string', required: false, description: 'xlsx (default) or csv', in: 'query' },
        { name: 'search', type: 'string', required: false, description: '', in: 'query' },
        { name: 'status', type: 'string', required: false, description: '', in: 'query' },
        { name: 'pipeline_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'stage_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'customer_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'contact_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'archived', type: 'string', required: false, description: 'Archive scope (contacts/companies/deals). "false" (default) = active only, "true" = archived only, "all" = both.', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/crm/export" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
