// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/email-templates.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/email-templates.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const EMAIL_TEMPLATES: ResourceGroup = {
  id: 'email-templates',
  label: 'EMAIL_TEMPLATES',
  description: 'email-templates endpoints.',
  endpoints: [
    {
      method: 'POST',
      path: '/email-templates/preview',
      toolName: 'preview_email_template',
      description: 'Preview the rendered HTML for a channel email template, applying optional workspace and per-template chrome overrides. Free read.',
      scopes: ['company:read'],
      isWrite: false,
      params: [
        { name: 'channel', type: 'string', required: true, description: 'Channel template key', in: 'body' },
        { name: 'workspace_settings', type: 'object', required: false, description: '', in: 'body' },
        { name: 'per_template_settings', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/email-templates/preview" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"channel":"...","workspace_settings":"...","per_template_settings":"..."}'`,
    },
    {
      method: 'GET',
      path: '/email-templates/defaults',
      toolName: 'get_email_template_defaults',
      description: 'Get the default email template chrome (subject, intro html) for each channel. Free read.',
      scopes: ['company:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/email-templates/defaults" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
