// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/email.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/email.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const EMAIL: ResourceGroup = {
  id: 'email',
  label: 'Email',
  description: 'Send and receive emails via TrustPager Mail or Gmail, manage threads, view logs, and configure email settings. Supports provider selection for Gmail integration.',
  endpoints: [
    {
      method: 'GET',
      path: '/email/threads',
      toolName: 'list_email_threads',
      description: 'List email threads in the workspace inbox. Filter by contact_id, customer_id, deal_id, unread.',
      scopes: ['email:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
        { name: 'after', type: 'string', required: false, description: '', in: 'query' },
        { name: 'contact_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'customer_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'deal_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'unread', type: 'boolean', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl -X GET \\
  "${API_BASE_URL}/email/threads?search=proposal&direction=inbound&limit=10" \\
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{
  "data": [
    {
      "id": "thread-uuid-...",
      "subject": "RE: Project Proposal",
      "status": "open",
      "is_read": false,
      "message_count": 3,
      "last_message_at": "2026-03-22T15:30:00Z",
      "last_message_direction": "inbound",
      "last_message_preview": "Thanks for the proposal...",
      "participants": [{ "name": "John Smith", "email": "john@example.com" }],
      "linked_entities": {
        "contacts": [{ "id": "...", "first_name": "John", "last_name": "Smith" }],
        "deals": [{ "id": "...", "name": "Website Redesign" }],
        "customers": []
      }
    }
  ],
  "pagination": { "limit": 10, "has_more": false, "next_cursor": null, "prev_cursor": null }
}`,
    },
    {
      method: 'POST',
      path: '/email/threads/mark-read',
      toolName: 'bulk_mark_email_threads_read',
      description: 'Mark multiple email threads as read.',
      scopes: ['email:write'],
      isWrite: true,
      params: [
        { name: 'thread_ids', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \\
  "${API_BASE_URL}/email/threads/mark-read" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{"all":true}'`,
      responseExample: `{
  "data": { "success": true, "updated": 14 },
  "meta": { "credits_remaining": 9487 }
}`,
    },
    {
      method: 'GET',
      path: '/email/threads/:thread_id',
      toolName: 'get_email_thread',
      description: 'Fetch a single email thread by UUID with all messages in chronological order.',
      scopes: ['email:read'],
      isWrite: false,
      params: [
        { name: 'thread_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/email/threads/:thread_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/email/threads/:thread_id',
      toolName: 'update_email_thread',
      description: 'Update an email thread. Mutate read/status, or link the thread to an opportunity / contact / customer so it appears on the deal activity feed and in list_email_threads?opportunity_id=. Useful when send_email was called without an opportunity_id and you need to attach the thread after the fact.',
      scopes: ['email:write'],
      isWrite: true,
      params: [
        { name: 'thread_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'is_read', type: 'boolean', required: false, description: '', in: 'body' },
        { name: 'status', type: 'string', required: false, description: 'active | archived | spam', in: 'body' },
        { name: 'link_opportunity_id', type: 'string', required: false, description: 'Link this thread to an opportunity UUID. Idempotent — safe to call repeatedly.', in: 'body' },
        { name: 'link_contact_id', type: 'string', required: false, description: 'Link this thread to a contact UUID. Idempotent.', in: 'body' },
        { name: 'link_customer_id', type: 'string', required: false, description: 'Link this thread to a customer UUID. Idempotent.', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/email/threads/:thread_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"is_read":"...","status":"...","link_opportunity_id":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/email/threads/:thread_id',
      toolName: 'delete_email_thread',
      description: 'Delete an email thread by UUID.',
      scopes: ['email:write'],
      isWrite: true,
      params: [
        { name: 'thread_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/email/threads/:thread_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/email/threads/:thread_id/messages',
      toolName: 'list_email_thread_messages',
      description: 'List all messages within an email thread.',
      scopes: ['email:read'],
      isWrite: false,
      params: [
        { name: 'thread_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/email/threads/:thread_id/messages" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/email/send',
      toolName: 'send_email',
      description: 'Send a new email from the user default outbound address. For replies use reply_to_email. Costs credits. Pass opportunity_id (canonical) or deal_id (legacy alias) to auto-link the resulting thread to a deal. Set raw_html: true to send a fully-designed HTML email verbatim with no TrustPager header/footer chrome (for pixel-perfect branded sends).',
      scopes: ['email:send'],
      isWrite: true,
      params: [
        { name: 'to_email', type: 'string', required: true, description: '', in: 'body' },
        { name: 'subject', type: 'string', required: true, description: '', in: 'body' },
        { name: 'html_body', type: 'string', required: true, description: '', in: 'body' },
        { name: 'cc', type: 'array', required: false, description: '', in: 'body' },
        { name: 'bcc', type: 'array', required: false, description: '', in: 'body' },
        { name: 'contact_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'opportunity_id', type: 'string', required: false, description: 'Link to an opportunity UUID. Stamps email_logs.deal_id and registers the thread under the opportunity activity feed.', in: 'body' },
        { name: 'deal_id', type: 'string', required: false, description: 'Legacy alias for opportunity_id.', in: 'body' },
        { name: 'raw_html', type: 'boolean', required: false, description: 'When true, send html_body verbatim with no header/footer chrome — for fully-designed branded emails. Default false wraps the body in the standard branded template.', in: 'body' },
      ],
      requestExample: `curl -X POST \\
  "${API_BASE_URL}/email/send" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "to_email": "client@example.com",
    "to_name": "Jane Doe",
    "subject": "Your CRM Setup Report",
    "html_body": "<h1>Hello!</h1><p>See attached report.</p>",
    "mode": "personal",
    "sender_user_id": "user-uuid-...",
    "attachments": [
      {
        "filename": "report.pdf",
        "mime_type": "application/pdf",
        "content": "JVBERi0xLjQg... (base64-encoded file)"
      }
    ]
  }'`,
    },
    {
      method: 'POST',
      path: '/email/send-with-file',
      toolName: 'send_email_with_file',
      description: 'Send an email with a workspace file attached. Costs credits. Pass opportunity_id (canonical) or deal_id (legacy alias) to auto-link the resulting thread to a deal.',
      scopes: ['files:read', 'email:send'],
      isWrite: true,
      params: [
        { name: 'file_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'to_email', type: 'string', required: true, description: '', in: 'body' },
        { name: 'subject', type: 'string', required: true, description: '', in: 'body' },
        { name: 'html_body', type: 'string', required: true, description: '', in: 'body' },
        { name: 'cc', type: 'array', required: false, description: '', in: 'body' },
        { name: 'bcc', type: 'array', required: false, description: '', in: 'body' },
        { name: 'contact_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'opportunity_id', type: 'string', required: false, description: 'Link to an opportunity UUID. Stamps email_logs.deal_id and registers the thread under the opportunity activity feed.', in: 'body' },
        { name: 'deal_id', type: 'string', required: false, description: 'Legacy alias for opportunity_id.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/email/send-with-file" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"file_id":"...","to_email":"...","subject":"..."}'`,
    },
    {
      method: 'POST',
      path: '/email/reply',
      toolName: 'reply_to_email',
      description: 'Reply to an existing email thread, preserving threading. Costs credits.',
      scopes: ['email:send'],
      isWrite: true,
      params: [
        { name: 'thread_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'to_email', type: 'string', required: true, description: '', in: 'body' },
        { name: 'reply_html', type: 'string', required: true, description: '', in: 'body' },
        { name: 'cc', type: 'array', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/email/reply" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"thread_id":"...","to_email":"...","reply_html":"..."}'`,
    },
    {
      method: 'POST',
      path: '/email/save-attachment',
      toolName: 'save_email_attachment',
      description: 'Save an email attachment to the workspace files.',
      scopes: ['email:read', 'files:write'],
      isWrite: true,
      params: [
        { name: 'thread_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'attachment_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'folder_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/email/save-attachment" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"thread_id":"...","attachment_id":"...","folder_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/email/capabilities',
      toolName: 'get_email_capabilities',
      description: 'Get the workspace email send capability summary — connected accounts, daily limits, configured aliases.',
      scopes: ['email:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/email/capabilities" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{
  "data": {
    "authenticated_user": {
      "user_id": "user-uuid-...",
      "name": "Simon Smith",
      "email": "simon@company.com",
      "has_personal_gmail": true,
      "hint": "This is the user who owns the API key. For personal sends, use mode \\"personal\\" with this user's sender_user_id."
    },
    "company_mail": {
      "configured": true,
      "provider": "gmail",
      "gmail_email": "team@example.com",
      "gmail_sender_user_id": "user-uuid-...",
      "connection_status": "active",
      "send_as_aliases": [
        { "email": "team@example.com", "displayName": "Team Name", "isDefault": true }
      ]
    },
    "personal_gmail_users": [
      {
        "user_id": "user-uuid-...",
        "email": "simon@company.com",
        "display_name": "Simon Smith",
        "gmail_address": "simon@gmail.com",
        "send_as_aliases": [
          { "email": "simon@company.com", "displayName": "Simon Smith", "isDefault": true },
          { "email": "team@company.com", "displayName": "Team", "isDefault": false }
        ]
      }
    ]
  }
}`,
    },
    {
      method: 'GET',
      path: '/email/logs',
      toolName: 'list_email_logs',
      description: 'List recent outbound email send log entries.',
      scopes: ['email:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/email/logs" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{
  "data": [
    {
      "id": "log-uuid-...",
      "subject": "Welcome to TrustPager",
      "recipient_email": "client@example.com",
      "recipient_name": "Jane Doe",
      "sender_email": "team@company.com",
      "sender_name": "Acme Corp",
      "sender_user_id": null,
      "email_type": "automation",
      "status": "delivered",
      "provider": "postmark",
      "cc": null,
      "thread_id": null,
      "contact_id": "contact-uuid-...",
      "customer_id": null,
      "deal_id": null,
      "created_at": "2026-04-14T10:00:00Z"
    }
  ],
  "pagination": { "limit": 25, "has_more": false, "next_cursor": null }
}`,
    },
    {
      method: 'GET',
      path: '/email/configs',
      toolName: 'list_email_configs',
      description: 'List configured outbound email senders (from-address aliases).',
      scopes: ['email:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/email/configs" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/email/configs',
      toolName: 'create_email_config',
      description: 'Create a new outbound email sender config.',
      scopes: ['email-config:write'],
      isWrite: true,
      params: [
        { name: 'from_email_handle', type: 'string', required: true, description: '', in: 'body' },
        { name: 'from_name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'staff_email', type: 'string', required: true, description: '', in: 'body' },
        { name: 'reply_to', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/email/configs" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"from_email_handle":"...","from_name":"...","staff_email":"..."}'`,
    },
    {
      method: 'GET',
      path: '/email/configs/:config_id',
      toolName: 'get_email_config',
      description: 'Fetch a single email config by UUID.',
      scopes: ['email:read'],
      isWrite: false,
      params: [
        { name: 'config_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/email/configs/:config_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/email/configs/:config_id',
      toolName: 'update_email_config',
      description: 'Update an email config. To send from your own verified domain, pass from_email_handle (local-part) + from_email_domain (a verified sending domain). Set preferred_provider to choose the workspace rail.',
      scopes: ['email-config:write'],
      isWrite: true,
      params: [
        { name: 'config_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'from_name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'reply_to', type: 'string', required: false, description: '', in: 'body' },
        { name: 'staff_email', type: 'string', required: false, description: '', in: 'body' },
        { name: 'from_email_handle', type: 'string', required: false, description: 'Local-part of the sender address (before the @). With no from_email_domain it composes <handle>@mail.trustpager.net.', in: 'body' },
        { name: 'from_email_domain', type: 'string', required: false, description: 'A verified sending domain for this workspace (see list_sending_domains). Composes from_email = <handle>@<domain>, e.g. support@yourcompany.com. Must be verified first.', in: 'body' },
        { name: 'preferred_provider', type: 'string', required: false, description: 'Default Workspace Email Address rail: "trustpager_mail" (send via your verified domain, never expires) or "gmail" (send via connected Team Gmail).', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/email/configs/:config_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"from_name":"...","reply_to":"...","staff_email":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/email/configs/:config_id',
      toolName: 'delete_email_config',
      description: 'Delete an email config by UUID. Destructive.',
      scopes: ['email-config:delete'],
      isWrite: true,
      params: [
        { name: 'config_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/email/configs/:config_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/email/sending-domains',
      toolName: 'list_sending_domains',
      description: 'List the workspace\'s bring-your-own sending domains and their verification status. A verified domain lets you send from your own address (e.g. support@yourcompany.com) instead of @mail.trustpager.net.',
      scopes: ['email:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/email/sending-domains" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/email/sending-domains',
      toolName: 'register_sending_domain',
      description: 'Register your own domain for sending. Returns two DNS records (a DKIM TXT and a Return-Path CNAME) to add at your DNS host — no SPF or MX change, your existing inbox keeps receiving. After adding them, call verify_sending_domain. Once verified, set it as the sending address via update_email_config { from_email_domain }.',
      scopes: ['email-config:write'],
      isWrite: true,
      params: [
        { name: 'domain', type: 'string', required: true, description: 'Bare domain, e.g. "yourcompany.com". No scheme, no @, no path.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/email/sending-domains" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"domain":"..."}'`,
    },
    {
      method: 'POST',
      path: '/email/sending-domains/:domain_id/verify',
      toolName: 'verify_sending_domain',
      description: 'Re-check DNS for a sending domain and return its current verification state. Call after adding the DNS records. DNS can take a few minutes to propagate. status becomes "verified" once both DKIM and Return-Path resolve.',
      scopes: ['email-config:write'],
      isWrite: true,
      params: [
        { name: 'domain_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/email/sending-domains/:domain_id/verify" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/email/sending-domains/:domain_id',
      toolName: 'remove_sending_domain',
      description: 'Remove a sending domain. Refused if it is currently your sending address (change update_email_config { from_email_domain } first). Otherwise removes it from TrustPager Mail entirely.',
      scopes: ['email-config:delete'],
      isWrite: true,
      params: [
        { name: 'domain_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/email/sending-domains/:domain_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
