// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/exports.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/exports.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const EXPORTS: ResourceGroup = {
  id: 'exports',
  label: 'EXPORTS',
  description: 'exports endpoints.',
  endpoints: [
    {
      method: 'GET',
      path: '/exports/field-catalog',
      toolName: 'get_export_field_catalog',
      description: 'Get the discoverable shape of valid filter fields and column sources.',
      scopes: ['exports:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/exports/field-catalog" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/exports/templates',
      toolName: 'list_export_templates',
      description: 'List saved CRM export templates.',
      scopes: ['exports:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/exports/templates" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/exports/templates',
      toolName: 'create_export_template',
      description: 'Create an export template.',
      scopes: ['exports:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'root_entity', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/exports/templates" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","root_entity":"..."}'`,
    },
    {
      method: 'GET',
      path: '/exports/templates/:template_id',
      toolName: 'get_export_template',
      description: 'Fetch an export template by UUID.',
      scopes: ['exports:read'],
      isWrite: false,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/exports/templates/:template_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/exports/templates/:template_id',
      toolName: 'update_export_template',
      description: 'Update an export template.',
      scopes: ['exports:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/exports/templates/:template_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/exports/templates/:template_id',
      toolName: 'delete_export_template',
      description: 'Delete an export template.',
      scopes: ['exports:delete'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/exports/templates/:template_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/exports/templates/:template_id/views',
      toolName: 'list_export_template_views',
      description: 'List views on an export template.',
      scopes: ['exports:read'],
      isWrite: false,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/exports/templates/:template_id/views" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/exports/templates/:template_id/views',
      toolName: 'create_export_template_view',
      description: 'Create a view on an export template.',
      scopes: ['exports:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/exports/templates/:template_id/views" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"..."}'`,
    },
    {
      method: 'GET',
      path: '/exports/templates/:template_id/views/:view_id',
      toolName: 'get_export_template_view',
      description: 'Fetch a view by UUID.',
      scopes: ['exports:read'],
      isWrite: false,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'view_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/exports/templates/:template_id/views/:view_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/exports/templates/:template_id/views/:view_id',
      toolName: 'update_export_template_view',
      description: 'Update a view.',
      scopes: ['exports:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'view_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/exports/templates/:template_id/views/:view_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/exports/templates/:template_id/views/:view_id',
      toolName: 'delete_export_template_view',
      description: 'Delete a view.',
      scopes: ['exports:delete'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'view_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/exports/templates/:template_id/views/:view_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/exports/templates/:template_id/preview',
      toolName: 'preview_export_template',
      description: 'Preview an export template (free read).',
      scopes: ['exports:read'],
      isWrite: false,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/exports/templates/:template_id/preview" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/exports/templates/:template_id/run',
      toolName: 'run_export_template',
      description: 'Run an export template.',
      scopes: ['exports:read'],
      isWrite: false,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/exports/templates/:template_id/run" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
