// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/forms.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/forms.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const FORMS: ResourceGroup = {
  id: 'forms',
  label: 'Forms',
  description: 'Create form templates, manage fields, send forms to contacts, and view submissions. Fields support CRM Variable Injection - map a field to a CRM variable so submitted values are written back to the linked deal, contact, or account before automations run.',
  endpoints: [
    {
      method: 'GET',
      path: '/forms/folders',
      toolName: 'list_form_folders',
      description: 'List form folders.',
      scopes: ['forms:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/forms/folders" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/forms/folders',
      toolName: 'create_form_folder',
      description: 'Create a form folder.',
      scopes: ['forms:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/forms/folders" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/forms/folders/:folder_id',
      toolName: 'update_form_folder',
      description: 'Update a form folder.',
      scopes: ['forms:write'],
      isWrite: true,
      params: [
        { name: 'folder_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/forms/folders/:folder_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/forms/folders/:folder_id',
      toolName: 'delete_form_folder',
      description: 'Delete a form folder.',
      scopes: ['forms:delete'],
      isWrite: true,
      params: [
        { name: 'folder_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/forms/folders/:folder_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/forms/submissions',
      toolName: 'list_form_submissions',
      description: 'List form submissions.',
      scopes: ['forms:read'],
      isWrite: false,
      params: [
        { name: 'template_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/forms/submissions" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/forms/submissions/internal-fill',
      toolName: 'create_internal_form_submission',
      description: 'Create an internal-fill submission for staff entry. No email, PIN pre-cleared.',
      scopes: ['forms:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'deal_id', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/forms/submissions/internal-fill" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"template_id":"...","deal_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/forms/submissions/:submission_id',
      toolName: 'get_form_submission',
      description: 'Fetch a form submission by UUID.',
      scopes: ['forms:read'],
      isWrite: false,
      params: [
        { name: 'submission_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/forms/submissions/:submission_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/forms/submissions/:submission_id/resend',
      toolName: 'resend_form_submission',
      description: 'Resend a form submission invitation.',
      scopes: ['forms:write'],
      isWrite: true,
      params: [
        { name: 'submission_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/forms/submissions/:submission_id/resend" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/forms/submissions/:submission_id/void',
      toolName: 'void_form_submission',
      description: 'Void a form submission.',
      scopes: ['forms:write'],
      isWrite: true,
      params: [
        { name: 'submission_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/forms/submissions/:submission_id/void" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/forms/submissions/:submission_id',
      toolName: 'delete_form_submission',
      description: 'Permanently delete a form submission (and any uploaded files). Optional ?delete_archived_pdf=true also removes the auto-archived PDF in the Documents library. Cannot be undone.',
      scopes: ['forms:delete'],
      isWrite: true,
      params: [
        { name: 'submission_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'delete_archived_pdf', type: 'boolean', required: false, description: 'When true, also deletes the auto-archived PDF stored in crm_documents from this submission.', in: 'query' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/forms/submissions/:submission_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/forms/send',
      toolName: 'send_form',
      description: 'Send a form to a recipient. Costs credits.',
      scopes: ['forms:send'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'recipient_email', type: 'string', required: true, description: '', in: 'body' },
        { name: 'recipient_name', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/forms/send" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"template_id":"...","recipient_email":"...","recipient_name":"..."}'`,
    },
    {
      method: 'GET',
      path: '/forms/templates',
      toolName: 'list_form_templates',
      description: 'List form templates.',
      scopes: ['forms:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/forms/templates" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/forms/templates',
      toolName: 'create_form_template',
      description: 'Create a form template.',
      scopes: ['forms:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/forms/templates" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"..."}'`,
    },
    {
      method: 'GET',
      path: '/forms/templates/:template_id',
      toolName: 'get_form_template',
      description: 'Fetch a form template by UUID.',
      scopes: ['forms:read'],
      isWrite: false,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/forms/templates/:template_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/forms/templates/:template_id',
      toolName: 'update_form_template',
      description: 'Update a form template.',
      scopes: ['forms:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/forms/templates/:template_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/forms/templates/:template_id',
      toolName: 'delete_form_template',
      description: 'Delete a form template.',
      scopes: ['forms:delete'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/forms/templates/:template_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/forms/templates/:template_id/duplicate',
      toolName: 'duplicate_form_template',
      description: 'Duplicate a form template.',
      scopes: ['forms:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/forms/templates/:template_id/duplicate" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/forms/templates/:template_id/archive',
      toolName: 'archive_form_template',
      description: 'Archive a form template.',
      scopes: ['forms:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/forms/templates/:template_id/archive" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/forms/templates/:template_id/fields',
      toolName: 'list_form_fields',
      description: 'List fields on a form template.',
      scopes: ['forms:read'],
      isWrite: false,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/forms/templates/:template_id/fields" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/forms/templates/:template_id/fields',
      toolName: 'add_form_field',
      description: 'Add a field to a form template.',
      scopes: ['forms:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'type', type: 'string', required: true, description: '', in: 'body' },
        { name: 'label', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/forms/templates/:template_id/fields" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"type":"...","label":"..."}'`,
    },
    {
      method: 'POST',
      path: '/forms/templates/:template_id/fields/reorder',
      toolName: 'reorder_form_fields',
      description: 'Reorder fields on a form template.',
      scopes: ['forms:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'field_ids', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/forms/templates/:template_id/fields/reorder" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"field_ids":"..."}'`,
    },
    {
      method: 'POST',
      path: '/forms/templates/:template_id/wiring',
      toolName: 'bulk_update_form_field_wiring',
      description: 'Bulk-set CRM-variable wiring on form fields.',
      scopes: ['forms:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'wiring', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/forms/templates/:template_id/wiring" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"wiring":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/forms/templates/:template_id/fields/:field_id',
      toolName: 'update_form_field',
      description: 'Update a form field.',
      scopes: ['forms:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'field_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/forms/templates/:template_id/fields/:field_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/forms/templates/:template_id/fields/:field_id',
      toolName: 'delete_form_field',
      description: 'Delete a form field.',
      scopes: ['forms:delete'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'field_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/forms/templates/:template_id/fields/:field_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
