// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/images.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/images.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const IMAGES: ResourceGroup = {
  id: 'images',
  label: 'IMAGES',
  description: 'images endpoints.',
  endpoints: [
    {
      method: 'POST',
      path: '/images/optimize',
      toolName: 'optimize_image',
      description: 'Optimize a stored image — resize and generate WebP variants for fast delivery.',
      scopes: ['files:write'],
      isWrite: true,
      params: [
        { name: 'file_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'max_width', type: 'number', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/images/optimize" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"file_id":"...","max_width":"..."}'`,
    },
  ],
};
