// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/invoices.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/invoices.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const INVOICES: ResourceGroup = {
  id: 'invoices',
  label: 'INVOICES',
  description: 'invoices endpoints.',
  endpoints: [
    {
      method: 'GET',
      path: '/invoices',
      toolName: 'list_invoices',
      description: 'List native invoices. Filter by opportunity_id, customer_id, status, source_platform, external_order_id, or search invoice number / reference.',
      scopes: ['invoices:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
        { name: 'after', type: 'string', required: false, description: '', in: 'query' },
        { name: 'opportunity_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'customer_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'status', type: 'string', required: false, description: '', in: 'query' },
        { name: 'source_platform', type: 'string', required: false, description: '', in: 'query' },
        { name: 'external_order_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'search', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/invoices" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/invoices',
      toolName: 'create_invoice',
      description: 'Create a native invoice, optionally linked to an opportunity and with inline line_items (header totals are computed from the lines). Pass external_order_id to link an ecommerce order.',
      scopes: ['invoices:write'],
      isWrite: true,
      params: [
        { name: 'opportunity_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'customer_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'external_order_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'invoice_number', type: 'string', required: false, description: '', in: 'body' },
        { name: 'status', type: 'string', required: false, description: '', in: 'body' },
        { name: 'issue_date', type: 'string', required: false, description: '', in: 'body' },
        { name: 'due_date', type: 'string', required: false, description: '', in: 'body' },
        { name: 'currency_code', type: 'string', required: false, description: '', in: 'body' },
        { name: 'reference', type: 'string', required: false, description: '', in: 'body' },
        { name: 'contact_name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'line_items', type: 'array', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/invoices" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"opportunity_id":"...","customer_id":"...","external_order_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/invoices/:invoice_id',
      toolName: 'get_invoice',
      description: 'Fetch a single native invoice by UUID, including its line_items.',
      scopes: ['invoices:read'],
      isWrite: false,
      params: [
        { name: 'invoice_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/invoices/:invoice_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/invoices/:invoice_id',
      toolName: 'update_invoice',
      description: 'Update a native invoice header (status, dates, reference, amount_paid, etc.). amount_due is recomputed. Pass only the fields you want to change.',
      scopes: ['invoices:write'],
      isWrite: true,
      params: [
        { name: 'invoice_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'status', type: 'string', required: false, description: '', in: 'body' },
        { name: 'due_date', type: 'string', required: false, description: '', in: 'body' },
        { name: 'reference', type: 'string', required: false, description: '', in: 'body' },
        { name: 'amount_paid', type: 'number', required: false, description: '', in: 'body' },
        { name: 'amount_credited', type: 'number', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/invoices/:invoice_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"status":"...","due_date":"...","reference":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/invoices/:invoice_id',
      toolName: 'delete_invoice',
      description: 'Delete a native invoice by UUID (its line items are removed too). Destructive.',
      scopes: ['invoices:write'],
      isWrite: true,
      params: [
        { name: 'invoice_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/invoices/:invoice_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/invoices/:invoice_id/line-items',
      toolName: 'add_invoice_line_item',
      description: 'Add one line item to a native invoice. Requires description; line_total and invoice totals are computed.',
      scopes: ['invoices:write'],
      isWrite: true,
      params: [
        { name: 'invoice_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'product_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'description', type: 'string', required: true, description: '', in: 'body' },
        { name: 'quantity', type: 'number', required: false, description: '', in: 'body' },
        { name: 'unit_price', type: 'number', required: false, description: '', in: 'body' },
        { name: 'discount_percent', type: 'number', required: false, description: '', in: 'body' },
        { name: 'tax_amount', type: 'number', required: false, description: '', in: 'body' },
        { name: 'external_line_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/invoices/:invoice_id/line-items" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"product_id":"...","description":"...","quantity":"..."}'`,
    },
    {
      method: 'POST',
      path: '/invoices/:invoice_id/line-items/bulk',
      toolName: 'bulk_add_invoice_line_items',
      description: 'Add up to 500 line items to a native invoice in one call. Body: { line_items: [...] }, each item the same shape as add_invoice_line_item. Used for invoice-data imports.',
      scopes: ['invoices:write'],
      isWrite: true,
      params: [
        { name: 'invoice_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'line_items', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/invoices/:invoice_id/line-items/bulk" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"line_items":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/invoices/:invoice_id/line-items/:line_id',
      toolName: 'update_invoice_line_item',
      description: 'Update one line item on a native invoice. line_total and invoice totals recompute when pricing fields change.',
      scopes: ['invoices:write'],
      isWrite: true,
      params: [
        { name: 'invoice_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'line_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'description', type: 'string', required: false, description: '', in: 'body' },
        { name: 'quantity', type: 'number', required: false, description: '', in: 'body' },
        { name: 'unit_price', type: 'number', required: false, description: '', in: 'body' },
        { name: 'discount_percent', type: 'number', required: false, description: '', in: 'body' },
        { name: 'tax_amount', type: 'number', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/invoices/:invoice_id/line-items/:line_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"description":"...","quantity":"...","unit_price":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/invoices/:invoice_id/line-items/:line_id',
      toolName: 'delete_invoice_line_item',
      description: 'Delete one line item from a native invoice. Invoice totals recompute. Destructive.',
      scopes: ['invoices:write'],
      isWrite: true,
      params: [
        { name: 'invoice_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'line_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/invoices/:invoice_id/line-items/:line_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
