// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/knowledge-bases.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/knowledge-bases.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const KNOWLEDGE_BASES: ResourceGroup = {
  id: 'knowledge-bases',
  label: 'KNOWLEDGE_BASES',
  description: 'knowledge-bases endpoints.',
  endpoints: [
    {
      method: 'GET',
      path: '/knowledge-bases',
      toolName: 'list_knowledge_bases',
      description: 'List knowledge bases in the workspace. Pass agent_type + agent_id to list only the KBs attached to a given voice or workflow agent.',
      scopes: ['knowledge:read'],
      isWrite: false,
      params: [
        { name: 'agent_type', type: 'string', required: false, description: '', in: 'query' },
        { name: 'agent_id', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/knowledge-bases" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/knowledge-bases',
      toolName: 'create_knowledge_base',
      description: 'Create a named knowledge base. Populate it via sync-help-center, sync-products, or by creating entries with this kb_id, then attach it to agents.',
      scopes: ['knowledge:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'description', type: 'string', required: false, description: '', in: 'body' },
        { name: 'auto_resync_enabled', type: 'boolean', required: false, description: '', in: 'body' },
        { name: 'resync_frequency', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/knowledge-bases" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","description":"...","auto_resync_enabled":"..."}'`,
    },
    {
      method: 'POST',
      path: '/knowledge-bases/adopt',
      toolName: 'adopt_retell_knowledge_base',
      description: 'Adopt an existing voice-provider knowledge base into the unified system: links it in place (no duplicate), imports its web-page sources into search, and attaches any voice agents already using it. Pass retell_kb_id.',
      scopes: ['knowledge:write'],
      isWrite: true,
      params: [
        { name: 'retell_kb_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/knowledge-bases/adopt" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"retell_kb_id":"...","name":"..."}'`,
    },
    {
      method: 'GET',
      path: '/knowledge-bases/:kb_id',
      toolName: 'get_knowledge_base',
      description: 'Fetch a knowledge base by UUID, with entry and attached-agent counts.',
      scopes: ['knowledge:read'],
      isWrite: false,
      params: [
        { name: 'kb_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/knowledge-bases/:kb_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/knowledge-bases/:kb_id',
      toolName: 'update_knowledge_base',
      description: 'Update a knowledge base (name, description, auto-resync settings).',
      scopes: ['knowledge:write'],
      isWrite: true,
      params: [
        { name: 'kb_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'description', type: 'string', required: false, description: '', in: 'body' },
        { name: 'auto_resync_enabled', type: 'boolean', required: false, description: '', in: 'body' },
        { name: 'resync_frequency', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/knowledge-bases/:kb_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","description":"...","auto_resync_enabled":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/knowledge-bases/:kb_id',
      toolName: 'delete_knowledge_base',
      description: 'Delete a knowledge base. Its entries are kept (unlinked); agent attachments are removed.',
      scopes: ['knowledge:delete'],
      isWrite: true,
      params: [
        { name: 'kb_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/knowledge-bases/:kb_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/knowledge-bases/:kb_id/entries',
      toolName: 'list_knowledge_base_entries',
      description: 'List the entries (documents) inside a knowledge base.',
      scopes: ['knowledge:read'],
      isWrite: false,
      params: [
        { name: 'kb_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
        { name: 'after', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/knowledge-bases/:kb_id/entries" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/knowledge-bases/:kb_id/sync-help-center',
      toolName: 'sync_knowledge_base_help_center',
      description: 'Ingest help-center articles into a knowledge base as embedded entries. Pass article_ids to select specific articles, or omit to sync all. Idempotent.',
      scopes: ['knowledge:write'],
      isWrite: true,
      params: [
        { name: 'kb_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'article_ids', type: 'array', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/knowledge-bases/:kb_id/sync-help-center" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"article_ids":"..."}'`,
    },
    {
      method: 'POST',
      path: '/knowledge-bases/:kb_id/sync-products',
      toolName: 'sync_knowledge_base_products',
      description: 'Ingest the active CRM product catalog into a knowledge base as embedded entries. Idempotent.',
      scopes: ['knowledge:write'],
      isWrite: true,
      params: [
        { name: 'kb_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/knowledge-bases/:kb_id/sync-products" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/knowledge-bases/:kb_id/ingest-url',
      toolName: 'ingest_knowledge_base_url',
      description: 'Fetch a web page, extract its text, and add it to a knowledge base as an embedded entry. Idempotent per URL.',
      scopes: ['knowledge:write'],
      isWrite: true,
      params: [
        { name: 'kb_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'url', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/knowledge-bases/:kb_id/ingest-url" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"url":"..."}'`,
    },
    {
      method: 'POST',
      path: '/knowledge-bases/:kb_id/ingest-text',
      toolName: 'ingest_knowledge_base_text',
      description: 'Add a block of text (e.g. an uploaded document\'s content) to a knowledge base as an embedded entry.',
      scopes: ['knowledge:write'],
      isWrite: true,
      params: [
        { name: 'kb_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'title', type: 'string', required: true, description: '', in: 'body' },
        { name: 'text', type: 'string', required: true, description: '', in: 'body' },
        { name: 'source_ref', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/knowledge-bases/:kb_id/ingest-text" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"title":"...","text":"...","source_ref":"..."}'`,
    },
    {
      method: 'GET',
      path: '/knowledge-bases/:kb_id/agents',
      toolName: 'list_knowledge_base_agents',
      description: 'List the agents (voice or workflow) a knowledge base is attached to.',
      scopes: ['knowledge:read'],
      isWrite: false,
      params: [
        { name: 'kb_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/knowledge-bases/:kb_id/agents" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/knowledge-bases/:kb_id/attach',
      toolName: 'attach_knowledge_base',
      description: 'Attach a knowledge base to an agent so the agent\'s searches are grounded in it. agent_type is \'voice\' or \'workflow\'; agent_id is the voice agent or workflow agent UUID.',
      scopes: ['knowledge:write'],
      isWrite: true,
      params: [
        { name: 'kb_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'agent_type', type: 'string', required: true, description: '', in: 'body' },
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/knowledge-bases/:kb_id/attach" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"agent_type":"...","agent_id":"..."}'`,
    },
    {
      method: 'POST',
      path: '/knowledge-bases/:kb_id/detach',
      toolName: 'detach_knowledge_base',
      description: 'Detach a knowledge base from an agent. The KB and its entries are kept.',
      scopes: ['knowledge:write'],
      isWrite: true,
      params: [
        { name: 'kb_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'agent_type', type: 'string', required: true, description: '', in: 'body' },
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/knowledge-bases/:kb_id/detach" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"agent_type":"...","agent_id":"..."}'`,
    },
  ],
};
