// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/knowledge.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/knowledge.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const KNOWLEDGE: ResourceGroup = {
  id: 'knowledge',
  label: 'AI Knowledge',
  description: 'Manage company AI Knowledge entries with semantic search powered by Voyage AI embeddings. Use for policies, FAQs, agent instructions, and product documentation.',
  endpoints: [
    {
      method: 'POST',
      path: '/knowledge/search',
      toolName: 'search_knowledge',
      description: 'Semantic search across the workspace knowledge base. Use to find relevant context before answering a customer question.',
      scopes: ['knowledge:read'],
      isWrite: false,
      params: [
        { name: 'query', type: 'string', required: true, description: 'Search query', in: 'body' },
        { name: 'limit', type: 'number', required: false, description: 'Max results (default 5)', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/knowledge/search" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"query":"...","limit":"..."}'`,
    },
    {
      method: 'POST',
      path: '/knowledge/sync-from-products',
      toolName: 'sync_knowledge_from_products',
      description: 'Refresh the knowledge base entries that auto-generate from the product catalog.',
      scopes: ['knowledge:write'],
      isWrite: true,
      requestExample: `curl -X POST \
  "${API_BASE_URL}/knowledge/sync-from-products" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/knowledge',
      toolName: 'list_knowledge',
      description: 'List entries in the workspace knowledge base. Supports filtering by category, tag, and text search.',
      scopes: ['knowledge:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
        { name: 'after', type: 'string', required: false, description: '', in: 'query' },
        { name: 'category', type: 'string', required: false, description: '', in: 'query' },
        { name: 'search', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/knowledge" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/knowledge',
      toolName: 'create_knowledge',
      description: 'Create a new knowledge base entry. Requires title and content.',
      scopes: ['knowledge:write'],
      isWrite: true,
      params: [
        { name: 'title', type: 'string', required: true, description: '', in: 'body' },
        { name: 'content', type: 'string', required: true, description: '', in: 'body' },
        { name: 'category', type: 'string', required: false, description: '', in: 'body' },
        { name: 'tags', type: 'array', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/knowledge" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"title":"...","content":"...","category":"..."}'`,
    },
    {
      method: 'GET',
      path: '/knowledge/:knowledge_id',
      toolName: 'get_knowledge',
      description: 'Fetch a single knowledge base entry by UUID. Returns full content.',
      scopes: ['knowledge:read'],
      isWrite: false,
      params: [
        { name: 'knowledge_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/knowledge/:knowledge_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/knowledge/:knowledge_id',
      toolName: 'update_knowledge',
      description: 'Update a knowledge base entry. Pass only the fields you want to change.',
      scopes: ['knowledge:write'],
      isWrite: true,
      params: [
        { name: 'knowledge_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'title', type: 'string', required: false, description: '', in: 'body' },
        { name: 'content', type: 'string', required: false, description: '', in: 'body' },
        { name: 'category', type: 'string', required: false, description: '', in: 'body' },
        { name: 'tags', type: 'array', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/knowledge/:knowledge_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"title":"...","content":"...","category":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/knowledge/:knowledge_id',
      toolName: 'delete_knowledge',
      description: 'Delete a knowledge base entry by UUID. Destructive.',
      scopes: ['knowledge:delete'],
      isWrite: true,
      params: [
        { name: 'knowledge_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/knowledge/:knowledge_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
