// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/lead-gen.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/lead-gen.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const LEAD_GEN: ResourceGroup = {
  id: 'lead-gen',
  label: 'Lead Generation',
  description: 'Search for businesses via Google Maps (powered by Apify), match against existing CRM records, save search configurations, and import results as contacts, customers, and deals. Requires lead-gen:read, lead-gen:write, or lead-gen:delete scopes.',
  endpoints: [
    {
      method: 'POST',
      path: '/lead-gen/search',
      toolName: 'lead_gen_search',
      description: 'Start a new lead-gen search via Apify Google Maps. Costs credits.',
      scopes: ['lead-gen:write'],
      isWrite: true,
      params: [
        { name: 'query', type: 'string', required: true, description: '', in: 'body' },
        { name: 'location', type: 'string', required: true, description: '', in: 'body' },
        { name: 'limit', type: 'number', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \\
  "${API_BASE_URL}/lead-gen/search" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "query": "electricians",
    "location": "Sydney, NSW",
    "max_results": 50,
    "place_minimum_stars": "three",
    "website_filter": "withWebsite"
  }'`,
      responseExample: `{
  "data": {
    "id": "8685d0d4-...",
    "status": "completed",
    "search_query": "electricians",
    "location": "Sydney, NSW",
    "max_results": 50,
    "result_count": 42,
    "new_result_count": 38,
    "already_in_crm_count": 4,
    "credits_charged": 10,
    "created_at": "2026-04-17T04:00:00Z",
    "completed_at": "2026-04-17T04:00:12Z",
    "results": [
      {
        "id": "a1b2c3d4-...",
        "business_name": "Sydney Electrical Services",
        "category": "Electrician",
        "address": "123 George St, Sydney NSW 2000",
        "city": "Sydney",
        "state": "NSW",
        "postal_code": "2000",
        "country_code": "AU",
        "phone": "+61299991234",
        "website": "https://sydneyelectrical.com.au",
        "email": null,
        "rating": 4.8,
        "reviews_count": 156,
        "google_maps_url": "https://maps.google.com/?cid=...",
        "match_status": "new",
        "matched_contact_id": null,
        "matched_customer_id": null,
        "imported": false,
        "imported_at": null
      }
    ],
    "meta": { "url": "https://app.trustpager.com/growth/lead-gen" }
  }
}`,
    },
    {
      method: 'GET',
      path: '/lead-gen/searches',
      toolName: 'lead_gen_list_searches',
      description: 'List past lead-gen searches.',
      scopes: ['lead-gen:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl -X GET \\
  "${API_BASE_URL}/lead-gen/searches?status=completed&limit=10" \\
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{
  "data": [
    {
      "id": "8685d0d4-...",
      "search_query": "electricians",
      "location": "Sydney, NSW",
      "status": "completed",
      "result_count": 42,
      "new_result_count": 38,
      "already_in_crm_count": 4,
      "credits_charged": 10,
      "created_at": "2026-04-17T04:00:00Z",
      "completed_at": "2026-04-17T04:00:12Z"
    }
  ],
  "pagination": { "limit": 10, "has_more": false, "next_cursor": null }
}`,
    },
    {
      method: 'GET',
      path: '/lead-gen/searches/:search_id',
      toolName: 'lead_gen_get_search',
      description: 'Fetch a lead-gen search by UUID with its results.',
      scopes: ['lead-gen:read'],
      isWrite: false,
      params: [
        { name: 'search_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/lead-gen/searches/:search_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/lead-gen/searches/:search_id/cancel',
      toolName: 'lead_gen_cancel_search',
      description: 'Force-cancel a running lead-gen search and refund any credits that were charged. Use this to clear searches stuck in "running" — typically because the dispatch edge function timed out / was killed before it could mark the row completed or failed, leaving the row orphaned and the user\'s credits locked up. Only searches in status="running" can be cancelled; completed/failed/cancelled rows return a 400. On success the row flips to status="cancelled" with error_message="Cancelled by user" and credits_charged is refunded via a "refund" ledger transaction. Response includes credits_refunded and credit_balance_after for confirmation.',
      scopes: ['lead-gen:write'],
      isWrite: true,
      params: [
        { name: 'search_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/lead-gen/searches/:search_id/cancel" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/lead-gen/import',
      toolName: 'lead_gen_import',
      description: 'Convert lead_gen_results into CRM contacts + customers (+ optional pipeline opportunity). Every conversion requires a per-result contact mapping — first_name is mandatory for each row so the CRM contact has a real person attached, not the business name. Find-or-create semantics: existing customers matched by name and contacts matched by email are reused instead of duplicated. Importing a lead that\'s already fully in CRM is a no-op; partial/zombie imports (imported flag flipped but contact record never created) are retried automatically.',
      scopes: ['lead-gen:write'],
      isWrite: true,
      params: [
        { name: 'contacts', type: 'array', required: true, description: 'Required. Per-result contact mapping. Each entry creates or reuses a contact with the supplied name + email + phone, links to the lead\'s customer record (by business name), and optionally creates a deal in the named pipeline + stage.', in: 'body' },
        { name: 'pipeline_id', type: 'string', required: false, description: 'Optional. When set with stage_id, creates a deal per imported lead and places it in this pipeline.', in: 'body' },
        { name: 'stage_id', type: 'string', required: false, description: 'Optional. Required when pipeline_id is provided.', in: 'body' },
        { name: 'lead_source', type: 'string', required: false, description: 'Defaults to "Lead Generation".', in: 'body' },
        { name: 'tags', type: 'array', required: false, description: 'Optional tags applied to the created deal(s).', in: 'body' },
      ],
      requestExample: `curl -X POST \\
  "${API_BASE_URL}/lead-gen/import" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "result_ids": ["a1b2c3d4-...", "b2c3d4e5-..."],
    "pipeline_id": "pipe-uuid-...",
    "stage_id": "stage-uuid-...",
    "tags": ["lead-gen", "electricians"],
    "lead_source": "Google Maps"
  }'`,
      responseExample: `{
  "data": {
    "imported_count": 2,
    "total_requested": 3,
    "imported": [
      {
        "result_id": "a1b2c3d4-...",
        "contact_id": "contact-uuid-...",
        "customer_id": "customer-uuid-...",
        "deal_id": "deal-uuid-..."
      },
      {
        "result_id": "b2c3d4e5-...",
        "contact_id": "contact-uuid-2...",
        "customer_id": "customer-uuid-2...",
        "deal_id": null
      },
      {
        "result_id": "c3d4e5f6-...",
        "contact_id": null,
        "customer_id": null,
        "deal_id": null,
        "error": "duplicate key value violates unique constraint"
      }
    ]
  }
}`,
    },
    {
      method: 'GET',
      path: '/lead-gen/saved-searches',
      toolName: 'lead_gen_list_saved_searches',
      description: 'List saved lead-gen searches.',
      scopes: ['lead-gen:read'],
      isWrite: false,
      requestExample: `curl -X GET \\
  "${API_BASE_URL}/lead-gen/saved-searches" \\
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{
  "data": [
    {
      "id": "7d05612a-...",
      "name": "Sydney Electricians",
      "search_query": "electricians",
      "location": "Sydney, NSW",
      "max_results": 100,
      "run_count": 5,
      "last_run_at": "2026-04-16T10:00:00Z",
      "is_archived": false
    }
  ],
  "pagination": { "limit": 25, "has_more": false, "next_cursor": null }
}`,
    },
    {
      method: 'POST',
      path: '/lead-gen/saved-searches',
      toolName: 'lead_gen_create_saved_search',
      description: 'Save a lead-gen search query for reuse.',
      scopes: ['lead-gen:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'search_query', type: 'string', required: true, description: '', in: 'body' },
        { name: 'location', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \\
  "${API_BASE_URL}/lead-gen/saved-searches" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "name": "Sydney Electricians",
    "search_query": "electricians",
    "location": "Sydney, NSW",
    "max_results": 100,
    "default_tags": ["lead-gen", "electricians"]
  }'`,
      responseExample: `{
  "data": {
    "id": "7d05612a-...",
    "name": "Sydney Electricians",
    "search_query": "electricians",
    "location": "Sydney, NSW",
    "max_results": 100,
    "run_count": 0,
    "last_run_at": null,
    "is_archived": false,
    "created_at": "2026-04-17T04:00:00Z",
    "updated_at": "2026-04-17T04:00:00Z"
  },
  "meta": { "url": "https://app.trustpager.com/growth/lead-gen" }
}`,
    },
    {
      method: 'GET',
      path: '/lead-gen/saved-searches/:saved_search_id',
      toolName: 'lead_gen_get_saved_search',
      description: 'Fetch a saved lead-gen search by UUID.',
      scopes: ['lead-gen:read'],
      isWrite: false,
      params: [
        { name: 'saved_search_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/lead-gen/saved-searches/:saved_search_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/lead-gen/saved-searches/:saved_search_id',
      toolName: 'lead_gen_update_saved_search',
      description: 'Update a saved lead-gen search.',
      scopes: ['lead-gen:write'],
      isWrite: true,
      params: [
        { name: 'saved_search_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/lead-gen/saved-searches/:saved_search_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/lead-gen/saved-searches/:saved_search_id',
      toolName: 'lead_gen_delete_saved_search',
      description: 'Archive a saved lead-gen search.',
      scopes: ['lead-gen:delete'],
      isWrite: true,
      params: [
        { name: 'saved_search_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/lead-gen/saved-searches/:saved_search_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
