// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/lead-gen-initiatives.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/lead-gen-initiatives.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const LEAD_GEN_INITIATIVES: ResourceGroup = {
  id: 'lead-gen-initiatives',
  label: 'LEAD_GEN_INITIATIVES',
  description: 'lead-gen-initiatives endpoints.',
  endpoints: [
    {
      method: 'POST',
      path: '/lead-gen/results',
      toolName: 'lead_gen_create_result',
      description: 'Manually insert a lead_gen_result (hand-curated lead, CSV import, smoke fixture).',
      scopes: ['lead-gen:write'],
      isWrite: true,
      params: [
        { name: 'business_name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'email', type: 'string', required: false, description: '', in: 'body' },
        { name: 'phone', type: 'string', required: false, description: '', in: 'body' },
        { name: 'website', type: 'string', required: false, description: '', in: 'body' },
        { name: 'city', type: 'string', required: false, description: '', in: 'body' },
        { name: 'state', type: 'string', required: false, description: '', in: 'body' },
        { name: 'country_code', type: 'string', required: false, description: '', in: 'body' },
        { name: 'search_id', type: 'string', required: false, description: 'Optional — if omitted a wrapper search is created', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/lead-gen/results" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"business_name":"...","email":"...","phone":"..."}'`,
    },
    {
      method: 'POST',
      path: '/lead-gen/initiatives',
      toolName: 'lead_gen_create_initiative',
      description: 'Create an outreach initiative (multi-step sequence) for lead-gen leads. Send-cadence fields are optional — sensible defaults apply (40 emails/day, 09:00-17:00 Mon-Fri Sydney, 90s minimum gap). Override only if the user needs a specific pace.',
      scopes: ['lead-gen:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'description', type: 'string', required: false, description: '', in: 'body' },
        { name: 'is_active', type: 'boolean', required: false, description: 'Active initiatives run their dispatcher; paused initiatives queue no new sends. Default true.', in: 'body' },
        { name: 'daily_send_cap', type: 'integer', required: false, description: 'Max email-channel sends per calendar day in the initiative timezone. Default 40. Personal email accounts typically get flagged above ~50/day for cold outreach.', in: 'body' },
        { name: 'send_window_start', type: 'string', required: false, description: '24-hour HH:MM start of the daily send window in send_window_timezone. Default "09:00".', in: 'body' },
        { name: 'send_window_end', type: 'string', required: false, description: '24-hour HH:MM end of the daily send window in send_window_timezone. Default "17:00".', in: 'body' },
        { name: 'send_window_timezone', type: 'string', required: false, description: 'IANA timezone for the send window (e.g. "Australia/Sydney"). Default "Australia/Sydney".', in: 'body' },
        { name: 'send_window_days', type: 'array', required: false, description: 'ISO weekdays the initiative is allowed to send on (1=Mon … 7=Sun). Default [1,2,3,4,5] (weekdays).', in: 'body' },
        { name: 'min_gap_seconds', type: 'integer', required: false, description: 'Minimum seconds between consecutive successful sends on this initiative. Default 90 — spreads 40 sends across ~60 minutes minimum.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/lead-gen/initiatives" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","description":"...","is_active":"..."}'`,
    },
    {
      method: 'GET',
      path: '/lead-gen/initiatives',
      toolName: 'lead_gen_list_initiatives',
      description: 'List outreach initiatives in this workspace.',
      scopes: ['lead-gen:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/lead-gen/initiatives" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/lead-gen/initiatives/dispatcher/run',
      toolName: 'lead_gen_run_initiative_dispatcher',
      description: 'Run the initiative dispatcher synchronously for this workspace. Fires any pending step tasks whose scheduled_for has passed. Same code path as the cron tick.',
      scopes: ['lead-gen:write'],
      isWrite: true,
      params: [
        { name: 'max_tasks', type: 'number', required: false, description: 'Cap on how many tasks to claim+run (default 10, max 50)', in: 'body' },
        { name: 'only_enrollment_id', type: 'string', required: false, description: 'Restrict to a specific enrolment (smoke testing)', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/lead-gen/initiatives/dispatcher/run" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"max_tasks":"...","only_enrollment_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/lead-gen/initiatives/:initiative_id',
      toolName: 'lead_gen_get_initiative',
      description: 'Get an initiative with its steps and underlying automations.',
      scopes: ['lead-gen:read'],
      isWrite: false,
      params: [
        { name: 'initiative_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/lead-gen/initiatives/:initiative_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/lead-gen/initiatives/:initiative_id',
      toolName: 'lead_gen_update_initiative',
      description: 'Update an initiative — name, description, active state, or send-cadence (daily cap, send window, days, min-gap). Only present fields are written.',
      scopes: ['lead-gen:write'],
      isWrite: true,
      params: [
        { name: 'initiative_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'description', type: 'string,null', required: false, description: '', in: 'body' },
        { name: 'is_active', type: 'boolean', required: false, description: '', in: 'body' },
        { name: 'daily_send_cap', type: 'integer', required: false, description: 'Max email-channel sends per calendar day. Personal email accounts typically get flagged above ~50/day.', in: 'body' },
        { name: 'send_window_start', type: 'string', required: false, description: '24-hour HH:MM (e.g. "09:00").', in: 'body' },
        { name: 'send_window_end', type: 'string', required: false, description: '24-hour HH:MM (e.g. "17:00").', in: 'body' },
        { name: 'send_window_timezone', type: 'string', required: false, description: 'IANA timezone (e.g. "Australia/Sydney").', in: 'body' },
        { name: 'send_window_days', type: 'array', required: false, description: 'ISO weekdays (1=Mon … 7=Sun).', in: 'body' },
        { name: 'min_gap_seconds', type: 'integer', required: false, description: 'Minimum seconds between consecutive successful sends.', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/lead-gen/initiatives/:initiative_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","description":"...","is_active":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/lead-gen/initiatives/:initiative_id',
      toolName: 'lead_gen_delete_initiative',
      description: 'Delete an initiative and all its steps + underlying automations.',
      scopes: ['lead-gen:delete'],
      isWrite: true,
      params: [
        { name: 'initiative_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/lead-gen/initiatives/:initiative_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/lead-gen/initiatives/:initiative_id/steps',
      toolName: 'lead_gen_add_initiative_step',
      description: 'Add a step to an initiative. Quick mode: pass action_type + action_config + delay. Bring-your-own mode: pass automation_id.',
      scopes: ['lead-gen:write'],
      isWrite: true,
      params: [
        { name: 'initiative_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'action_type', type: 'string', required: false, description: 'send_gmail_email | send_sms | notify_assigned_staff', in: 'body' },
        { name: 'action_config', type: 'object', required: false, description: 'Config matching the chosen action type (subject/body/etc.)', in: 'body' },
        { name: 'automation_id', type: 'string', required: false, description: 'Alternative to action_type+config — reuse an existing automation', in: 'body' },
        { name: 'delay_days', type: 'number', required: false, description: '', in: 'body' },
        { name: 'delay_hours', type: 'number', required: false, description: '', in: 'body' },
        { name: 'delay_minutes', type: 'number', required: false, description: '', in: 'body' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/lead-gen/initiatives/:initiative_id/steps" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"action_type":"...","action_config":"...","automation_id":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/lead-gen/initiatives/:initiative_id/steps/:step_id',
      toolName: 'lead_gen_update_initiative_step',
      description: 'Update an initiative step (delay, ordering, is_active).',
      scopes: ['lead-gen:write'],
      isWrite: true,
      params: [
        { name: 'initiative_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'step_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/lead-gen/initiatives/:initiative_id/steps/:step_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/lead-gen/initiatives/:initiative_id/steps/:step_id',
      toolName: 'lead_gen_delete_initiative_step',
      description: 'Delete a step from an initiative and its underlying automation.',
      scopes: ['lead-gen:delete'],
      isWrite: true,
      params: [
        { name: 'initiative_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'step_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/lead-gen/initiatives/:initiative_id/steps/:step_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/lead-gen/initiatives/:initiative_id/enrol',
      toolName: 'lead_gen_enrol_in_initiative',
      description: 'Enrol one or more lead_gen_results into an initiative. Schedules the first step task and tracks the rest as the dispatcher advances each enrolment.',
      scopes: ['lead-gen:write'],
      isWrite: true,
      params: [
        { name: 'initiative_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'lead_gen_result_ids', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/lead-gen/initiatives/:initiative_id/enrol" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"lead_gen_result_ids":"..."}'`,
    },
    {
      method: 'GET',
      path: '/lead-gen/initiatives/:initiative_id/enrolments',
      toolName: 'lead_gen_list_initiative_enrolments',
      description: 'List enrolments for an initiative with their joined lead-gen result snapshots.',
      scopes: ['lead-gen:read'],
      isWrite: false,
      params: [
        { name: 'initiative_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/lead-gen/initiatives/:initiative_id/enrolments" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
