// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/memory.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/memory.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const MEMORY: ResourceGroup = {
  id: 'memory',
  label: 'Agent Memory',
  description: 'Cross-run persistent state for managed agents. Each row records what an agent learned, decided, or intends to revisit about a subject. Supports semantic search via vector embeddings. Required scopes: memory:read (GET/search), memory:write (POST/PATCH/DELETE).',
  endpoints: [
    {
      method: 'POST',
      path: '/memory/search',
      toolName: 'search_memory',
      description: 'Semantic search over agent memories. Pass a natural-language query; returns the top-K most similar memories ranked by cosine similarity. Use when you need fuzzy / topic-based lookup ("have I discussed pricing with this contact?") rather than exact filter by subject_id. Use list_memory for keyed lookup ("what have I said to contact X about kind Y?").',
      scopes: ['memory:read'],
      isWrite: false,
      params: [
        { name: 'query', type: 'string', required: true, description: 'Natural language query.', in: 'body' },
        { name: 'subject_type', type: 'string', required: false, description: '', in: 'body' },
        { name: 'subject_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'kind', type: 'string', required: false, description: '', in: 'body' },
        { name: 'agent_registry_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'visibility', type: 'string', required: false, description: '', in: 'body' },
        { name: 'limit', type: 'number', required: false, description: 'Default 10, max 50.', in: 'body' },
        { name: 'threshold', type: 'number', required: false, description: 'Cosine similarity floor (0.0–1.0). Default 0.3.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/memory/search" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"query":"...","subject_type":"...","subject_id":"..."}'`,
      notes: [
        'Returns {results: [...], count: N}. Each result includes all standard memory fields plus a similarity score.',
        'Embeddings use Voyage-3 (1024 dimensions). Voyage-3 cosine scores are lower-magnitude than OpenAI -- raise threshold to 0.3+ for stricter matching.',
        'Returns an error (not empty results) if the embedding service is unavailable.',
      ],
    },
    {
      method: 'POST',
      path: '/memory/purge',
      toolName: 'purge_memory',
      description: 'Bulk-retract agent memories matching a filter, in one call. Soft-deletes by default (reversible, audit-preserving); pass hard:true to physically remove rows for PII / right-to-be-forgotten. This is the "forget everything about this contact / opportunity / company" primitive — filter by subject, agent, kind, tag, or linked entity. Refuses to run with no filter unless you set all:true. Requires the memory:delete scope.',
      scopes: ['memory:delete'],
      isWrite: true,
      params: [
        { name: 'subject_type', type: 'string', required: false, description: 'Purge memories about this subject type — e.g. "contact", "opportunity", "company", "self".', in: 'body' },
        { name: 'subject_id', type: 'string', required: false, description: 'Purge memories about this specific subject id (use with subject_type for "forget this contact").', in: 'body' },
        { name: 'agent_registry_id', type: 'string', required: false, description: 'Purge memories owned by this agent.', in: 'body' },
        { name: 'kind', type: 'string', required: false, description: 'Purge memories of this kind.', in: 'body' },
        { name: 'tag', type: 'string', required: false, description: 'Purge memories carrying this tag.', in: 'body' },
        { name: 'linked_entity_type', type: 'string', required: false, description: 'Purge memories linked to an entity of this type (combine with linked_entity_id).', in: 'body' },
        { name: 'linked_entity_id', type: 'string', required: false, description: 'Purge memories linked to this entity id (combine with linked_entity_type).', in: 'body' },
        { name: 'hard', type: 'boolean', required: false, description: 'Default false (soft-delete). true physically removes the rows — irreversible.', in: 'body' },
        { name: 'all', type: 'boolean', required: false, description: 'Set true to purge EVERY memory in the workspace. Required when no filter is provided; ignored otherwise.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/memory/purge" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"subject_type":"...","subject_id":"...","agent_registry_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/memory',
      toolName: 'list_memory',
      description: 'List agent memories for this workspace, filterable by subject, kind, agent, tag, linked entity, and time. Cursor-paginated. Use this for keyed lookup before composing new actions (e.g. "what have I already said to this contact?"); use search_memory for fuzzy / semantic lookup.',
      scopes: ['memory:read'],
      isWrite: false,
      params: [
        { name: 'subject_type', type: 'string', required: false, description: 'Filter by subject type — e.g. "contact", "opportunity", "company", "self".', in: 'query' },
        { name: 'subject_id', type: 'string', required: false, description: 'Filter by subject id (use with subject_type).', in: 'query' },
        { name: 'kind', type: 'string', required: false, description: 'Filter by kind — e.g. "pitch", "objection", "preference", "next_steps".', in: 'query' },
        { name: 'agent_registry_id', type: 'string', required: false, description: 'Filter by owning agent.', in: 'query' },
        { name: 'visibility', type: 'string', required: false, description: 'Filter by visibility.', in: 'query' },
        { name: 'tag', type: 'array', required: false, description: 'Tag filter (matches any of the provided tags). Pass as repeated `tag` query params or array.', in: 'query' },
        { name: 'linked_entity_type', type: 'string', required: false, description: 'Find memories linked to an entity of this type.', in: 'query' },
        { name: 'linked_entity_id', type: 'string', required: false, description: 'Find memories linked to this entity id (must be combined with linked_entity_type).', in: 'query' },
        { name: 'since', type: 'string', required: false, description: 'ISO timestamp — return memories created after this time.', in: 'query' },
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
        { name: 'after', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/memory" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/memory',
      toolName: 'write_memory',
      description: 'Write a memory for an agent. If `key` is provided, behaves as upsert on (agent, subject, kind, key) — re-running the same key UPDATES the existing memory rather than creating a duplicate. Use this to record what you have learned, decided, or intend to revisit. Content is natural-language; metadata is structured. Embedding generated automatically for semantic search.',
      scopes: ['memory:write'],
      isWrite: true,
      params: [
        { name: 'agent_registry_id', type: 'string', required: false, description: 'The owning agent id. For agent-private state.', in: 'body' },
        { name: 'visibility', type: 'string', required: false, description: 'Default "private". Set "shared" to make this memory readable by other agents in the workspace.', in: 'body' },
        { name: 'subject_type', type: 'string', required: true, description: 'What this memory is about — e.g. "contact", "opportunity", "company", "self".', in: 'body' },
        { name: 'subject_id', type: 'string', required: false, description: 'The id of the subject (the contact uuid, opportunity uuid, etc.). Null for global/self memories.', in: 'body' },
        { name: 'kind', type: 'string', required: true, description: 'The category of memory — e.g. "pitch", "objection", "preference", "observation", "next_steps". Free-form; agents define their own taxonomy.', in: 'body' },
        { name: 'key', type: 'string', required: false, description: 'Optional unique key within (agent, subject, kind) — enables upsert. Example: an article_slug for a pitch memory means re-pitching the same slug UPDATES rather than duplicates.', in: 'body' },
        { name: 'content', type: 'string', required: true, description: 'The memory itself, in natural language.', in: 'body' },
        { name: 'metadata', type: 'object', required: false, description: 'Structured payload alongside the content.', in: 'body' },
        { name: 'linked_entities', type: 'array', required: false, description: 'Other entities this memory references. e.g. [{type:"opportunity", id:"..."}, {type:"article", id:"voice-agents-setup"}].', in: 'body' },
        { name: 'tags', type: 'array', required: false, description: 'Free-form semantic facets. e.g. ["competitor:Twilio", "objection:pricing", "feature:voice_agents"].', in: 'body' },
        { name: 'confidence', type: 'number', required: false, description: '0.0–1.0. Default 1.0. Decreases as the memory ages or gets contradicted.', in: 'body' },
        { name: 'source_kind', type: 'string', required: false, description: 'Where this memory came from — e.g. "email_send", "transcript", "tool_observation", "manual".', in: 'body' },
        { name: 'source_id', type: 'string', required: false, description: 'Pointer back to the source event (e.g. email_logs.id).', in: 'body' },
        { name: 'parent_memory_id', type: 'string', required: false, description: 'Link to an earlier memory this one updates or continues.', in: 'body' },
        { name: 'expires_at', type: 'string', required: false, description: 'ISO timestamp. Memory becomes inactive after this time.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/memory" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"agent_registry_id":"...","visibility":"...","subject_type":"..."}'`,
      notes: [
        'Returns HTTP 201 on insert, HTTP 200 on upsert (when key matched an existing row).',
        'embedding_status in the response is "attached" (semantic search ready) or "pending" (embedding deferred).',
        'A soft-deleted row with the same key is automatically revived (deleted_at cleared).',
      ],
    },
    {
      method: 'GET',
      path: '/memory/:memory_id',
      toolName: 'get_memory',
      description: 'Fetch a single agent memory by its uuid.',
      scopes: ['memory:read'],
      isWrite: false,
      params: [
        { name: 'memory_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/memory/:memory_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/memory/:memory_id',
      toolName: 'update_memory',
      description: 'Update a memory in place — change content, metadata, tags, links, confidence, expiry, or visibility. Re-embeds automatically if content changes. For upsert semantics, prefer write_memory with the same key.',
      scopes: ['memory:write'],
      isWrite: true,
      params: [
        { name: 'memory_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'content', type: 'string', required: false, description: '', in: 'body' },
        { name: 'metadata', type: 'object', required: false, description: '', in: 'body' },
        { name: 'linked_entities', type: 'array', required: false, description: '', in: 'body' },
        { name: 'tags', type: 'array', required: false, description: '', in: 'body' },
        { name: 'confidence', type: 'number', required: false, description: '', in: 'body' },
        { name: 'expires_at', type: 'string', required: false, description: '', in: 'body' },
        { name: 'visibility', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/memory/:memory_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"content":"...","metadata":"...","linked_entities":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/memory/:memory_id',
      toolName: 'delete_memory',
      description: 'Soft-delete a memory. Sets deleted_at; the row is preserved for audit but no longer surfaces in list / search / get calls. Reversible only by admin SQL.',
      scopes: ['memory:write'],
      isWrite: true,
      params: [
        { name: 'memory_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/memory/:memory_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
