// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/notepads.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/notepads.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const NOTEPADS: ResourceGroup = {
  id: 'notepads',
  label: 'Notepads',
  description: 'Manage rich-text notepads organized in folders. Supports markdown input, iterative editing (append/prepend/section patches), per-record visibility, and ACL-based access control for restricted notes.',
  endpoints: [
    {
      method: 'GET',
      path: '/notepads/folders',
      toolName: 'list_notepad_folders',
      description: 'List notepad folders in the workspace.',
      scopes: ['notepads:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/notepads/folders" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/notepads/folders',
      toolName: 'create_notepad_folder',
      description: 'Create a new notepad folder. Set is_public=true to mark it a public content collection that can be integrated as a section on a website (the public notepads inside it then appear there).',
      scopes: ['notepads:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'is_public', type: 'boolean', required: false, description: 'Mark the folder as a public content collection (integratable on websites).', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/notepads/folders" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"..."}'`,
    },
    {
      method: 'GET',
      path: '/notepads/folders/:folder_id',
      toolName: 'get_notepad_folder',
      description: 'Fetch a notepad folder by UUID.',
      scopes: ['notepads:read'],
      isWrite: false,
      params: [
        { name: 'folder_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/notepads/folders/:folder_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/notepads/folders/:folder_id',
      toolName: 'update_notepad_folder',
      description: 'Rename or update a notepad folder. Set is_public to mark it (true) or unmark it (false) as a public content collection integratable on websites.',
      scopes: ['notepads:write'],
      isWrite: true,
      params: [
        { name: 'folder_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'is_public', type: 'boolean', required: false, description: 'Public content collection flag.', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/notepads/folders/:folder_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/notepads/folders/:folder_id',
      toolName: 'delete_notepad_folder',
      description: 'Delete a notepad folder by UUID.',
      scopes: ['notepads:delete'],
      isWrite: true,
      params: [
        { name: 'folder_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/notepads/folders/:folder_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/notepads/folders/:folder_id/acl',
      toolName: 'list_notepad_folder_acl',
      description: 'List access-control entries on a notepad folder.',
      scopes: ['notepads:read'],
      isWrite: false,
      params: [
        { name: 'folder_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/notepads/folders/:folder_id/acl" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/notepads/folders/:folder_id/acl',
      toolName: 'add_notepad_folder_acl_entry',
      description: 'Grant access to a notepad folder (user or role principal).',
      scopes: ['notepads:write'],
      isWrite: true,
      params: [
        { name: 'folder_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'principal_type', type: 'string', required: true, description: '', in: 'body' },
        { name: 'principal_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'permission', type: 'string', required: false, description: 'read or write', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/notepads/folders/:folder_id/acl" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"principal_type":"...","principal_id":"...","permission":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/notepads/acl/:acl_id',
      toolName: 'remove_notepad_acl_entry',
      description: 'Revoke a notepad ACL entry by UUID.',
      scopes: ['notepads:write'],
      isWrite: true,
      params: [
        { name: 'acl_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/notepads/acl/:acl_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/notepads',
      toolName: 'list_notepads',
      description: 'List notepads in the workspace. Filter by folder_id, is_public, or free-text search.',
      scopes: ['notepads:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
        { name: 'q', type: 'string', required: false, description: '', in: 'query' },
        { name: 'folder_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'is_public', type: 'boolean', required: false, description: 'Filter to public (blog-published) notepads only.', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/notepads" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/notepads',
      toolName: 'create_notepad',
      description: 'Create a new notepad. Supports markdown content. Set is_public=true to publish it to the public blog (a slug is derived from the title); notepads are private by default.',
      scopes: ['notepads:write'],
      isWrite: true,
      params: [
        { name: 'title', type: 'string', required: true, description: '', in: 'body' },
        { name: 'content', type: 'string', required: false, description: '', in: 'body' },
        { name: 'folder_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'is_public', type: 'boolean', required: false, description: 'Publish to the public blog. Private by default. The post only appears publicly when it is also in a website\'s designated blog folder.', in: 'body' },
        { name: 'slug', type: 'string', required: false, description: 'Optional public URL slug. Derived from the title when omitted.', in: 'body' },
        { name: 'cover_image', type: 'string', required: false, description: 'Cover image URL — shown on the Notepads card grid and at the top of the public blog post.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/notepads" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"title":"...","content":"...","folder_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/notepads/:notepad_id',
      toolName: 'get_notepad',
      description: 'Fetch a notepad by UUID, including its full content.',
      scopes: ['notepads:read'],
      isWrite: false,
      params: [
        { name: 'notepad_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/notepads/:notepad_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/notepads/:notepad_id',
      toolName: 'update_notepad',
      description: 'Update the title and/or content of a notepad. Set is_public=true to publish it to the public blog, or false to unpublish; a slug is derived from the title on first publish.',
      scopes: ['notepads:write'],
      isWrite: true,
      params: [
        { name: 'notepad_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'title', type: 'string', required: false, description: '', in: 'body' },
        { name: 'content', type: 'string', required: false, description: '', in: 'body' },
        { name: 'is_public', type: 'boolean', required: false, description: 'Publish (true) or unpublish (false) to the public blog.', in: 'body' },
        { name: 'slug', type: 'string', required: false, description: 'Optional public URL slug. Derived from the title when omitted.', in: 'body' },
        { name: 'cover_image', type: 'string', required: false, description: 'Cover image URL (shown on the card grid + public post). Pass null to clear.', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/notepads/:notepad_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"title":"...","content":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/notepads/:notepad_id',
      toolName: 'delete_notepad',
      description: 'Delete a notepad by UUID. Destructive.',
      scopes: ['notepads:delete'],
      isWrite: true,
      params: [
        { name: 'notepad_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/notepads/:notepad_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/notepads/:notepad_id/deals',
      toolName: 'list_notepad_deals',
      description: 'List opportunities/deals linked to a notepad.',
      scopes: ['notepads:read'],
      isWrite: false,
      params: [
        { name: 'notepad_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/notepads/:notepad_id/deals" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/notepads/:notepad_id/deals',
      toolName: 'link_notepad_to_deal',
      description: 'Link a notepad to an opportunity.',
      scopes: ['notepads:write'],
      isWrite: true,
      params: [
        { name: 'notepad_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'deal_id', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/notepads/:notepad_id/deals" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"deal_id":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/notepads/:notepad_id/deals/:deal_id',
      toolName: 'unlink_notepad_from_deal',
      description: 'Unlink a notepad from an opportunity.',
      scopes: ['notepads:write'],
      isWrite: true,
      params: [
        { name: 'notepad_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'deal_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/notepads/:notepad_id/deals/:deal_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/notepads/:notepad_id/acl',
      toolName: 'list_notepad_acl',
      description: 'List access-control entries on a notepad.',
      scopes: ['notepads:read'],
      isWrite: false,
      params: [
        { name: 'notepad_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/notepads/:notepad_id/acl" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/notepads/:notepad_id/acl',
      toolName: 'add_notepad_acl_entry',
      description: 'Grant access to a notepad (user or role principal).',
      scopes: ['notepads:write'],
      isWrite: true,
      params: [
        { name: 'notepad_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'principal_type', type: 'string', required: true, description: '', in: 'body' },
        { name: 'principal_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'permission', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/notepads/:notepad_id/acl" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"principal_type":"...","principal_id":"...","permission":"..."}'`,
    },
  ],
};
