// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/phone.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/phone.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const PHONE: ResourceGroup = {
  id: 'phone',
  label: 'Phone',
  description: 'Manage phone numbers and call logs. Search for available numbers to purchase.',
  endpoints: [
    {
      method: 'POST',
      path: '/phone/numbers/search',
      toolName: 'search_phone_numbers',
      description: 'Search for available phone numbers to purchase.',
      scopes: ['phone:read'],
      isWrite: false,
      params: [
        { name: 'country_code', type: 'string', required: false, description: '', in: 'body' },
        { name: 'area_code', type: 'string', required: false, description: '', in: 'body' },
        { name: 'contains', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/phone/numbers/search" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"country_code":"...","area_code":"...","contains":"..."}'`,
    },
    {
      method: 'POST',
      path: '/phone/numbers/buy',
      toolName: 'buy_phone_number',
      description: 'Buy a phone number. Costs credits and recurring fees.',
      scopes: ['phone:write'],
      isWrite: true,
      params: [
        { name: 'phone_number', type: 'string', required: true, description: '', in: 'body' },
        { name: 'friendly_name', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/phone/numbers/buy" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"phone_number":"...","friendly_name":"..."}'`,
    },
    {
      method: 'GET',
      path: '/phone/numbers',
      toolName: 'list_phone_numbers',
      description: 'List workspace phone numbers.',
      scopes: ['phone:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/phone/numbers" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/phone/numbers/:phone_number_id',
      toolName: 'get_phone_number',
      description: 'Fetch a phone number by UUID.',
      scopes: ['phone:read'],
      isWrite: false,
      params: [
        { name: 'phone_number_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/phone/numbers/:phone_number_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/phone/numbers/:phone_number_id',
      toolName: 'update_phone_number',
      description: 'Update a phone number: friendly_name and voice-agent routing. IMPORTANT: binding an agent here (inbound_voice_agent_id / outbound_voice_agent_id) controls INBOUND answering (who picks up calls TO this number) and is one-agent-per-number. OUTBOUND dialling does NOT use this binding; set the caller-ID number on the agent via create_voice_agent_outbound_config (default_phone_number_id), which lets one number serve many agents.',
      scopes: ['phone:write'],
      isWrite: true,
      params: [
        { name: 'phone_number_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'friendly_name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'inbound_voice_agent_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'outbound_voice_agent_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/phone/numbers/:phone_number_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"friendly_name":"...","inbound_voice_agent_id":"...","outbound_voice_agent_id":"..."}'`,
    },
    {
      method: 'POST',
      path: '/phone/numbers/:phone_number_id/release',
      toolName: 'release_phone_number',
      description: 'Release a phone number (stops billing).',
      scopes: ['phone:write'],
      isWrite: true,
      params: [
        { name: 'phone_number_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/phone/numbers/:phone_number_id/release" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/phone/addresses',
      toolName: 'list_phone_addresses',
      description: 'List regulatory addresses on file with the phone provider.',
      scopes: ['phone:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/phone/addresses" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/phone/addresses',
      toolName: 'create_phone_address',
      description: 'Create a regulatory address.',
      scopes: ['phone:write'],
      isWrite: true,
      params: [
        { name: 'customer_name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'street', type: 'string', required: true, description: '', in: 'body' },
        { name: 'city', type: 'string', required: true, description: '', in: 'body' },
        { name: 'region', type: 'string', required: true, description: '', in: 'body' },
        { name: 'postal_code', type: 'string', required: true, description: '', in: 'body' },
        { name: 'iso_country', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/phone/addresses" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"customer_name":"...","street":"...","city":"..."}'`,
    },
    {
      method: 'GET',
      path: '/phone/bundles',
      toolName: 'list_phone_bundles',
      description: 'List regulatory bundles for phone-number compliance.',
      scopes: ['phone:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/phone/bundles" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/phone/bundles',
      toolName: 'create_phone_bundle',
      description: 'Create a regulatory bundle.',
      scopes: ['phone:write'],
      isWrite: true,
      params: [
        { name: 'country_code', type: 'string', required: true, description: '', in: 'body' },
        { name: 'number_type', type: 'string', required: true, description: '', in: 'body' },
        { name: 'end_user_type', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/phone/bundles" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"country_code":"...","number_type":"...","end_user_type":"..."}'`,
    },
    {
      method: 'GET',
      path: '/phone/bundles/:bundle_id',
      toolName: 'get_phone_bundle',
      description: 'Fetch a regulatory bundle by UUID.',
      scopes: ['phone:read'],
      isWrite: false,
      params: [
        { name: 'bundle_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/phone/bundles/:bundle_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/phone/bundles/:bundle_id/submit',
      toolName: 'submit_phone_bundle',
      description: 'Submit a regulatory bundle for review.',
      scopes: ['phone:write'],
      isWrite: true,
      params: [
        { name: 'bundle_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/phone/bundles/:bundle_id/submit" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/phone/call-logs',
      toolName: 'list_phone_call_logs',
      description: 'List phone-call records (inbound + outbound). USE THIS for any "recent calls", "phone call history", "missed calls", "who called", or similar phone-specific query. Returns the raw call log (timestamps, duration, direction, phone number, recording url, voice-agent linkage) — richer than list_activities for calls. Prefer this over list_activities when the user asks specifically about phone activity.',
      scopes: ['calls:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
        { name: 'direction', type: 'string', required: false, description: 'inbound or outbound', in: 'query' },
        { name: 'contact_id', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/phone/call-logs" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
