// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/pipelines.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/pipelines.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const PIPELINES: ResourceGroup = {
  id: 'pipelines',
  label: 'Pipelines',
  description: 'Manage sales pipelines and their stages. Opportunities move through pipeline stages to track progress.',
  endpoints: [
    {
      method: 'GET',
      path: '/pipelines',
      toolName: 'list_pipelines',
      description: 'List all pipelines in the workspace. Each pipeline represents a workflow (e.g. "Sales", "Onboarding", "Support Tickets"). Use this when you need a pipeline UUID for creating or moving an opportunity.',
      scopes: ['pipelines:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/pipelines" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/pipelines',
      toolName: 'create_pipeline',
      description: 'Create a new pipeline in the workspace. Requires a name; optional fields include description, is_active, is_default, position, sop_url, learning_hub_canvas_id, connected_pipeline_ids, exclude_from_lead_reporting.',
      scopes: ['pipelines:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: 'Pipeline name (e.g. "Sales", "Onboarding")', in: 'body' },
        { name: 'description', type: 'string', required: false, description: 'Optional plain-text description of what this pipeline tracks', in: 'body' },
        { name: 'is_active', type: 'boolean', required: false, description: 'Whether the pipeline is currently active (default true)', in: 'body' },
        { name: 'is_default', type: 'boolean', required: false, description: 'Make this the workspace default pipeline', in: 'body' },
        { name: 'position', type: 'number', required: false, description: 'Display order across all pipelines', in: 'body' },
        { name: 'learning_hub_canvas_id', type: 'string', required: false, description: 'Optional UUID of a Learning Hub training canvas to attach as this pipeline\'s training resource. Mutually exclusive with sop_url. When set, the "View Training" button opens the canvas in-app rather than an external URL.', in: 'body' },
        { name: 'exclude_from_lead_reporting', type: 'boolean', required: false, description: 'When true, opportunities in this pipeline are excluded from the Lead Sources leaderboard (totals, per-source cards, conversion rate). Defaults to false. Use for non-lead pipelines like supplier or referral-partner networks stored as opportunities.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/pipelines" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","description":"...","is_active":"..."}'`,
    },
    {
      method: 'GET',
      path: '/pipelines/:pipeline_id',
      toolName: 'get_pipeline',
      description: 'Fetch a single pipeline by UUID. Returns the pipeline record (does not include stages — use list_pipeline_stages for that).',
      scopes: ['pipelines:read'],
      isWrite: false,
      params: [
        { name: 'pipeline_id', type: 'string', required: true, description: 'UUID of the pipeline', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/pipelines/:pipeline_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/pipelines/:pipeline_id',
      toolName: 'update_pipeline',
      description: 'Update a pipeline by UUID. Pass only the fields you want to change. Writable: name, description, is_active, is_default, position, sop_url, learning_hub_canvas_id, connected_pipeline_ids, exclude_from_lead_reporting.',
      scopes: ['pipelines:write'],
      isWrite: true,
      params: [
        { name: 'pipeline_id', type: 'string', required: true, description: 'UUID of the pipeline to update', in: 'path' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'description', type: 'string', required: false, description: '', in: 'body' },
        { name: 'is_active', type: 'boolean', required: false, description: '', in: 'body' },
        { name: 'is_default', type: 'boolean', required: false, description: '', in: 'body' },
        { name: 'position', type: 'number', required: false, description: '', in: 'body' },
        { name: 'learning_hub_canvas_id', type: 'string', required: false, description: 'UUID of a Learning Hub training canvas to link as this pipeline\'s training resource, or null to clear. Mutually exclusive with sop_url.', in: 'body' },
        { name: 'exclude_from_lead_reporting', type: 'boolean', required: false, description: 'When true, opportunities in this pipeline are excluded from the Lead Sources leaderboard (totals, per-source cards, conversion rate). Use for non-lead pipelines like supplier or referral-partner networks stored as opportunities.', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/pipelines/:pipeline_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","description":"...","is_active":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/pipelines/:pipeline_id',
      toolName: 'delete_pipeline',
      description: 'Delete a pipeline by UUID. Destructive — pipeline cannot be deleted if it has opportunities placed in any of its stages.',
      scopes: ['pipelines:delete'],
      isWrite: true,
      params: [
        { name: 'pipeline_id', type: 'string', required: true, description: 'UUID of the pipeline to delete', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/pipelines/:pipeline_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/pipelines/:pipeline_id/stages',
      toolName: 'list_pipeline_stages',
      description: 'List all stages of a pipeline in display order. Each stage includes a deal_count. Use this to find a stage UUID for create_opportunity or move_opportunity.',
      scopes: ['pipelines:read'],
      isWrite: false,
      params: [
        { name: 'pipeline_id', type: 'string', required: true, description: 'UUID of the pipeline', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/pipelines/:pipeline_id/stages" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/pipelines/:pipeline_id/stages',
      toolName: 'create_pipeline_stage',
      description: 'Add a new stage to a pipeline. Requires a name. Optional: position (defaults to end), color (hex), is_won_stage, is_lost_stage.',
      scopes: ['pipelines:write'],
      isWrite: true,
      params: [
        { name: 'pipeline_id', type: 'string', required: true, description: 'UUID of the parent pipeline', in: 'path' },
        { name: 'name', type: 'string', required: true, description: 'Stage name', in: 'body' },
        { name: 'position', type: 'number', required: false, description: 'Display order within the pipeline (0-based)', in: 'body' },
        { name: 'color', type: 'string', required: false, description: 'Hex colour code for the stage chip', in: 'body' },
        { name: 'is_won_stage', type: 'boolean', required: false, description: 'Mark this stage as a "won" terminal stage', in: 'body' },
        { name: 'is_lost_stage', type: 'boolean', required: false, description: 'Mark this stage as a "lost" terminal stage', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/pipelines/:pipeline_id/stages" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","position":"...","color":"..."}'`,
    },
    {
      method: 'POST',
      path: '/pipelines/:pipeline_id/stages/reorder',
      toolName: 'reorder_pipeline_stages',
      description: 'Reorder the stages of a pipeline. Pass an array of stage UUIDs in the desired new order — position numbers are reassigned in array order.',
      scopes: ['pipelines:write'],
      isWrite: true,
      params: [
        { name: 'pipeline_id', type: 'string', required: true, description: 'UUID of the pipeline', in: 'path' },
        { name: 'stage_ids', type: 'array', required: true, description: 'Stage UUIDs in their new display order', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/pipelines/:pipeline_id/stages/reorder" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"stage_ids":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/pipelines/:pipeline_id/stages/:stage_id',
      toolName: 'update_pipeline_stage',
      description: 'Update a single stage within a pipeline. Pass only the fields you want to change.',
      scopes: ['pipelines:write'],
      isWrite: true,
      params: [
        { name: 'pipeline_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'stage_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'position', type: 'number', required: false, description: '', in: 'body' },
        { name: 'color', type: 'string', required: false, description: '', in: 'body' },
        { name: 'is_won_stage', type: 'boolean', required: false, description: '', in: 'body' },
        { name: 'is_lost_stage', type: 'boolean', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/pipelines/:pipeline_id/stages/:stage_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","position":"...","color":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/pipelines/:pipeline_id/stages/:stage_id',
      toolName: 'delete_pipeline_stage',
      description: 'Delete a single stage from a pipeline. Destructive — fails if opportunities are placed in this stage.',
      scopes: ['pipelines:delete'],
      isWrite: true,
      params: [
        { name: 'pipeline_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'stage_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/pipelines/:pipeline_id/stages/:stage_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/pipelines/:pipeline_id/deals',
      toolName: 'list_pipeline_deals',
      description: 'List all opportunities (deals) placed in any stage of a pipeline. Returns opportunity records with their current stage placement.',
      scopes: ['pipelines:read', 'opportunities:read'],
      isWrite: false,
      params: [
        { name: 'pipeline_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'limit', type: 'number', required: false, description: 'Max rows (1-100, default 25)', in: 'query' },
        { name: 'after', type: 'string', required: false, description: 'Pagination cursor', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/pipelines/:pipeline_id/deals" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/pipelines/:pipeline_id/summary',
      toolName: 'get_pipeline_summary',
      description: 'Fetch summary statistics for a pipeline: deal counts and value totals per stage. Use this for "pipeline health" or "what is in stage X" questions.',
      scopes: ['pipelines:read'],
      isWrite: false,
      params: [
        { name: 'pipeline_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/pipelines/:pipeline_id/summary" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
