// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/portals.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/portals.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const PORTALS: ResourceGroup = {
  id: 'portals',
  label: 'PORTALS',
  description: 'portals endpoints.',
  endpoints: [
    {
      method: 'GET',
      path: '/portals',
      toolName: 'list_portals',
      description: 'List client/partner portals in the workspace.',
      scopes: ['portals:read'],
      isWrite: false,
      params: [
        { name: 'type', type: 'string', required: false, description: '', in: 'query' },
        { name: 'status', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/portals" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/portals',
      toolName: 'create_portal',
      description: 'Create a client/partner portal. A portal is the unit of access + switching: members see only records explicitly shared into it.',
      scopes: ['portals:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: 'Display name, e.g. "Harbourline — Partner Portal".', in: 'body' },
        { name: 'type', type: 'string', required: false, description: 'partner | client | doc_collection. Defaults to client.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/portals" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","type":"..."}'`,
    },
    {
      method: 'GET',
      path: '/portals/:portal_id',
      toolName: 'get_portal',
      description: 'Fetch a portal by UUID.',
      scopes: ['portals:read'],
      isWrite: false,
      params: [
        { name: 'portal_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/portals/:portal_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/portals/:portal_id',
      toolName: 'update_portal',
      description: 'Update a portal (name, type, status). Set status to disabled to suspend member access.',
      scopes: ['portals:write'],
      isWrite: true,
      params: [
        { name: 'portal_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'type', type: 'string', required: false, description: '', in: 'body' },
        { name: 'status', type: 'string', required: false, description: 'active | disabled', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/portals/:portal_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","type":"...","status":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/portals/:portal_id',
      toolName: 'delete_portal',
      description: 'Delete a portal. Cascades to its members and shares (the underlying shared records are NOT deleted).',
      scopes: ['portals:delete'],
      isWrite: true,
      params: [
        { name: 'portal_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/portals/:portal_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/portals/:portal_id/members',
      toolName: 'list_portal_members',
      description: 'List the members of a portal.',
      scopes: ['portals:read'],
      isWrite: false,
      params: [
        { name: 'portal_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/portals/:portal_id/members" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/portals/:portal_id/members',
      toolName: 'add_portal_member',
      description: 'Add a member to a portal by email. The member is a company-less external login (broker, client, site staff) — they never join the inviting company. Idempotent per email.',
      scopes: ['portals:write'],
      isWrite: true,
      params: [
        { name: 'portal_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'email', type: 'string', required: true, description: 'The member email. Required.', in: 'body' },
        { name: 'user_id', type: 'string', required: false, description: 'Optional existing user UUID to link immediately.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/portals/:portal_id/members" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"email":"...","user_id":"..."}'`,
    },
    {
      method: 'POST',
      path: '/portals/:portal_id/invite',
      toolName: 'invite_portal_member',
      description: 'Invite an external person to a portal by email. Creates a company-less login (broker / client / site staff), emails them an acceptance link, and records them as an active member. They NEVER join your company. Idempotent per email; if a login for that email already exists it is linked without a second invite.',
      scopes: ['portals:write'],
      isWrite: true,
      params: [
        { name: 'portal_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'email', type: 'string', required: true, description: 'The person to invite. Required.', in: 'body' },
        { name: 'full_name', type: 'string', required: false, description: 'Optional display name shown in the portal.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/portals/:portal_id/invite" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"email":"...","full_name":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/portals/:portal_id/members/:member_id',
      toolName: 'remove_portal_member',
      description: 'Remove a member from a portal (revokes their access to it).',
      scopes: ['portals:write'],
      isWrite: true,
      params: [
        { name: 'portal_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'member_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/portals/:portal_id/members/:member_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/portals/:portal_id/shares',
      toolName: 'list_portal_shares',
      description: 'List the records shared into a portal.',
      scopes: ['portals:read'],
      isWrite: false,
      params: [
        { name: 'portal_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'resource_type', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/portals/:portal_id/shares" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/portals/:portal_id/shares',
      toolName: 'share_to_portal',
      description: 'Share a workspace record into a portal so its members can see it. This is the explicit access grant — nothing appears in a portal until shared. Idempotent. resource_type is one of: form_submission, signing_envelope, booking, work_order, referral, commission_payment, document_slot, marketing_material.',
      scopes: ['portals:write'],
      isWrite: true,
      params: [
        { name: 'portal_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'resource_type', type: 'string', required: true, description: 'The kind of record being shared.', in: 'body' },
        { name: 'resource_id', type: 'string', required: true, description: 'UUID of the record to share.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/portals/:portal_id/shares" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"resource_type":"...","resource_id":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/portals/:portal_id/shares/:share_id',
      toolName: 'remove_portal_share',
      description: 'Stop sharing a record into a portal (members lose access to it). Does not delete the underlying record.',
      scopes: ['portals:write'],
      isWrite: true,
      params: [
        { name: 'portal_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'share_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/portals/:portal_id/shares/:share_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
