// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/products.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/products.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const PRODUCTS: ResourceGroup = {
  id: 'products',
  label: 'Products',
  description: 'Manage products and services that can be added to deals.',
  endpoints: [
    {
      method: 'GET',
      path: '/products',
      toolName: 'list_products',
      description: 'List products / services in the workspace catalog. Use for quotes, line items on opportunities, or pricing questions.',
      scopes: ['products:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
        { name: 'after', type: 'string', required: false, description: '', in: 'query' },
        { name: 'search', type: 'string', required: false, description: 'Free-text across name and sku', in: 'query' },
        { name: 'category', type: 'string', required: false, description: '', in: 'query' },
        { name: 'is_active', type: 'boolean', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/products" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/products',
      toolName: 'create_product',
      description: 'Create a new product/service. Requires name and price.',
      scopes: ['products:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'sku', type: 'string', required: false, description: '', in: 'body' },
        { name: 'price', type: 'number', required: true, description: '', in: 'body' },
        { name: 'currency', type: 'string', required: false, description: '', in: 'body' },
        { name: 'category', type: 'string', required: false, description: '', in: 'body' },
        { name: 'description', type: 'string', required: false, description: '', in: 'body' },
        { name: 'unit', type: 'string', required: false, description: '', in: 'body' },
        { name: 'deposit_percent', type: 'number', required: false, description: '', in: 'body' },
        { name: 'is_active', type: 'boolean', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/products" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","sku":"...","price":"..."}'`,
    },
    {
      method: 'GET',
      path: '/products/:product_id',
      toolName: 'get_product',
      description: 'Fetch a single product by UUID, including pricing and metadata.',
      scopes: ['products:read'],
      isWrite: false,
      params: [
        { name: 'product_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/products/:product_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/products/:product_id',
      toolName: 'update_product',
      description: 'Update a product. Pass only the fields you want to change.',
      scopes: ['products:write'],
      isWrite: true,
      params: [
        { name: 'product_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'sku', type: 'string', required: false, description: '', in: 'body' },
        { name: 'price', type: 'number', required: false, description: '', in: 'body' },
        { name: 'category', type: 'string', required: false, description: '', in: 'body' },
        { name: 'description', type: 'string', required: false, description: '', in: 'body' },
        { name: 'is_active', type: 'boolean', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/products/:product_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","sku":"...","price":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/products/:product_id',
      toolName: 'delete_product',
      description: 'Delete a product by UUID. Destructive.',
      scopes: ['products:delete'],
      isWrite: true,
      params: [
        { name: 'product_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/products/:product_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/products/:product_id/costs',
      toolName: 'list_product_costs',
      description: 'List all cost entries (supplier costs) for a product.',
      scopes: ['products:read'],
      isWrite: false,
      params: [
        { name: 'product_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/products/:product_id/costs" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/products/:product_id/costs',
      toolName: 'create_product_cost',
      description: 'Add a cost entry to a product (e.g. supplier price).',
      scopes: ['products:write'],
      isWrite: true,
      params: [
        { name: 'product_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'label', type: 'string', required: false, description: '', in: 'body' },
        { name: 'cost_price', type: 'number', required: false, description: '', in: 'body' },
        { name: 'quantity', type: 'number', required: false, description: '', in: 'body' },
        { name: 'currency', type: 'string', required: false, description: '', in: 'body' },
        { name: 'supplier_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'notes', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/products/:product_id/costs" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"label":"...","cost_price":"...","quantity":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/products/:product_id/costs/:cost_id',
      toolName: 'update_product_cost',
      description: 'Update a product cost entry. Pass only the fields you want to change.',
      scopes: ['products:write'],
      isWrite: true,
      params: [
        { name: 'product_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'cost_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'label', type: 'string', required: false, description: '', in: 'body' },
        { name: 'cost_price', type: 'number', required: false, description: '', in: 'body' },
        { name: 'quantity', type: 'number', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/products/:product_id/costs/:cost_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"label":"...","cost_price":"...","quantity":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/products/:product_id/costs/:cost_id',
      toolName: 'delete_product_cost',
      description: 'Delete a product cost entry by UUID. Destructive.',
      scopes: ['products:delete'],
      isWrite: true,
      params: [
        { name: 'product_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'cost_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/products/:product_id/costs/:cost_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
