// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/referrals.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/referrals.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const REFERRALS: ResourceGroup = {
  id: 'referrals',
  label: 'Referrals',
  description: 'Track the referrer -> referred contact -> opportunity chain. Includes workspace-defined category picklist, a leaderboard endpoint, a public token-based submission form, and a create_referral automation action for pipeline-driven partner registration. Every write to the referrals table fires the referral_attributed automation trigger (see GET /schemas/triggers/referral_attributed). Attribution is also cached on the opportunity: crm_deals.primary_referrer_contact_id and crm_deals.primary_referrer_category are maintained by a Postgres trigger and surface in GET /opportunities/:id (including the expand=referrer expansion).',
  endpoints: [
    {
      method: 'GET',
      path: '/referrals',
      toolName: 'list_referrals',
      description: 'List referrals in the workspace.',
      scopes: ['referrals:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl "https://ucqwijexmjctglmrxlej.supabase.co/functions/v1/api/v1/referrals?category=CT&status=pending" \\
  -H "Authorization: Bearer tp_live_..."`,
      responseExample: `{
  "data": [
    {
      "id": "f2788884-aaaa-bbbb-cccc-111111111111",
      "company_id": "ebeff86e-7b09-4e49-96db-f711d69d2d57",
      "referrer_contact_id": "1068084c-f975-4bb8-be1b-4f0a2f0843be",
      "referred_contact_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      "referred_deal_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      "source": "form",
      "status": "pending",
      "category": "CT",
      "notes": null,
      "converted_at": null,
      "commission_paid_to_date": 250,
      "commission_pending": 500,
      "commission_next_payment_date": "2026-07-01",
      "commission_next_payment_amount": 500,
      "created_at": "2026-05-01T09:00:00.000Z",
      "updated_at": "2026-05-01T09:00:00.000Z"
    }
  ],
  "pagination": {
    "total": 1,
    "has_more": false,
    "next_cursor": null
  },
  "meta": { "credits_remaining": 4500 }
}`,
    },
    {
      method: 'POST',
      path: '/referrals',
      toolName: 'create_referral',
      description: 'Create a referral entry. Requires referrer_contact_id.',
      scopes: ['referrals:write'],
      isWrite: true,
      params: [
        { name: 'referrer_contact_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'referred_contact_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'notes', type: 'string', required: false, description: '', in: 'body' },
        { name: 'deal_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST "https://ucqwijexmjctglmrxlej.supabase.co/functions/v1/api/v1/referrals" \\
  -H "Authorization: Bearer tp_live_..." \\
  -H "Content-Type: application/json" \\
  -d '{
    "referrer_contact_id": "1068084c-f975-4bb8-be1b-4f0a2f0843be",
    "category": "MRI",
    "notes": "Met at the networking event last Tuesday"
  }'`,
      responseExample: `{
  "data": {
    "id": "8aa0c05e-d0b2-49b3-b6e8-2da112254c63",
    "company_id": "ebeff86e-7b09-4e49-96db-f711d69d2d57",
    "referrer_contact_id": "1068084c-f975-4bb8-be1b-4f0a2f0843be",
    "referred_contact_id": null,
    "referred_deal_id": null,
    "source": "manual",
    "status": "pending",
    "category": "MRI",
    "notes": "Met at the networking event last Tuesday",
    "converted_at": null,
    "created_at": "2026-05-16T10:00:00.000Z",
    "updated_at": "2026-05-16T10:00:00.000Z"
  },
  "meta": { "credits_remaining": 4499 }
}`,
    },
    {
      method: 'POST',
      path: '/referrals/request',
      toolName: 'request_referral',
      description: 'Ask a contact to refer someone — sends the referral-request flow.',
      scopes: ['referrals:write'],
      isWrite: true,
      params: [
        { name: 'contact_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'channel', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST "https://ucqwijexmjctglmrxlej.supabase.co/functions/v1/api/v1/referrals/request" \\
  -H "Authorization: Bearer tp_live_..." \\
  -H "Content-Type: application/json" \\
  -d '{"contact_id": "1068084c-f975-4bb8-be1b-4f0a2f0843be", "expires_in_days": 30}'`,
      responseExample: `{
  "data": {
    "request_id": "ccdd1234-abcd-1234-abcd-abcdef123456",
    "token": "abc123def456",
    "public_url": "https://app.trustpager.com/refer/abc123def456",
    "expires_at": "2026-06-15T10:00:00.000Z",
    "email_sent": true
  },
  "meta": { "credits_remaining": 4496 }
}`,
    },
    {
      method: 'GET',
      path: '/referrals/requests',
      toolName: 'list_referral_requests',
      description: 'List outbound referral requests.',
      scopes: ['referrals:read'],
      isWrite: false,
      requestExample: `curl "https://ucqwijexmjctglmrxlej.supabase.co/functions/v1/api/v1/referrals/requests?status=sent" \\
  -H "Authorization: Bearer tp_live_..."`,
      responseExample: `{
  "data": [
    {
      "id": "ccdd1234-abcd-1234-abcd-abcdef123456",
      "company_id": "ebeff86e-7b09-4e49-96db-f711d69d2d57",
      "contact_id": "1068084c-f975-4bb8-be1b-4f0a2f0843be",
      "deal_id": null,
      "recipient_email": "referrer@example.com",
      "recipient_name": "Jane Smith",
      "status": "sent",
      "sent_at": "2026-05-16T10:00:00.000Z",
      "viewed_at": null,
      "submitted_at": null,
      "referral_id": null,
      "expires_at": "2026-06-15T10:00:00.000Z",
      "created_at": "2026-05-16T10:00:00.000Z"
    }
  ],
  "pagination": { "total": 1, "has_more": false, "next_cursor": null },
  "meta": { "credits_remaining": 4500 }
}`,
    },
    {
      method: 'GET',
      path: '/referrals/leaderboard',
      toolName: 'get_referral_leaderboard',
      description: 'Get the referrer leaderboard for the workspace.',
      scopes: ['referrals:read'],
      isWrite: false,
      requestExample: `curl "https://ucqwijexmjctglmrxlej.supabase.co/functions/v1/api/v1/referrals/leaderboard?limit=10" \\
  -H "Authorization: Bearer tp_live_..."`,
      responseExample: `{
  "data": {
    "leaderboard": [
      {
        "contact": {
          "id": "1068084c-f975-4bb8-be1b-4f0a2f0843be",
          "first_name": "Jane",
          "last_name": "Smith",
          "email": "jane@example.com",
          "images": []
        },
        "total_referrals": 5,
        "converted_referrals": 3,
        "conversion_rate": 0.6,
        "commission_paid_to_date": 750,
        "commission_pending": 500
      }
    ]
  },
  "meta": { "credits_remaining": 4500 }
}`,
    },
    {
      method: 'POST',
      path: '/referrals/attribute',
      toolName: 'set_opportunity_referrer',
      description: 'Set, reassign, or clear the primary referrer on an opportunity. Pass referrer_contact_id to attribute it to a contact, or null to clear. Updates the referral graph in place so commission tracking and history survive a reassignment, and leaves form/automation-sourced referrals intact.',
      scopes: ['referrals:write'],
      isWrite: true,
      params: [
        { name: 'opportunity_id', type: 'string', required: true, description: 'Opportunity (deal) UUID to attribute. Required.', in: 'body' },
        { name: 'referrer_contact_id', type: 'string,null', required: true, description: 'Contact UUID of the referrer. Pass null to clear the referrer.', in: 'body' },
        { name: 'category', type: 'string', required: false, description: 'Optional referral category (modality, service type, lead source).', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/referrals/attribute" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"opportunity_id":"...","referrer_contact_id":"...","category":"..."}'`,
    },
    {
      method: 'GET',
      path: '/referrals/:referral_id',
      toolName: 'get_referral',
      description: 'Fetch a referral by UUID.',
      scopes: ['referrals:read'],
      isWrite: false,
      params: [
        { name: 'referral_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/referrals/:referral_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/referrals/:referral_id',
      toolName: 'update_referral',
      description: 'Update a referral.',
      scopes: ['referrals:write'],
      isWrite: true,
      params: [
        { name: 'referral_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'status', type: 'string', required: false, description: '', in: 'body' },
        { name: 'notes', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/referrals/:referral_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"status":"...","notes":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/referrals/:referral_id',
      toolName: 'delete_referral',
      description: 'Delete a referral.',
      scopes: ['referrals:delete'],
      isWrite: true,
      params: [
        { name: 'referral_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/referrals/:referral_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/referrals/:referral_id/commissions',
      toolName: 'list_referral_commissions',
      description: 'List the commission instalments (scheduled / paid / cancelled) attached to a referral, ordered by due date.',
      scopes: ['referrals:read'],
      isWrite: false,
      params: [
        { name: 'referral_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/referrals/:referral_id/commissions" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/referrals/:referral_id/commissions',
      toolName: 'add_referral_commission',
      description: 'Add a commission instalment to a referral. amount is required; status defaults to scheduled. The cached commission summary (paid-to-date / pending / next-payment) on the referral updates automatically.',
      scopes: ['referrals:write'],
      isWrite: true,
      params: [
        { name: 'referral_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'amount', type: 'number', required: true, description: '', in: 'body' },
        { name: 'status', type: 'string', required: false, description: 'scheduled | paid | cancelled. Defaults to scheduled.', in: 'body' },
        { name: 'due_date', type: 'string', required: false, description: 'ISO date (YYYY-MM-DD) the instalment is expected.', in: 'body' },
        { name: 'paid_date', type: 'string', required: false, description: 'ISO date (YYYY-MM-DD) the instalment was paid.', in: 'body' },
        { name: 'notes', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/referrals/:referral_id/commissions" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"amount":"...","status":"...","due_date":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/referrals/:referral_id/commissions/:payment_id',
      toolName: 'update_referral_commission',
      description: 'Update a commission instalment (amount, status, due_date, paid_date, notes). Setting status to paid auto-stamps paid_date when none is supplied.',
      scopes: ['referrals:write'],
      isWrite: true,
      params: [
        { name: 'referral_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'payment_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'amount', type: 'number', required: false, description: '', in: 'body' },
        { name: 'status', type: 'string', required: false, description: '', in: 'body' },
        { name: 'due_date', type: 'string', required: false, description: '', in: 'body' },
        { name: 'paid_date', type: 'string', required: false, description: '', in: 'body' },
        { name: 'notes', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/referrals/:referral_id/commissions/:payment_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"amount":"...","status":"...","due_date":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/referrals/:referral_id/commissions/:payment_id',
      toolName: 'delete_referral_commission',
      description: 'Delete a commission instalment from a referral. The cached commission summary on the referral updates automatically.',
      scopes: ['referrals:write'],
      isWrite: true,
      params: [
        { name: 'referral_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'payment_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/referrals/:referral_id/commissions/:payment_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
