// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/reports.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/reports.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const REPORTS: ResourceGroup = {
  id: 'reports',
  label: 'Reports',
  description: 'Query engine, dashboard CRUD, card CRUD, and funnel configuration for the workspace reporting system. Dashboards support per-record visibility (all_users or restricted) with ACL-based access grants.',
  endpoints: [
    {
      method: 'POST',
      path: '/reports/query',
      toolName: 'query_report',
      description: 'Run a report query against the workspace. Free read. The "deals" source excludes pipelines flagged exclude_from_lead_reporting by default; pass include_excluded_pipelines:true to include them.',
      scopes: ['opportunities:read'],
      isWrite: false,
      params: [
        { name: 'source', type: 'string', required: true, description: '', in: 'body' },
        { name: 'measures', type: 'array', required: false, description: '', in: 'body' },
        { name: 'dimensions', type: 'array', required: false, description: '', in: 'body' },
        { name: 'filters', type: 'array', required: false, description: '', in: 'body' },
        { name: 'include_excluded_pipelines', type: 'boolean', required: false, description: 'Deals source only. Include pipelines flagged exclude_from_lead_reporting (excluded by default).', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/reports/query" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"source":"...","measures":"...","dimensions":"..."}'`,
    },
    {
      method: 'GET',
      path: '/reports/sources',
      toolName: 'list_report_sources',
      description: 'List available reporting data sources, measures, and dimensions.',
      scopes: ['opportunities:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/reports/sources" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/reports/templates',
      toolName: 'list_report_templates',
      description: 'List dashboard templates.',
      scopes: ['opportunities:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/reports/templates" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/reports/send',
      toolName: 'send_report_email',
      description: 'Send a dashboard digest email.',
      scopes: ['opportunities:read'],
      isWrite: true,
      params: [
        { name: 'dashboard_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'to', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/reports/send" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"dashboard_id":"...","to":"..."}'`,
    },
    {
      method: 'POST',
      path: '/reports/render-preview',
      toolName: 'render_report_preview',
      description: 'Server-side render a dashboard to HTML for preview.',
      scopes: ['opportunities:read'],
      isWrite: false,
      params: [
        { name: 'dashboard_id', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/reports/render-preview" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"dashboard_id":"..."}'`,
    },
    {
      method: 'POST',
      path: '/report-dashboards',
      toolName: 'create_report_dashboard',
      description: 'Create a report dashboard.',
      scopes: ['opportunities:read'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'template_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/report-dashboards" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","template_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/report-dashboards',
      toolName: 'list_report_dashboards',
      description: 'List report dashboards.',
      scopes: ['opportunities:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/report-dashboards" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/report-dashboards/:dashboard_id',
      toolName: 'get_report_dashboard',
      description: 'Fetch a dashboard with cards.',
      scopes: ['opportunities:read'],
      isWrite: false,
      params: [
        { name: 'dashboard_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/report-dashboards/:dashboard_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/report-dashboards/:dashboard_id',
      toolName: 'update_report_dashboard',
      description: 'Update a dashboard.',
      scopes: ['opportunities:read'],
      isWrite: true,
      params: [
        { name: 'dashboard_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/report-dashboards/:dashboard_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/report-dashboards/:dashboard_id',
      toolName: 'delete_report_dashboard',
      description: 'Delete a dashboard.',
      scopes: ['opportunities:read'],
      isWrite: true,
      params: [
        { name: 'dashboard_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/report-dashboards/:dashboard_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/report-dashboards/:dashboard_id/cards',
      toolName: 'add_report_card',
      description: 'Add a card to a dashboard.',
      scopes: ['opportunities:read'],
      isWrite: true,
      params: [
        { name: 'dashboard_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'type', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/report-dashboards/:dashboard_id/cards" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"type":"..."}'`,
    },
    {
      method: 'PUT',
      path: '/report-dashboards/:dashboard_id/reorder',
      toolName: 'reorder_report_cards',
      description: 'Reorder cards on a dashboard.',
      scopes: ['opportunities:read'],
      isWrite: true,
      params: [
        { name: 'dashboard_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'card_ids', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X PUT \
  "${API_BASE_URL}/report-dashboards/:dashboard_id/reorder" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"card_ids":"..."}'`,
    },
    {
      method: 'GET',
      path: '/report-dashboards/:dashboard_id/acl',
      toolName: 'list_report_dashboard_acl',
      description: 'List dashboard ACL grants.',
      scopes: ['opportunities:read'],
      isWrite: false,
      params: [
        { name: 'dashboard_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/report-dashboards/:dashboard_id/acl" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/report-dashboards/:dashboard_id/acl',
      toolName: 'add_report_dashboard_acl_entry',
      description: 'Grant dashboard access.',
      scopes: ['opportunities:read'],
      isWrite: true,
      params: [
        { name: 'dashboard_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'principal_type', type: 'string', required: true, description: '', in: 'body' },
        { name: 'principal_id', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/report-dashboards/:dashboard_id/acl" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"principal_type":"...","principal_id":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/report-cards/:card_id',
      toolName: 'update_report_card',
      description: 'Update a card.',
      scopes: ['opportunities:read'],
      isWrite: true,
      params: [
        { name: 'card_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/report-cards/:card_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/report-cards/:card_id',
      toolName: 'remove_report_card',
      description: 'Delete a card.',
      scopes: ['opportunities:read'],
      isWrite: true,
      params: [
        { name: 'card_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/report-cards/:card_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/report-funnels',
      toolName: 'get_report_funnel_config',
      description: 'Get funnel config for a pipeline.',
      scopes: ['opportunities:read'],
      isWrite: false,
      params: [
        { name: 'pipeline_id', type: 'string', required: true, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/report-funnels" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PUT',
      path: '/report-funnels',
      toolName: 'configure_report_funnel',
      description: 'Configure a funnel for a pipeline.',
      scopes: ['opportunities:read'],
      isWrite: true,
      params: [
        { name: 'pipeline_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'steps', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X PUT \
  "${API_BASE_URL}/report-funnels" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"pipeline_id":"...","steps":"..."}'`,
    },
  ],
};
