// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/scheduling.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/scheduling.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const SCHEDULING: ResourceGroup = {
  id: 'scheduling',
  label: 'SCHEDULING',
  description: 'scheduling endpoints.',
  endpoints: [
    {
      method: 'GET',
      path: '/scheduling/event-types',
      toolName: 'list_scheduled_event_types',
      description: 'List the workspace scheduled event types (meeting templates). Use to find event_type_id for get_available_slots and create_booking.',
      scopes: ['scheduling:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/scheduling/event-types" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/scheduling/event-types',
      toolName: 'create_scheduled_event_type',
      description: 'Create a new scheduled event type (meeting template).',
      scopes: ['scheduling:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'duration_minutes', type: 'number', required: false, description: '', in: 'body' },
        { name: 'host_user_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'description', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/event-types" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","duration_minutes":"...","host_user_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/scheduling/event-types/:event_type_id',
      toolName: 'get_scheduled_event_type',
      description: 'Fetch a single scheduled event type by UUID.',
      scopes: ['scheduling:read'],
      isWrite: false,
      params: [
        { name: 'event_type_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/scheduling/event-types/:event_type_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/scheduling/event-types/:event_type_id',
      toolName: 'update_scheduled_event_type',
      description: 'Update a scheduled event type.',
      scopes: ['scheduling:write'],
      isWrite: true,
      params: [
        { name: 'event_type_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'duration_minutes', type: 'number', required: false, description: '', in: 'body' },
        { name: 'host_user_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'description', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/scheduling/event-types/:event_type_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","duration_minutes":"...","host_user_id":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/scheduling/event-types/:event_type_id',
      toolName: 'delete_scheduled_event_type',
      description: 'Delete a scheduled event type by UUID. Destructive.',
      scopes: ['scheduling:delete'],
      isWrite: true,
      params: [
        { name: 'event_type_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/scheduling/event-types/:event_type_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/scheduling/availability',
      toolName: 'get_scheduling_availability',
      description: 'Get the workspace working-hours availability and overrides.',
      scopes: ['scheduling:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/scheduling/availability" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PUT',
      path: '/scheduling/availability',
      toolName: 'update_scheduling_availability',
      description: 'Update workspace working hours and date overrides.',
      scopes: ['scheduling:write'],
      isWrite: true,
      params: [
        { name: 'working_hours', type: 'object', required: false, description: '', in: 'body' },
        { name: 'overrides', type: 'array', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PUT \
  "${API_BASE_URL}/scheduling/availability" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"working_hours":"...","overrides":"..."}'`,
    },
    {
      method: 'POST',
      path: '/scheduling/available-slots',
      toolName: 'get_available_slots',
      description: 'Get available booking slots for a scheduled event type within a date range. Returns slot start times in host timezone.',
      scopes: ['scheduling:read'],
      isWrite: false,
      params: [
        { name: 'event_type_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'start_date', type: 'string', required: true, description: '', in: 'body' },
        { name: 'end_date', type: 'string', required: true, description: '', in: 'body' },
        { name: 'timezone', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/available-slots" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"event_type_id":"...","start_date":"...","end_date":"..."}'`,
    },
    {
      method: 'POST',
      path: '/scheduling/check-availability',
      toolName: 'check_slot_availability',
      description: 'Quick check whether a specific slot is available. Returns nearest available alternatives if not.',
      scopes: ['scheduling:read'],
      isWrite: false,
      params: [
        { name: 'event_type_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'slot', type: 'string', required: true, description: 'ISO datetime', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/check-availability" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"event_type_id":"...","slot":"..."}'`,
    },
    {
      method: 'POST',
      path: '/scheduling/voice/cancel-booking',
      toolName: 'voice_cancel_booking',
      description: 'AI voice agent — cancel a booking keyed by caller phone.',
      scopes: ['scheduling:write'],
      isWrite: true,
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/voice/cancel-booking" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/scheduling/voice/reschedule-booking',
      toolName: 'voice_reschedule_booking',
      description: 'AI voice agent — reschedule a booking keyed by caller phone.',
      scopes: ['scheduling:write'],
      isWrite: true,
      params: [
        { name: 'slot', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/voice/reschedule-booking" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"slot":"..."}'`,
    },
    {
      method: 'POST',
      path: '/scheduling/voice/:event_type_id/slots',
      toolName: 'voice_get_slots',
      description: 'AI voice agent — get available slots for an event type.',
      scopes: ['scheduling:read'],
      isWrite: false,
      params: [
        { name: 'event_type_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/voice/:event_type_id/slots" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/scheduling/voice/:event_type_id/book',
      toolName: 'voice_book',
      description: 'AI voice agent — create a booking from voice flow.',
      scopes: ['scheduling:write'],
      isWrite: true,
      params: [
        { name: 'event_type_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'slot', type: 'string', required: true, description: '', in: 'body' },
        { name: 'invitee_name', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/voice/:event_type_id/book" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"slot":"...","invitee_name":"..."}'`,
    },
    {
      method: 'GET',
      path: '/scheduling/bookings',
      toolName: 'list_bookings',
      description: 'List bookings (calendar appointments). Filter by date, contact, host, status.',
      scopes: ['scheduling:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
        { name: 'after', type: 'string', required: false, description: '', in: 'query' },
        { name: 'contact_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'customer_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'deal_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'host_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'status', type: 'string', required: false, description: '', in: 'query' },
        { name: 'from', type: 'string', required: false, description: '', in: 'query' },
        { name: 'to', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/scheduling/bookings" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/scheduling/bookings',
      toolName: 'create_booking',
      description: 'Create a calendar booking. Use get_available_slots first to find a valid start_time.',
      scopes: ['scheduling:write'],
      isWrite: true,
      params: [
        { name: 'event_type_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'start_time', type: 'string', required: true, description: '', in: 'body' },
        { name: 'invitee_email', type: 'string', required: true, description: '', in: 'body' },
        { name: 'invitee_name', type: 'string', required: false, description: '', in: 'body' },
        { name: 'contact_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'deal_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'notes', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/bookings" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"event_type_id":"...","start_time":"...","invitee_email":"..."}'`,
    },
    {
      method: 'GET',
      path: '/scheduling/bookings/:booking_id',
      toolName: 'get_booking',
      description: 'Fetch a single booking by UUID with event details, invitee, host, status, linked records.',
      scopes: ['scheduling:read'],
      isWrite: false,
      params: [
        { name: 'booking_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/scheduling/bookings/:booking_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/scheduling/bookings/:booking_id/cancel',
      toolName: 'cancel_booking',
      description: 'Cancel a booking. Invitee gets cancellation notice.',
      scopes: ['scheduling:write'],
      isWrite: true,
      params: [
        { name: 'booking_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'reason', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/bookings/:booking_id/cancel" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"reason":"..."}'`,
    },
    {
      method: 'POST',
      path: '/scheduling/bookings/:booking_id/reschedule',
      toolName: 'reschedule_booking',
      description: 'Reschedule a booking. Use get_available_slots to find a valid new slot.',
      scopes: ['scheduling:write'],
      isWrite: true,
      params: [
        { name: 'booking_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'slot', type: 'string', required: true, description: '', in: 'body' },
        { name: 'reason', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/bookings/:booking_id/reschedule" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"slot":"...","reason":"..."}'`,
    },
    {
      method: 'POST',
      path: '/scheduling/bookings/:booking_id/mark-attended',
      toolName: 'mark_booking_attended',
      description: 'Mark a booking as attended.',
      scopes: ['scheduling:write'],
      isWrite: true,
      params: [
        { name: 'booking_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/bookings/:booking_id/mark-attended" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/scheduling/bookings/:booking_id/mark-late',
      toolName: 'mark_booking_late',
      description: 'Mark a booking as late.',
      scopes: ['scheduling:write'],
      isWrite: true,
      params: [
        { name: 'booking_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/bookings/:booking_id/mark-late" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/scheduling/bookings/:booking_id/mark-no-show',
      toolName: 'mark_booking_no_show',
      description: 'Mark a booking as no-show.',
      scopes: ['scheduling:write'],
      isWrite: true,
      params: [
        { name: 'booking_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/bookings/:booking_id/mark-no-show" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/scheduling/bookings/:booking_id/notetaker',
      toolName: 'schedule_notetaker_for_booking',
      description: 'Schedule the TrustPager Notetaker to join a booking.',
      scopes: ['scheduling:write'],
      isWrite: true,
      params: [
        { name: 'booking_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduling/bookings/:booking_id/notetaker" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
