// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/scheduled-communications.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/scheduled-communications.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const SCHEDULED_COMMUNICATIONS: ResourceGroup = {
  id: 'scheduled-communications',
  label: 'Scheduled Communications',
  description: 'Queue deferred emails, SMS, and AI voice calls for future dispatch. The communications_scheduler_tick cron (runs every minute) claims pending rows, enforces business-hours windows, retries with exponential backoff, and dispatches via the automation pipeline. Row lifecycle: pending -> dispatching -> dispatched | failed | cancelled | skipped.',
  endpoints: [
    {
      method: 'GET',
      path: '/scheduled-communications',
      toolName: 'list_scheduled_communications',
      description: 'List the unified queue of scheduled emails, SMS and voice calls.',
      scopes: ['dispatcher:read'],
      isWrite: false,
      params: [
        { name: 'status', type: 'string', required: false, description: '', in: 'query' },
        { name: 'channel', type: 'string', required: false, description: '', in: 'query' },
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl -X GET \\
  "${API_BASE_URL}/scheduled-communications?status=pending&channel=email&limit=10" \\
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{
  "data": [
    {
      "id": "60b5889e-c8e1-4273-836e-67a3f0b3231a",
      "company_id": "ebeff86e-7b09-4e49-96db-f711d69d2d57",
      "channel": "email",
      "status": "pending",
      "scheduled_for": "2026-05-01T09:00:00+00:00",
      "timezone": "Australia/Sydney",
      "respect_business_hours": true,
      "payload": {
        "to_email": "client@example.com",
        "subject": "Follow-up from our call",
        "html_body": "<p>Hi Sarah, ...</p>"
      },
      "contact_id": "abc123...",
      "deal_id": null,
      "customer_id": null,
      "attempt_count": 0,
      "last_attempt_at": null,
      "last_error": null,
      "dispatched_at": null,
      "dispatched_external_id": null,
      "source": "api",
      "created_at": "2026-04-23T15:00:00Z",
      "updated_at": "2026-04-23T15:00:00Z"
    }
  ],
  "pagination": { "limit": 10, "has_more": false, "next_cursor": null, "prev_cursor": null },
  "meta": { "credits_remaining": 50000, "url": "https://app.trustpager.com/inbox/dispatcher" }
}`,
    },
    {
      method: 'POST',
      path: '/scheduled-communications',
      toolName: 'schedule_communication',
      description: 'Schedule a deferred email, SMS or voice call for future dispatch.',
      scopes: ['dispatcher:write'],
      isWrite: true,
      params: [
        { name: 'channel', type: 'string', required: true, description: '', in: 'body' },
        { name: 'scheduled_for', type: 'string', required: true, description: '', in: 'body' },
        { name: 'payload', type: 'object', required: true, description: '', in: 'body' },
        { name: 'contact_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'deal_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `# Schedule an email for tomorrow morning (business hours enforced)
curl -X POST \\
  "${API_BASE_URL}/scheduled-communications" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "channel": "email",
    "scheduled_for": "2026-05-01T09:00:00Z",
    "timezone": "Australia/Sydney",
    "respect_business_hours": true,
    "payload": {
      "to_email": "client@example.com",
      "subject": "Following up on your quote",
      "html_body": "<p>Hi Sarah, just checking in...</p>",
      "contact_id": "abc123..."
    },
    "contact_id": "abc123..."
  }'

# Schedule an AI voice call for next week
curl -X POST \\
  "${API_BASE_URL}/scheduled-communications" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "channel": "voice_call",
    "scheduled_for": "2026-05-05T10:00:00Z",
    "timezone": "Australia/Brisbane",
    "respect_business_hours": true,
    "payload": {
      "voice_agent_outbound_config_id": "config-uuid...",
      "to_number": "+61412345678",
      "dynamic_variables": { "contact_name": "Sarah", "deal_name": "Website Project" }
    }
  }'

# Schedule a voice call with multi-attempt cadence (3 attempts: now, +2h, +24h)
curl -X POST \\
  "${API_BASE_URL}/scheduled-communications" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "channel": "voice_call",
    "scheduled_for": "2026-05-05T10:00:00Z",
    "timezone": "Australia/Brisbane",
    "respect_business_hours": true,
    "contact_id": "contact-uuid...",
    "payload": {
      "voice_agent_outbound_config_id": "config-uuid...",
      "to_number": "+61412345678",
      "dynamic_variables": { "contact_name": "Sarah" },
      "follow_ups": {
        "max_attempts": 3,
        "follow_up_delays": [2, 24],
        "voice_agent_outbound_config_id": "config-uuid...",
        "to_number": "+61412345678",
        "respect_business_hours": true,
        "contact_id": "contact-uuid..."
      }
    }
  }'`,
      responseExample: `{
  "data": {
    "id": "60b5889e-c8e1-4273-836e-67a3f0b3231a",
    "channel": "email",
    "status": "pending",
    "scheduled_for": "2026-05-01T09:00:00+00:00",
    "timezone": "Australia/Sydney",
    "respect_business_hours": true,
    "payload": { "to_email": "client@example.com", "subject": "Following up on your quote", "html_body": "..." },
    "contact_id": "abc123...",
    "attempt_count": 0,
    "source": "api",
    "created_at": "2026-04-23T15:00:00Z"
  },
  "meta": { "credits_remaining": 49999 }
}`,
      notes: [
        'Scheduling email requires dispatcher:write AND email:send scopes.',
        'Scheduling SMS requires dispatcher:write AND sms:send scopes.',
        'Scheduling a voice call requires dispatcher:write AND calls:initiate scopes.',
        'When respect_business_hours=true, the scheduler defers rows outside Mon-Fri 9-5 in the callee\\\\\\\\\\\\\\\'s timezone (configurable per company).',
        'The scheduler tick runs every minute. Expect up to 1 minute of latency after scheduled_for.',
        'Rows retry with exponential backoff: email/SMS up to 3 attempts, voice_call up to 2.',
        'Voice cadence (multi-attempt): include a follow_ups object in the voice_call payload to automatically schedule retries. follow_up_delays is an array of hours between each attempt (supports decimals: 0.5 = 30 min). The cadence stops early if the call connects and the contact speaks for 10+ seconds (real conversation detected). Retries are queued as new pending rows in the dispatcher.',
      ],
    },
    {
      method: 'POST',
      path: '/scheduled-communications/bulk-cancel',
      toolName: 'bulk_cancel_scheduled_communications',
      description: 'Cancel multiple scheduled communications matching a filter.',
      scopes: ['dispatcher:write'],
      isWrite: true,
      params: [
        { name: 'ids', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduled-communications/bulk-cancel" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"ids":"..."}'`,
    },
    {
      method: 'GET',
      path: '/scheduled-communications/:scheduled_id',
      toolName: 'get_scheduled_communication',
      description: 'Fetch a scheduled communication by UUID.',
      scopes: ['dispatcher:read'],
      isWrite: false,
      params: [
        { name: 'scheduled_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/scheduled-communications/:scheduled_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/scheduled-communications/:scheduled_id',
      toolName: 'update_scheduled_communication',
      description: 'Update a pending scheduled communication (only while status=pending).',
      scopes: ['dispatcher:write'],
      isWrite: true,
      params: [
        { name: 'scheduled_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'scheduled_for', type: 'string', required: false, description: '', in: 'body' },
        { name: 'payload', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/scheduled-communications/:scheduled_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"scheduled_for":"...","payload":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/scheduled-communications/:scheduled_id',
      toolName: 'cancel_scheduled_communication',
      description: 'Soft-cancel a scheduled communication.',
      scopes: ['dispatcher:write'],
      isWrite: true,
      params: [
        { name: 'scheduled_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/scheduled-communications/:scheduled_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/scheduled-communications/:scheduled_id/dispatch-now',
      toolName: 'dispatch_scheduled_communication_now',
      description: 'Dispatch a pending scheduled communication immediately.',
      scopes: ['dispatcher:write'],
      isWrite: true,
      params: [
        { name: 'scheduled_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/scheduled-communications/:scheduled_id/dispatch-now" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
