// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/schemas.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/schemas.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const SCHEMAS: ResourceGroup = {
  id: 'schemas',
  label: 'Schemas',
  description: 'Discoverable reference data for automation trigger types. Returns the shape of trigger_data each trigger publishes, the {{variable}} tokens available in action templates, and CRM-enriched variable namespaces. Free -- 0 credits, no scope required.',
  endpoints: [
    {
      method: 'GET',
      path: '/schemas/triggers',
      toolName: 'list_trigger_schemas',
      description: 'List all automation trigger schemas — the discoverable shape of every trigger type. Free read.',
      scopes: [],
      isWrite: false,
      requestExample: `curl -X GET \\
  "${API_BASE_URL}/schemas/triggers" \\
  -H "Authorization: Bearer YOUR_API_KEY"`,
      responseExample: `{
  "data": {
    "count": 43,
    "enriched_variables": {
      "contact.*": "Contact record fields (first_name, last_name, email, phone, custom fields) - populated after opportunity matching.",
      "deal.*": "Deal/opportunity fields (name, value, status, opportunity_type, tags).",
      "customer.*": "Customer/account record fields (name, abn, industry). Also available as account.*.",
      "today": "Today as YYYY-MM-DD in the company timezone.",
      "now": "Current timestamp as ISO 8601."
    },
    "triggers": [
      {
        "trigger_type": "referral_attributed",
        "label": "Referral Attributed",
        "description": "When an inbound referral is recorded -- fires for every code path (create_referral automation action, public form, or direct API/MCP create). Use to thank referrers, alert team, or increment per-referrer counters.",
        "sample_trigger_data": {
          "referral_id": "uuid",
          "referrer_contact_id": "uuid",
          "referrer_email": "dr.smith@clinic.com.au",
          "referred_contact_id": "uuid",
          "referred_deal_id": "uuid",
          "category": "CT",
          "status": "pending",
          "source": "api",
          "notes": null
        },
        "available_variables": [
          "{{referral_id}}",
          "{{referrer_contact_id}}",
          "{{referrer_email}}",
          "{{referred_contact_id}}",
          "{{referred_deal_id}}",
          "{{category}}",
          "{{status}}",
          "{{source}}",
          "{{notes}}"
        ]
      },
      {
        "trigger_type": "facebook_lead_ad",
        "label": "Facebook Lead Ad",
        "description": "When a Facebook Lead Ad form is submitted.",
        "sample_trigger_data": {
          "page_id": "123456789",
          "form_id": "form_abc123",
          "first_name": "John",
          "last_name": "Doe",
          "email": "john@example.com",
          "phone": "+61431377068"
        },
        "available_variables": [
          "{{page_id}}",
          "{{form_id}}",
          "{{first_name}}",
          "{{last_name}}",
          "{{email}}",
          "{{phone}}"
        ]
      }
    ]
  },
  "meta": { "credits_remaining": 10000 }
}`,
    },
    {
      method: 'GET',
      path: '/schemas/triggers/:trigger_type|str',
      toolName: 'get_trigger_schema',
      description: 'Fetch a single trigger schema by trigger_type (e.g. contact_created). Free read.',
      scopes: [],
      isWrite: false,
      params: [
        { name: 'trigger_type', type: 'string', required: true, description: 'Trigger type identifier', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/schemas/triggers/:trigger_type|str" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
