// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/search.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/search.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const SEARCH: ResourceGroup = {
  id: 'search',
  label: 'Universal Search',
  description: 'Search across all entity types (contacts, customers, deals) in a single call. Supports fuzzy/typo-tolerant matching on names via pg_trgm.',
  endpoints: [
    {
      method: 'POST',
      path: '/search',
      toolName: 'search',
      description: 'Cross-entity fuzzy search across contacts, companies, and opportunities. Use this when the user gives a name without specifying entity type — returns matches across all three with their UUIDs and types. Faster than calling each list_* tool separately.',
      scopes: ['contacts:read', 'companies:read', 'opportunities:read'],
      isWrite: false,
      params: [
        { name: 'query', type: 'string', required: true, description: 'Free-text search query. Matches across names, emails, phones, notes.', in: 'body' },
        { name: 'limit', type: 'number', required: false, description: 'Max results per entity type (default 25)', in: 'body' },
      ],
      requestExample: `curl -X POST \\
  "${API_BASE_URL}/search" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{ "query": "Sarah", "limit": 10 }'`,
      responseExample: `{
  "data": [
    {
      "entity_type": "contact",
      "entity_id": "a1b2c3d4-...",
      "display_name": "Sarah Johnson",
      "subtitle": "sarah@example.com",
      "rank": 1.0
    },
    {
      "entity_type": "customer",
      "entity_id": "e5f6a7b8-...",
      "display_name": "Sarah Johnson Ltd",
      "subtitle": "info@sarahjohnson.com.au",
      "rank": 0.85
    },
    {
      "entity_type": "deal",
      "entity_id": "c9d0e1f2-...",
      "display_name": "Website Redesign - Sarah Johnson",
      "subtitle": "open",
      "rank": 0.72
    }
  ],
  "meta": { "credits_remaining": 4500 }
}`,
    },
  ],
};
