// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/seo.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/seo.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const SEO: ResourceGroup = {
  id: 'seo',
  label: 'SEO',
  description: 'seo endpoints.',
  endpoints: [
    {
      method: 'POST',
      path: '/seo-research/keyword-research',
      toolName: 'seo_keyword_research',
      description: 'Run keyword research via TrustPager SEO. Returns each keyword with monthly search volume, CPC, competition, and keyword difficulty. Costs credits. Results are saved as a run you can re-open without paying again.',
      scopes: ['seo:write'],
      isWrite: true,
      params: [
        { name: 'seed_keywords', type: 'array', required: true, description: 'One or more seed keywords to expand from.', in: 'body' },
        { name: 'location', type: 'string', required: false, description: 'Country code: AU (default), US, GB, NZ, CA.', in: 'body' },
        { name: 'language', type: 'string', required: false, description: 'Language code, default en.', in: 'body' },
        { name: 'website_id', type: 'string', required: false, description: 'Optional website UUID to attach this run to.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/seo-research/keyword-research" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"seed_keywords":"...","location":"...","language":"..."}'`,
    },
    {
      method: 'POST',
      path: '/seo-research/competitor-gap',
      toolName: 'seo_competitor_gap',
      description: 'Find the keywords a competitor domain ranks for via TrustPager SEO, with volume/CPC/difficulty. Optionally pass your_domain to focus on the gap. Costs credits. Saved as a run.',
      scopes: ['seo:write'],
      isWrite: true,
      params: [
        { name: 'competitor_domain', type: 'string', required: true, description: 'Competitor domain, e.g. competitor.com.', in: 'body' },
        { name: 'your_domain', type: 'string', required: false, description: 'Optional — your own domain to compare against.', in: 'body' },
        { name: 'location', type: 'string', required: false, description: 'Country code: AU (default), US, GB, NZ, CA.', in: 'body' },
        { name: 'language', type: 'string', required: false, description: 'Language code, default en.', in: 'body' },
        { name: 'website_id', type: 'string', required: false, description: 'Optional website UUID to attach this run to.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/seo-research/competitor-gap" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"competitor_domain":"...","your_domain":"...","location":"..."}'`,
    },
    {
      method: 'POST',
      path: '/seo-research/serp-snapshot',
      toolName: 'seo_serp_snapshot',
      description: 'Capture the live top organic search results for a keyword in a location via TrustPager SEO. Costs credits. Saved as a run.',
      scopes: ['seo:write'],
      isWrite: true,
      params: [
        { name: 'keyword', type: 'string', required: true, description: 'The search query to snapshot.', in: 'body' },
        { name: 'location', type: 'string', required: false, description: 'Country code: AU (default), US, GB, NZ, CA.', in: 'body' },
        { name: 'language', type: 'string', required: false, description: 'Language code, default en.', in: 'body' },
        { name: 'website_id', type: 'string', required: false, description: 'Optional website UUID to attach this run to.', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/seo-research/serp-snapshot" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"keyword":"...","location":"...","language":"..."}'`,
    },
    {
      method: 'GET',
      path: '/seo-research/runs',
      toolName: 'seo_list_runs',
      description: 'List past TrustPager SEO research runs (newest first). Filter by website_id or tool.',
      scopes: ['seo:read'],
      isWrite: false,
      params: [
        { name: 'website_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'tool', type: 'string', required: false, description: 'keyword_research | competitor_gap | serp_snapshot', in: 'query' },
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/seo-research/runs" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/seo-research/runs/:run_id',
      toolName: 'seo_get_run',
      description: 'Fetch a TrustPager SEO research run by UUID with its full result rows.',
      scopes: ['seo:read'],
      isWrite: false,
      params: [
        { name: 'run_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/seo-research/runs/:run_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
