// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/service-requests.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/service-requests.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const SERVICE_REQUESTS: ResourceGroup = {
  id: 'service-requests',
  label: 'Service Requests',
  description: 'Submit and manage platform improvement requests. Designed for AI agents to report missing capabilities, suggest new features, and flag issues with the MCP, API, or platform. Supports listing, filtering, note threads, inline note editing, and two-way ticket linking.',
  endpoints: [
    {
      method: 'GET',
      path: '/service-requests',
      toolName: 'list_service_requests',
      description: 'List platform improvement / capability requests submitted by AI agents.',
      scopes: ['service-requests:read'],
      isWrite: false,
      params: [
        { name: 'status', type: 'string', required: false, description: '', in: 'query' },
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl https://ucqwijexmjctglmrxlej.supabase.co/functions/v1/api/v1/service-requests?status=pending&priority=high \\
  -H "Authorization: Bearer tp_live_..."`,
      responseExample: `{
  "data": [
    {
      "id": "f112de7b-c7df-4193-bacd-2d43c31c1f11",
      "title": "Add status filter to list_opportunities",
      "description": "Cannot filter opportunities by status (won/lost/open).",
      "status": "pending",
      "context": {
        "source": "api",
        "category": "missing_filter",
        "priority": "high",
        "affected_tools": ["list_opportunities"]
      },
      "related_ids": [],
      "notes": [],
      "created_at": "2026-04-19T05:08:56.498025+00:00",
      "updated_at": "2026-04-19T05:08:56.498025+00:00",
      "user_id": "771a4a38-3a5d-4a9b-98c3-e10879850c9d"
    }
  ],
  "meta": {
    "credits_remaining": 3457,
    "pagination": { "has_more": false, "next_cursor": null, "count": 1 }
  }
}`,
    },
    {
      method: 'POST',
      path: '/service-requests',
      toolName: 'create_service_request',
      description: 'File a platform improvement / capability request. Use when you hit a missing tool, missing field, confusing error, or bug.',
      scopes: ['service-requests:write'],
      isWrite: true,
      params: [
        { name: 'title', type: 'string', required: true, description: '', in: 'body' },
        { name: 'description', type: 'string', required: true, description: '', in: 'body' },
        { name: 'category', type: 'string', required: false, description: '', in: 'body' },
        { name: 'priority', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST https://ucqwijexmjctglmrxlej.supabase.co/functions/v1/api/v1/service-requests \\
  -H "Authorization: Bearer tp_live_..." \\
  -H "Content-Type: application/json" \\
  -d '{
    "title": "Add status filter to list_opportunities",
    "description": "Cannot filter opportunities by status (won/lost/open). Had to fetch all opportunities and filter client-side.",
    "category": "missing_filter",
    "affected_tools": ["list_opportunities"],
    "suggested_solution": "Add a status query parameter to GET /opportunities",
    "use_case": "User asked for a report of won deals from last quarter",
    "priority": "medium",
    "related_ids": ["a1b2c3d4-e5f6-7890-abcd-ef1234567890"]
  }'`,
      responseExample: `{
  "data": {
    "id": "f112de7b-c7df-4193-bacd-2d43c31c1f11",
    "title": "Add status filter to list_opportunities",
    "description": "Cannot filter opportunities by status (won/lost/open)...",
    "context": {
      "source": "api",
      "category": "missing_filter",
      "priority": "medium",
      "affected_tools": ["list_opportunities"],
      "suggested_solution": "Add a status query parameter to GET /opportunities",
      "use_case": "User asked for a report of won deals from last quarter"
    },
    "status": "pending",
    "related_ids": ["a1b2c3d4-e5f6-7890-abcd-ef1234567890"],
    "created_at": "2026-04-19T05:08:56.498025+00:00"
  },
  "meta": {
    "credits_remaining": 3457,
    "url": "https://app.trustpager.com/settings/service-requests",
    "message": "Service request logged. The customer can track all requests at the URL above."
  }
}`,
    },
    {
      method: 'GET',
      path: '/service-requests/:request_id',
      toolName: 'get_service_request',
      description: 'Fetch a service request by UUID with full details and notes.',
      scopes: ['service-requests:read'],
      isWrite: false,
      params: [
        { name: 'request_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/service-requests/:request_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/service-requests/search',
      toolName: 'search_service_requests',
      description: 'Semantic search across this workspace\'s service requests using vector embeddings. Use to find duplicates before filing, group related open requests, or find historical resolutions. Returns ranked SRs by cosine similarity.',
      scopes: ['service-requests:read'],
      isWrite: false,
      params: [
        { name: 'query', type: 'string', required: true, description: 'Natural-language description of what you\'re looking for', in: 'body' },
        { name: 'status', type: 'string', required: false, description: 'Optional: restrict to a single status', in: 'body' },
        { name: 'limit', type: 'number', required: false, description: 'Max results, 1-50 (default 10)', in: 'body' },
        { name: 'threshold', type: 'number', required: false, description: 'Minimum cosine similarity 0-1 (default 0.5)', in: 'body' },
      ],
      requestExample: `curl -X POST https://ucqwijexmjctglmrxlej.supabase.co/functions/v1/api/v1/service-requests/search \\
  -H "Authorization: Bearer tp_live_..." \\
  -H "Content-Type: application/json" \\
  -d '{
    "query": "missing status filter on list opportunities",
    "status": "pending",
    "limit": 5
  }'`,
      responseExample: `{
  "data": [
    {
      "id": "f112de7b-c7df-4193-bacd-2d43c31c1f11",
      "title": "Add status filter to list_opportunities",
      "description": "Cannot filter opportunities by status (won/lost/open).",
      "status": "pending",
      "similarity": 0.8621,
      "created_at": "2026-04-19T05:08:56.498025+00:00"
    }
  ],
  "meta": { "credits_remaining": 3456 }
}`,
    },
    {
      method: 'POST',
      path: '/service-requests/:request_id/notes',
      toolName: 'add_service_request_note',
      description: 'Add a note to a service request.',
      scopes: ['service-requests:write'],
      isWrite: true,
      params: [
        { name: 'request_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'content', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/service-requests/:request_id/notes" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"content":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/service-requests/:request_id/notes/:note_id',
      toolName: 'update_service_request_note',
      description: 'Update a note on a service request.',
      scopes: ['service-requests:write'],
      isWrite: true,
      params: [
        { name: 'request_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'note_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'content', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/service-requests/:request_id/notes/:note_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"content":"..."}'`,
    },
    {
      method: 'POST',
      path: '/service-requests/:request_id/links',
      toolName: 'link_service_requests',
      description: 'Link service requests to each other.',
      scopes: ['service-requests:write'],
      isWrite: true,
      params: [
        { name: 'request_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'linked_request_ids', type: 'array', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/service-requests/:request_id/links" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"linked_request_ids":"..."}'`,
    },
  ],
};
