// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/signing.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/signing.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const SIGNING: ResourceGroup = {
  id: 'signing',
  label: 'Signing',
  description: 'Manage e-signature envelopes. Send documents for signing and track completion status.',
  endpoints: [
    {
      method: 'GET',
      path: '/signing/envelopes',
      toolName: 'list_signing_envelopes',
      description: 'List e-signing envelopes (documents sent for signature).',
      scopes: ['documents:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
        { name: 'after', type: 'string', required: false, description: '', in: 'query' },
        { name: 'status', type: 'string', required: false, description: '', in: 'query' },
        { name: 'deal_id', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/signing/envelopes" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/signing/send',
      toolName: 'send_for_signing',
      description: 'Send a document for e-signature. Requires template, signers, and a deal_id. Costs credits.',
      scopes: ['signing:send'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'signers', type: 'array', required: true, description: '', in: 'body' },
        { name: 'deal_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'subject', type: 'string', required: false, description: '', in: 'body' },
        { name: 'message', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/signing/send" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"template_id":"...","signers":"...","deal_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/signing/envelopes/:envelope_id',
      toolName: 'get_signing_envelope',
      description: 'Fetch a signing envelope by UUID — signer status, document state, audit trail.',
      scopes: ['documents:read'],
      isWrite: false,
      params: [
        { name: 'envelope_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/signing/envelopes/:envelope_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/signing/envelopes/:envelope_id/void',
      toolName: 'void_signing_envelope',
      description: 'Void a sent envelope (cancel the signing request).',
      scopes: ['signing:send'],
      isWrite: true,
      params: [
        { name: 'envelope_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'reason', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/signing/envelopes/:envelope_id/void" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"reason":"..."}'`,
    },
    {
      method: 'POST',
      path: '/signing/envelopes/:envelope_id/resend',
      toolName: 'resend_signing_envelope',
      description: 'Resend a signing envelope (re-deliver the request to pending signers).',
      scopes: ['signing:send'],
      isWrite: true,
      params: [
        { name: 'envelope_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/signing/envelopes/:envelope_id/resend" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
