// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/sms.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/sms.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const SMS: ResourceGroup = {
  id: 'sms',
  label: 'SMS',
  description: 'Send and receive SMS messages. View conversations and message history.',
  endpoints: [
    {
      method: 'GET',
      path: '/sms/conversations',
      toolName: 'list_sms_conversations',
      description: 'List SMS conversations in the workspace inbox. Supports filtering by contact_id, customer_id, and unread status.',
      scopes: ['sms:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
        { name: 'after', type: 'string', required: false, description: '', in: 'query' },
        { name: 'contact_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'customer_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'unread', type: 'boolean', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/sms/conversations" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/sms/conversations/mark-read',
      toolName: 'bulk_mark_sms_conversations_read',
      description: 'Mark multiple SMS conversations as read at once.',
      scopes: ['sms:write'],
      isWrite: true,
      params: [
        { name: 'conversation_ids', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/sms/conversations/mark-read" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"conversation_ids":"..."}'`,
    },
    {
      method: 'GET',
      path: '/sms/conversations/:conversation_id',
      toolName: 'get_sms_conversation',
      description: 'Fetch a single SMS conversation by UUID, including the full message history.',
      scopes: ['sms:read'],
      isWrite: false,
      params: [
        { name: 'conversation_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/sms/conversations/:conversation_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/sms/conversations/:conversation_id',
      toolName: 'update_sms_conversation',
      description: 'Update an SMS conversation (e.g. mark read, archive).',
      scopes: ['sms:write'],
      isWrite: true,
      params: [
        { name: 'conversation_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'is_read', type: 'boolean', required: false, description: '', in: 'body' },
        { name: 'is_archived', type: 'boolean', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/sms/conversations/:conversation_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"is_read":"...","is_archived":"..."}'`,
    },
    {
      method: 'GET',
      path: '/sms/conversations/:conversation_id/messages',
      toolName: 'get_sms_messages',
      description: 'List all messages in an SMS conversation in chronological order.',
      scopes: ['sms:read'],
      isWrite: false,
      params: [
        { name: 'conversation_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/sms/conversations/:conversation_id/messages" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/sms/send',
      toolName: 'send_sms',
      description: 'Send an SMS message from a workspace phone number. `phone_number_id` is OPTIONAL — when omitted, auto-resolves to the workspace\'s single active SMS-capable phone number (the common case). Only pass `phone_number_id` if the workspace has multiple SMS numbers and you need to choose one; in that case call `list_phone_numbers` first and never invent a UUID. Keep under 160 chars where possible. Costs credits.',
      scopes: ['sms:send'],
      isWrite: true,
      params: [
        { name: 'to_number', type: 'string', required: true, description: 'Recipient phone in E.164, e.g. +61431377068', in: 'body' },
        { name: 'message', type: 'string', required: true, description: 'SMS body. Keep concise — ideally under 160 chars.', in: 'body' },
        { name: 'phone_number_id', type: 'string', required: false, description: 'OPTIONAL. UUID of the workspace phone number to send from. Omit to auto-pick the single active SMS-capable number. If the workspace has multiple SMS numbers, call list_phone_numbers first.', in: 'body' },
        { name: 'contact_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'deal_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/sms/send" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"to_number":"...","message":"...","phone_number_id":"..."}'`,
      responseExample: `// Normal send
{
  "data": {
    "id": "msg-uuid-...",
    "status": "sent",
    "to_number": "+61412345678",
    "message": "Hello from TrustPager"
  },
  "meta": { "credits_remaining": 9490 }
}

// Suppressed send (contact has sms_unsubscribed: true)
{
  "data": {
    "status": "suppressed",
    "suppressed": true,
    "contact_id": "contact-uuid-...",
    "reason": "sms_unsubscribed"
  },
  "meta": { "credits_remaining": 9490 }
}`,
    },
  ],
};
