// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/spreadsheets.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/spreadsheets.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const SPREADSHEETS: ResourceGroup = {
  id: 'spreadsheets',
  label: 'Spreadsheets',
  description: 'Manage spreadsheet templates (column definitions) and populated spreadsheets (row data). Spreadsheets can be linked to opportunities and are also created automatically when a form with a spreadsheet field is submitted. Scopes: spreadsheets:read, spreadsheets:write, spreadsheets:delete.',
  endpoints: [
    {
      method: 'GET',
      path: '/spreadsheets/templates',
      toolName: 'list_spreadsheet_templates',
      description: 'List spreadsheet templates (column structures).',
      scopes: ['spreadsheets:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/spreadsheets/templates" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/spreadsheets/templates',
      toolName: 'create_spreadsheet_template',
      description: 'Create a spreadsheet template.',
      scopes: ['spreadsheets:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'columns', type: 'array', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/spreadsheets/templates" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","columns":"..."}'`,
    },
    {
      method: 'GET',
      path: '/spreadsheets/templates/:template_id',
      toolName: 'get_spreadsheet_template',
      description: 'Fetch a spreadsheet template by UUID.',
      scopes: ['spreadsheets:read'],
      isWrite: false,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/spreadsheets/templates/:template_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/spreadsheets/templates/:template_id',
      toolName: 'update_spreadsheet_template',
      description: 'Update a spreadsheet template.',
      scopes: ['spreadsheets:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/spreadsheets/templates/:template_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/spreadsheets/templates/:template_id',
      toolName: 'delete_spreadsheet_template',
      description: 'Delete a spreadsheet template.',
      scopes: ['spreadsheets:delete'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/spreadsheets/templates/:template_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/spreadsheets',
      toolName: 'list_spreadsheets',
      description: 'List spreadsheets in the workspace.',
      scopes: ['spreadsheets:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/spreadsheets" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/spreadsheets',
      toolName: 'create_spreadsheet',
      description: 'Create a spreadsheet from a template.',
      scopes: ['spreadsheets:write'],
      isWrite: true,
      params: [
        { name: 'template_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/spreadsheets" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"template_id":"...","name":"..."}'`,
    },
    {
      method: 'GET',
      path: '/spreadsheets/:spreadsheet_id',
      toolName: 'get_spreadsheet',
      description: 'Fetch a spreadsheet by UUID.',
      scopes: ['spreadsheets:read'],
      isWrite: false,
      params: [
        { name: 'spreadsheet_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/spreadsheets/:spreadsheet_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/spreadsheets/:spreadsheet_id',
      toolName: 'update_spreadsheet',
      description: 'Update a spreadsheet.',
      scopes: ['spreadsheets:write'],
      isWrite: true,
      params: [
        { name: 'spreadsheet_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/spreadsheets/:spreadsheet_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/spreadsheets/:spreadsheet_id',
      toolName: 'delete_spreadsheet',
      description: 'Delete a spreadsheet.',
      scopes: ['spreadsheets:delete'],
      isWrite: true,
      params: [
        { name: 'spreadsheet_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/spreadsheets/:spreadsheet_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/spreadsheets/:spreadsheet_id/rows',
      toolName: 'list_spreadsheet_rows',
      description: 'List rows in a spreadsheet.',
      scopes: ['spreadsheets:read'],
      isWrite: false,
      params: [
        { name: 'spreadsheet_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/spreadsheets/:spreadsheet_id/rows" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/spreadsheets/:spreadsheet_id/rows',
      toolName: 'append_spreadsheet_row',
      description: 'Append a row to a spreadsheet.',
      scopes: ['spreadsheets:write'],
      isWrite: true,
      params: [
        { name: 'spreadsheet_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'cells', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/spreadsheets/:spreadsheet_id/rows" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"cells":"..."}'`,
    },
    {
      method: 'POST',
      path: '/spreadsheets/:spreadsheet_id/rows/bulk',
      toolName: 'bulk_append_spreadsheet_rows',
      description: 'Bulk-append rows.',
      scopes: ['spreadsheets:write'],
      isWrite: true,
      params: [
        { name: 'spreadsheet_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'rows', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/spreadsheets/:spreadsheet_id/rows/bulk" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"rows":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/spreadsheets/:spreadsheet_id/rows/:row_id',
      toolName: 'update_spreadsheet_row',
      description: 'Update a row.',
      scopes: ['spreadsheets:write'],
      isWrite: true,
      params: [
        { name: 'spreadsheet_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'row_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'cells', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/spreadsheets/:spreadsheet_id/rows/:row_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"cells":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/spreadsheets/:spreadsheet_id/rows/:row_id',
      toolName: 'delete_spreadsheet_row',
      description: 'Delete a row.',
      scopes: ['spreadsheets:delete'],
      isWrite: true,
      params: [
        { name: 'spreadsheet_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'row_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/spreadsheets/:spreadsheet_id/rows/:row_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/spreadsheets/:spreadsheet_id/import_from_document',
      toolName: 'import_spreadsheet_from_document',
      description: 'Extract rows from a PDF via a document mapper.',
      scopes: ['spreadsheets:write'],
      isWrite: true,
      params: [
        { name: 'spreadsheet_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'mapper_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'file_id', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/spreadsheets/:spreadsheet_id/import_from_document" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"mapper_id":"...","file_id":"..."}'`,
    },
  ],
};
