// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/tasks.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/tasks.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const TASKS: ResourceGroup = {
  id: 'tasks',
  label: 'Tasks',
  description: 'Create, assign, and manage tasks linked to deals and contacts.',
  endpoints: [
    {
      method: 'POST',
      path: '/tasks/reorder',
      toolName: 'reorder_tasks',
      description: 'Reorder a set of tasks. Pass task_ids array in desired display order; sort_order is reassigned from the array index.',
      scopes: ['tasks:write'],
      isWrite: true,
      params: [
        { name: 'task_ids', type: 'array', required: true, description: 'Task UUIDs in new display order', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/tasks/reorder" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"task_ids":"..."}'`,
    },
    {
      method: 'GET',
      path: '/tasks/categories',
      toolName: 'list_task_categories',
      description: 'List task categories defined in the workspace. Use this to find a category UUID for assigning to a task.',
      scopes: ['tasks:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/tasks/categories" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/tasks/categories',
      toolName: 'create_task_category',
      description: 'Create a new task category in the workspace.',
      scopes: ['tasks:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: 'Category name', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/tasks/categories" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/tasks/categories/:category_id',
      toolName: 'update_task_category',
      description: 'Rename a task category.',
      scopes: ['tasks:write'],
      isWrite: true,
      params: [
        { name: 'category_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/tasks/categories/:category_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/tasks/categories/:category_id',
      toolName: 'delete_task_category',
      description: 'Delete a task category by UUID. Destructive.',
      scopes: ['tasks:delete'],
      isWrite: true,
      params: [
        { name: 'category_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/tasks/categories/:category_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/tasks',
      toolName: 'list_tasks',
      description: 'List tasks in the workspace. Supports filtering by status, assigned_to, priority, category, deal_id, contact_id, customer_id.',
      scopes: ['tasks:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: 'Max number of tasks to return (1-100, default 25)', in: 'query' },
        { name: 'after', type: 'string', required: false, description: 'Pagination cursor', in: 'query' },
        { name: 'status', type: 'string', required: false, description: 'Filter by status', in: 'query' },
        { name: 'assigned_to', type: 'string', required: false, description: 'UUID of the assignee', in: 'query' },
        { name: 'priority', type: 'string', required: false, description: 'Filter by priority', in: 'query' },
        { name: 'category', type: 'string', required: false, description: 'Filter by category', in: 'query' },
        { name: 'deal_id', type: 'string', required: false, description: 'Filter to a specific opportunity', in: 'query' },
        { name: 'contact_id', type: 'string', required: false, description: 'Filter to a specific contact', in: 'query' },
        { name: 'customer_id', type: 'string', required: false, description: 'Filter to a specific company', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/tasks" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/tasks',
      toolName: 'create_task',
      description: 'Create a new task. Requires title. The task modal has two text fields: "Summary" (short one-liner — maps to the `description` field) and "Detailed Description" (long-form notes — maps to the `body` field). Use the right one for the length of content. Link to records via deal_id / contact_id / customer_id.',
      scopes: ['tasks:write'],
      isWrite: true,
      params: [
        { name: 'title', type: 'string', required: true, description: 'Title (required). Matches the "Title" field on the task modal.', in: 'body' },
        { name: 'description', type: 'string', required: false, description: 'Summary — short one-line summary (target under ~200 chars). Matches the "Summary" field on the task modal. For multi-paragraph content use `body` instead.', in: 'body' },
        { name: 'body', type: 'string', required: false, description: 'Detailed Description — long-form notes, acceptance criteria, multi-paragraph content. Matches the "Detailed Description" field on the task modal.', in: 'body' },
        { name: 'due_date', type: 'string', required: false, description: 'ISO date (YYYY-MM-DD) when the task is due', in: 'body' },
        { name: 'due_time', type: 'string', required: false, description: 'Time of day (HH:MM) when the task is due', in: 'body' },
        { name: 'assigned_to', type: 'string', required: false, description: 'UUID of the user to assign', in: 'body' },
        { name: 'category', type: 'string', required: false, description: 'Category name', in: 'body' },
        { name: 'priority', type: 'string', required: false, description: 'low, medium, or high', in: 'body' },
        { name: 'deal_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'contact_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'customer_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/tasks" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"title":"...","description":"...","body":"..."}'`,
    },
    {
      method: 'GET',
      path: '/tasks/:task_id',
      toolName: 'get_task',
      description: 'Fetch a single task by UUID. Returns the full task record.',
      scopes: ['tasks:read'],
      isWrite: false,
      params: [
        { name: 'task_id', type: 'string', required: true, description: 'UUID of the task', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/tasks/:task_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/tasks/:task_id',
      toolName: 'update_task',
      description: 'Update a task. Set status to "completed" to mark complete. Pass only fields you want to change. Note: the task modal has two text fields — "Summary" (maps to `description`) and "Detailed Description" (maps to `body`). Pick the right one for the length of content.',
      scopes: ['tasks:write'],
      isWrite: true,
      params: [
        { name: 'task_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'title', type: 'string', required: false, description: 'Title. Matches the "Title" field on the task modal.', in: 'body' },
        { name: 'description', type: 'string', required: false, description: 'Summary — short one-line summary (target under ~200 chars). Matches the "Summary" field on the task modal. For multi-paragraph content use `body` instead.', in: 'body' },
        { name: 'body', type: 'string', required: false, description: 'Detailed Description — long-form notes, acceptance criteria, multi-paragraph content. Matches the "Detailed Description" field on the task modal.', in: 'body' },
        { name: 'due_date', type: 'string', required: false, description: '', in: 'body' },
        { name: 'due_time', type: 'string', required: false, description: '', in: 'body' },
        { name: 'assigned_to', type: 'string', required: false, description: '', in: 'body' },
        { name: 'status', type: 'string', required: false, description: 'pending, in_progress, or completed', in: 'body' },
        { name: 'priority', type: 'string', required: false, description: '', in: 'body' },
        { name: 'category', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/tasks/:task_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"title":"...","description":"...","body":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/tasks/:task_id',
      toolName: 'delete_task',
      description: 'Delete a task by UUID. Destructive.',
      scopes: ['tasks:delete'],
      isWrite: true,
      params: [
        { name: 'task_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/tasks/:task_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
