import { type ResourceGroup } from './types.js';

// =============================================================================
// TEXT AGENTS -- now served by unified /agents endpoint
// This file retained for backward compatibility in the docs index.
// The actual endpoint is /agents?type=text (see voice-agents.ts for full docs).
// =============================================================================

export const TEXT_AGENTS: ResourceGroup = {
  id: 'text-agents',
  label: 'Text Agents',
  description: 'Text agents are now part of the unified /agents endpoint. Use GET /agents?type=text to list text agents. See the Agents resource group for full documentation.',
  endpoints: [
    { method: 'GET', path: '/agents?type=text', description: 'List all text agents. Use the unified /agents endpoint with type=text.', scopes: ['voice-agents:read'], isWrite: false },
    { method: 'GET', path: '/agents/:id', description: 'Retrieve a text agent. Auto-detects type.', scopes: ['voice-agents:read'], isWrite: false, params: [{ name: 'id', type: 'uuid', required: true, description: 'Text agent ID', in: 'path' }] },
    { method: 'POST', path: '/agents', description: 'Create a text agent. Include "type": "text" and "name" in the request body.', scopes: ['voice-agents:write'], isWrite: true, params: [{ name: 'type', type: 'string', required: true, description: 'Must be "text"', in: 'body' }, { name: 'name', type: 'string', required: true, description: 'Agent name', in: 'body' }] },
    { method: 'PATCH', path: '/agents/:id', description: 'Update a text agent. Auto-detects type.', scopes: ['voice-agents:write'], isWrite: true, params: [{ name: 'id', type: 'uuid', required: true, description: 'Text agent ID', in: 'path' }] },
    { method: 'DELETE', path: '/agents/:id', description: 'Delete a text agent. Auto-detects type.', scopes: ['voice-agents:write'], isWrite: true, params: [{ name: 'id', type: 'uuid', required: true, description: 'Text agent ID', in: 'path' }] },
    { method: 'GET', path: '/agents/:id/responses', description: 'List responses generated by a text agent.', scopes: ['voice-agents:read'], isWrite: false, params: [{ name: 'id', type: 'uuid', required: true, description: 'Text agent ID', in: 'path' }] },
  ],
};
