import { type ResourceGroup } from './types.js';

// =============================================================================
// TEXT AGENTS
// =============================================================================

export const TEXT_AGENTS: ResourceGroup = {
  id: 'text-agents',
  label: 'Text Agents',
  description: 'Manage AI text agents that handle SMS and chat conversations.',
  endpoints: [
    { method: 'GET', path: '/text-agents', description: 'List all text agents.', scopes: ['voice-agents:read'], isWrite: false },
    { method: 'GET', path: '/text-agents/:id', description: 'Retrieve a text agent.', scopes: ['voice-agents:read'], isWrite: false, params: [{ name: 'id', type: 'uuid', required: true, description: 'Text agent ID', in: 'path' }] },
    { method: 'POST', path: '/text-agents', description: 'Create a text agent.', scopes: ['voice-agents:write'], isWrite: true, params: [{ name: 'name', type: 'string', required: true, description: 'Agent name', in: 'body' }] },
    { method: 'PATCH', path: '/text-agents/:id', description: 'Update a text agent.', scopes: ['voice-agents:write'], isWrite: true, params: [{ name: 'id', type: 'uuid', required: true, description: 'Text agent ID', in: 'path' }] },
    { method: 'DELETE', path: '/text-agents/:id', description: 'Delete a text agent.', scopes: ['voice-agents:write'], isWrite: true, params: [{ name: 'id', type: 'uuid', required: true, description: 'Text agent ID', in: 'path' }] },
    { method: 'GET', path: '/text-agents/:id/responses', description: 'List responses generated by a text agent.', scopes: ['voice-agents:read'], isWrite: false, params: [{ name: 'id', type: 'uuid', required: true, description: 'Text agent ID', in: 'path' }] },
  ],
};
