// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/training.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/training.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const TRAINING: ResourceGroup = {
  id: 'training',
  label: 'Learning Hub',
  description: 'Manage Learning Hub canvases and their cards. Canvases are drag-and-drop boards of cards that can embed YouTube videos, external links, iframes, notepads, PDFs, images, and secure files.',
  endpoints: [
    {
      method: 'GET',
      path: '/training-canvases',
      toolName: 'list_training_canvases',
      description: 'List training canvases in the workspace. Free read.',
      scopes: ['resources:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/training-canvases" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/training-canvases',
      toolName: 'create_training_canvas',
      description: 'Create a new training canvas.',
      scopes: ['resources:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'template', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/training-canvases" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","template":"..."}'`,
    },
    {
      method: 'GET',
      path: '/training-canvases/:canvas_id',
      toolName: 'get_training_canvas',
      description: 'Fetch a training canvas by UUID with its cards.',
      scopes: ['resources:read'],
      isWrite: false,
      params: [
        { name: 'canvas_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/training-canvases/:canvas_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/training-canvases/:canvas_id',
      toolName: 'update_training_canvas',
      description: 'Update a training canvas.',
      scopes: ['resources:write'],
      isWrite: true,
      params: [
        { name: 'canvas_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'name', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/training-canvases/:canvas_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/training-canvases/:canvas_id',
      toolName: 'delete_training_canvas',
      description: 'Delete a training canvas by UUID.',
      scopes: ['resources:delete'],
      isWrite: true,
      params: [
        { name: 'canvas_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/training-canvases/:canvas_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/training-canvases/:canvas_id/cards',
      toolName: 'add_training_card',
      description: 'Add a card to a training canvas.',
      scopes: ['resources:write'],
      isWrite: true,
      params: [
        { name: 'canvas_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'title', type: 'string', required: false, description: '', in: 'body' },
        { name: 'content', type: 'string', required: false, description: '', in: 'body' },
        { name: 'position', type: 'number', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/training-canvases/:canvas_id/cards" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"title":"...","content":"...","position":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/training-cards/:card_id',
      toolName: 'update_training_card',
      description: 'Update a training card.',
      scopes: ['resources:write'],
      isWrite: true,
      params: [
        { name: 'card_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'title', type: 'string', required: false, description: '', in: 'body' },
        { name: 'content', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/training-cards/:card_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"title":"...","content":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/training-cards/:card_id',
      toolName: 'delete_training_card',
      description: 'Delete a training card.',
      scopes: ['resources:delete'],
      isWrite: true,
      params: [
        { name: 'card_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/training-cards/:card_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
