// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/voice-agents.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/voice-agents.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const VOICE_AGENTS: ResourceGroup = {
  id: 'voice-agents',
  label: 'Agents',
  description: 'Manage AI voice agents and text agents under the unified /agents endpoint. Use ?type=voice or ?type=text to filter listings. The type field is required in the create body.',
  endpoints: [
    {
      method: 'GET',
      path: '/voice-agents/calls/:call_id|str',
      toolName: 'get_voice_agent_call',
      description: 'Fetch a voice-agent call by id (UUID or Retell call_id).',
      scopes: ['calls:read'],
      isWrite: false,
      params: [
        { name: 'call_id', type: 'string', required: true, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/voice-agents/calls/:call_id|str" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/voice-agents/calls/:call_id|str/recording',
      toolName: 'get_voice_agent_call_recording',
      description: 'Get signed playback URL for a voice-agent call recording.',
      scopes: ['calls:read'],
      isWrite: false,
      params: [
        { name: 'call_id', type: 'string', required: true, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/voice-agents/calls/:call_id|str/recording" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/voice-agents/calls/:call_id|str/recording/rehost',
      toolName: 'rehost_voice_agent_call_recording',
      description: 'Re-host a voice-agent call recording into private storage.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'call_id', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/voice-agents/calls/:call_id|str/recording/rehost" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"call_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/voice-agents',
      toolName: 'list_voice_agents',
      description: 'List voice agents in the workspace.',
      scopes: ['voice-agents:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/voice-agents" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/voice-agents',
      toolName: 'create_voice_agent',
      description: 'Create a voice agent.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'agent_name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'voice_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/voice-agents" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"agent_name":"...","voice_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/voice-agents/:agent_id',
      toolName: 'get_voice_agent',
      description: 'Fetch a voice agent by UUID.',
      scopes: ['voice-agents:read'],
      isWrite: false,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/voice-agents/:agent_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/voice-agents/:agent_id',
      toolName: 'update_voice_agent',
      description: 'Update a voice agent.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/voice-agents/:agent_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/voice-agents/:agent_id',
      toolName: 'delete_voice_agent',
      description: 'Delete a voice agent.',
      scopes: ['voice-agents:delete'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/voice-agents/:agent_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/voice-agents/:agent_id/sync',
      toolName: 'sync_voice_agent',
      description: 'Sync a voice agent config with the upstream provider.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/voice-agents/:agent_id/sync" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/voice-agents/:agent_id/call',
      toolName: 'initiate_voice_call',
      description: 'Initiate an outbound voice call via this agent.',
      scopes: ['calls:initiate'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'to_number', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/voice-agents/:agent_id/call" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"to_number":"..."}'`,
    },
    {
      method: 'GET',
      path: '/voice-agents/:agent_id/calls',
      toolName: 'list_voice_agent_calls',
      description: 'List calls handled by a voice agent.',
      scopes: ['calls:read'],
      isWrite: false,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/voice-agents/:agent_id/calls" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/voice-agents/:agent_id/update-flow',
      toolName: 'update_voice_agent_flow',
      description: 'Replace the voice-agent conversation flow.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'flow', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/voice-agents/:agent_id/update-flow" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"flow":"..."}'`,
    },
    {
      method: 'POST',
      path: '/voice-agents/:agent_id/patch-flow',
      toolName: 'patch_voice_agent_flow',
      description: 'Partial update to the voice-agent flow.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'patch', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/voice-agents/:agent_id/patch-flow" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"patch":"..."}'`,
    },
    {
      method: 'POST',
      path: '/voice-agents/:agent_id/update-settings',
      toolName: 'update_voice_agent_settings',
      description: 'Update voice-agent settings.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/voice-agents/:agent_id/update-settings" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/voice-agents/:agent_id/publish',
      toolName: 'publish_voice_agent',
      description: 'Publish a voice agent draft to live.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/voice-agents/:agent_id/publish" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/voice-agents/:agent_id/provision',
      toolName: 'provision_voice_agent',
      description: 'Provision a voice agent that was created as an orphan row.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/voice-agents/:agent_id/provision" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/voice-agents/:agent_id/apply-template',
      toolName: 'apply_voice_agent_template',
      description: 'Stamp a profile/source template onto a target voice agent.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'template_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/voice-agents/:agent_id/apply-template" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"template_id":"..."}'`,
    },
    {
      method: 'GET',
      path: '/voice-agents/:agent_id/website-config',
      toolName: 'list_voice_agent_website_configs',
      description: 'List website configs on a voice agent.',
      scopes: ['voice-agents:read'],
      isWrite: false,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/voice-agents/:agent_id/website-config" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/voice-agents/:agent_id/website-config',
      toolName: 'create_voice_agent_website_config',
      description: 'Bind a voice agent to a website.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'website_id', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/voice-agents/:agent_id/website-config" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"website_id":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/voice-agents/:agent_id/website-config/:config_id',
      toolName: 'update_voice_agent_website_config',
      description: 'Update a voice-agent website config.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'config_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/voice-agents/:agent_id/website-config/:config_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/voice-agents/:agent_id/website-config/:config_id',
      toolName: 'delete_voice_agent_website_config',
      description: 'Delete a voice-agent website config.',
      scopes: ['voice-agents:delete'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'config_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/voice-agents/:agent_id/website-config/:config_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/voice-agents/:agent_id/outbound-config',
      toolName: 'list_voice_agent_outbound_configs',
      description: 'List outbound-call configs on a voice agent.',
      scopes: ['voice-agents:read'],
      isWrite: false,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/voice-agents/:agent_id/outbound-config" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/voice-agents/:agent_id/outbound-config',
      toolName: 'create_voice_agent_outbound_config',
      description: 'Enable OUTBOUND dialling for a voice agent. Set default_phone_number_id to an imported number: that number becomes the caller ID and is all outbound needs (each call passes the agent itself, so no number-level binding is required and ONE number can be the default for many agents). Do NOT use update_phone_number to bind the number to the agent for outbound; that binding is inbound-only. Per-agent, no website required.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'default_phone_number_id', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/voice-agents/:agent_id/outbound-config" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"default_phone_number_id":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/voice-agents/:agent_id/outbound-config/:config_id',
      toolName: 'update_voice_agent_outbound_config',
      description: 'Update an outbound-call config.',
      scopes: ['voice-agents:write'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'config_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/voice-agents/:agent_id/outbound-config/:config_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/voice-agents/:agent_id/outbound-config/:config_id',
      toolName: 'delete_voice_agent_outbound_config',
      description: 'Delete an outbound-call config.',
      scopes: ['voice-agents:delete'],
      isWrite: true,
      params: [
        { name: 'agent_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'config_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/voice-agents/:agent_id/outbound-config/:config_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
