// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/webhooks.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/webhooks.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const WEBHOOKS: ResourceGroup = {
  id: 'webhooks',
  label: 'Webhooks',
  description: 'Manage incoming and outgoing webhooks for external system integration.',
  endpoints: [
    {
      method: 'GET',
      path: '/webhooks/outgoing',
      toolName: 'list_outgoing_webhooks',
      description: 'List outgoing webhook configs.',
      scopes: ['webhooks:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/webhooks/outgoing" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/webhooks/outgoing',
      toolName: 'create_outgoing_webhook',
      description: 'Create an outgoing webhook.',
      scopes: ['webhooks:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'url', type: 'string', required: true, description: '', in: 'body' },
        { name: 'events', type: 'array', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/webhooks/outgoing" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","url":"...","events":"..."}'`,
    },
    {
      method: 'GET',
      path: '/webhooks/outgoing/:webhook_id',
      toolName: 'get_outgoing_webhook',
      description: 'Fetch an outgoing webhook by UUID.',
      scopes: ['webhooks:read'],
      isWrite: false,
      params: [
        { name: 'webhook_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/webhooks/outgoing/:webhook_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/webhooks/outgoing/:webhook_id',
      toolName: 'update_outgoing_webhook',
      description: 'Update an outgoing webhook.',
      scopes: ['webhooks:write'],
      isWrite: true,
      params: [
        { name: 'webhook_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/webhooks/outgoing/:webhook_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/webhooks/outgoing/:webhook_id',
      toolName: 'delete_outgoing_webhook',
      description: 'Delete an outgoing webhook.',
      scopes: ['webhooks:delete'],
      isWrite: true,
      params: [
        { name: 'webhook_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/webhooks/outgoing/:webhook_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/webhooks/outgoing/:webhook_id/logs',
      toolName: 'get_outgoing_webhook_logs',
      description: 'List delivery logs for an outgoing webhook.',
      scopes: ['webhooks:read'],
      isWrite: false,
      params: [
        { name: 'webhook_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/webhooks/outgoing/:webhook_id/logs" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/webhooks/outgoing/:webhook_id/test',
      toolName: 'test_outgoing_webhook',
      description: 'Send a test payload to an outgoing webhook.',
      scopes: ['webhooks:write'],
      isWrite: true,
      params: [
        { name: 'webhook_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/webhooks/outgoing/:webhook_id/test" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/webhooks/incoming',
      toolName: 'list_incoming_webhooks',
      description: 'List incoming webhook URLs.',
      scopes: ['webhooks:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/webhooks/incoming" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/webhooks/incoming',
      toolName: 'create_incoming_webhook',
      description: 'Create an incoming webhook URL.',
      scopes: ['webhooks:write'],
      isWrite: true,
      params: [
        { name: 'service_type', type: 'string', required: true, description: '', in: 'body' },
        { name: 'service_name', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/webhooks/incoming" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"service_type":"...","service_name":"..."}'`,
    },
    {
      method: 'GET',
      path: '/webhooks/incoming/:webhook_id',
      toolName: 'get_incoming_webhook',
      description: 'Fetch an incoming webhook config.',
      scopes: ['webhooks:read'],
      isWrite: false,
      params: [
        { name: 'webhook_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/webhooks/incoming/:webhook_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/webhooks/incoming/:webhook_id',
      toolName: 'update_incoming_webhook',
      description: 'Update an incoming webhook.',
      scopes: ['webhooks:write'],
      isWrite: true,
      params: [
        { name: 'webhook_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/webhooks/incoming/:webhook_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/webhooks/incoming/:webhook_id',
      toolName: 'delete_incoming_webhook',
      description: 'Delete an incoming webhook.',
      scopes: ['webhooks:delete'],
      isWrite: true,
      params: [
        { name: 'webhook_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/webhooks/incoming/:webhook_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/webhooks/subscribe',
      toolName: 'create_webhook_subscription',
      description: 'Subscribe a URL to API event notifications.',
      scopes: ['webhooks:write'],
      isWrite: true,
      params: [
        { name: 'url', type: 'string', required: true, description: '', in: 'body' },
        { name: 'events', type: 'array', required: true, description: '', in: 'body' },
        { name: 'secret', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/webhooks/subscribe" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"url":"...","events":"...","secret":"..."}'`,
    },
    {
      method: 'GET',
      path: '/webhooks/subscriptions',
      toolName: 'list_webhook_subscriptions',
      description: 'List webhook subscriptions.',
      scopes: ['webhooks:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/webhooks/subscriptions" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/webhooks/subscriptions/:subscription_id',
      toolName: 'update_webhook_subscription',
      description: 'Update a webhook subscription.',
      scopes: ['webhooks:write'],
      isWrite: true,
      params: [
        { name: 'subscription_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/webhooks/subscriptions/:subscription_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/webhooks/subscriptions/:subscription_id',
      toolName: 'delete_webhook_subscription',
      description: 'Delete a webhook subscription.',
      scopes: ['webhooks:delete'],
      isWrite: true,
      params: [
        { name: 'subscription_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/webhooks/subscriptions/:subscription_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/webhooks/subscriptions/:subscription_id/logs',
      toolName: 'list_webhook_subscription_logs',
      description: 'List delivery logs for a webhook subscription.',
      scopes: ['webhooks:read'],
      isWrite: false,
      params: [
        { name: 'subscription_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/webhooks/subscriptions/:subscription_id/logs" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
