// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/websites.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/websites.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const WEBSITES: ResourceGroup = {
  id: 'websites',
  label: 'Websites',
  description: 'Manage TrustPager-hosted websites, pages, and page sections.',
  endpoints: [
    {
      method: 'GET',
      path: '/websites',
      toolName: 'list_websites',
      description: 'List workspace websites.',
      scopes: ['websites:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/websites" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/websites',
      toolName: 'create_website',
      description: 'Create a new website. Registers the site record (site_key, domain, branding) used by public-form embeds and the website lead gateway.',
      scopes: ['websites:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'domain', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/websites" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","domain":"..."}'`,
    },
    {
      method: 'GET',
      path: '/websites/:website_id',
      toolName: 'get_website',
      description: 'Fetch a website by UUID — including site_key, domain, branding, navbar, footer, and SEO configuration.',
      scopes: ['websites:read'],
      isWrite: false,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/websites/:website_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/websites/:website_id',
      toolName: 'update_website',
      description: 'Update a website — name, domain, branding, navbar, footer, SEO meta tags, lead gen form, or custom scripts.',
      scopes: ['websites:write'],
      isWrite: true,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/websites/:website_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/websites/:website_id',
      toolName: 'delete_website',
      description: 'Delete a website and its associated content. This action cannot be undone.',
      scopes: ['websites:delete'],
      isWrite: true,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/websites/:website_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
