// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/websites.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/websites.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const WEBSITES: ResourceGroup = {
  id: 'websites',
  label: 'Websites',
  description: 'Manage TrustPager-hosted websites, pages, and page sections.',
  endpoints: [
    {
      method: 'GET',
      path: '/websites',
      toolName: 'list_websites',
      description: 'List workspace websites.',
      scopes: ['websites:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/websites" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/websites',
      toolName: 'create_website',
      description: 'Create a new website.',
      scopes: ['websites:write'],
      isWrite: true,
      params: [
        { name: 'name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'domain', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/websites" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"name":"...","domain":"..."}'`,
    },
    {
      method: 'GET',
      path: '/websites/:website_id',
      toolName: 'get_website',
      description: 'Fetch a website by UUID.',
      scopes: ['websites:read'],
      isWrite: false,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/websites/:website_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/websites/:website_id',
      toolName: 'update_website',
      description: 'Update a website.',
      scopes: ['websites:write'],
      isWrite: true,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/websites/:website_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/websites/:website_id',
      toolName: 'delete_website',
      description: 'Delete a website.',
      scopes: ['websites:delete'],
      isWrite: true,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/websites/:website_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/websites/:website_id/pages',
      toolName: 'list_website_pages',
      description: 'List pages on a website.',
      scopes: ['websites:read'],
      isWrite: false,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/websites/:website_id/pages" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/websites/:website_id/pages',
      toolName: 'create_website_page',
      description: 'Add a page to a website.',
      scopes: ['websites:write'],
      isWrite: true,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'title', type: 'string', required: true, description: '', in: 'body' },
        { name: 'slug', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/websites/:website_id/pages" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"title":"...","slug":"..."}'`,
    },
    {
      method: 'GET',
      path: '/websites/:website_id/pages/:page_id',
      toolName: 'get_website_page',
      description: 'Fetch a website page by UUID.',
      scopes: ['websites:read'],
      isWrite: false,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'page_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/websites/:website_id/pages/:page_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/websites/:website_id/pages/:page_id',
      toolName: 'update_website_page',
      description: 'Update a website page.',
      scopes: ['websites:write'],
      isWrite: true,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'page_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/websites/:website_id/pages/:page_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/websites/:website_id/pages/:page_id',
      toolName: 'delete_website_page',
      description: 'Delete a website page.',
      scopes: ['websites:delete'],
      isWrite: true,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'page_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/websites/:website_id/pages/:page_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/websites/:website_id/pages/:page_id/sections',
      toolName: 'list_website_page_sections',
      description: 'List sections on a website page.',
      scopes: ['websites:read'],
      isWrite: false,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'page_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/websites/:website_id/pages/:page_id/sections" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/websites/:website_id/pages/:page_id/sections',
      toolName: 'create_website_page_section',
      description: 'Add a section to a website page.',
      scopes: ['websites:write'],
      isWrite: true,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'page_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'type', type: 'string', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/websites/:website_id/pages/:page_id/sections" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"type":"..."}'`,
    },
    {
      method: 'POST',
      path: '/websites/:website_id/pages/:page_id/sections/reorder',
      toolName: 'reorder_website_page_sections',
      description: 'Reorder sections on a website page.',
      scopes: ['websites:write'],
      isWrite: true,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'page_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'section_ids', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/websites/:website_id/pages/:page_id/sections/reorder" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"section_ids":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/websites/:website_id/pages/:page_id/sections/:section_id',
      toolName: 'update_website_page_section',
      description: 'Update a section.',
      scopes: ['websites:write'],
      isWrite: true,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'page_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'section_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/websites/:website_id/pages/:page_id/sections/:section_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/websites/:website_id/pages/:page_id/sections/:section_id',
      toolName: 'delete_website_page_section',
      description: 'Delete a section.',
      scopes: ['websites:delete'],
      isWrite: true,
      params: [
        { name: 'website_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'page_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'section_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/websites/:website_id/pages/:page_id/sections/:section_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
