// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/work-orders.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/work-orders.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const WORK_ORDERS: ResourceGroup = {
  id: 'work-orders',
  label: 'Work Orders',
  description: 'Manage work orders linked to deals for tracking project execution. Work orders appear on the CRM Calendar, support team assignment, and scheduled dates.',
  endpoints: [
    {
      method: 'GET',
      path: '/work-orders',
      toolName: 'list_work_orders',
      description: 'List work orders attached to deal products.',
      scopes: ['work-orders:read'],
      isWrite: false,
      params: [
        { name: 'limit', type: 'number', required: false, description: '', in: 'query' },
        { name: 'deal_id', type: 'string', required: false, description: '', in: 'query' },
        { name: 'status_id', type: 'string', required: false, description: '', in: 'query' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/work-orders" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/work-orders',
      toolName: 'create_work_order',
      description: 'Create a work order attached to a deal product.',
      scopes: ['work-orders:write'],
      isWrite: true,
      params: [
        { name: 'deal_product_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'status_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'notes', type: 'string', required: false, description: '', in: 'body' },
        { name: 'fields', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/work-orders" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"deal_product_id":"...","status_id":"...","notes":"..."}'`,
    },
    {
      method: 'POST',
      path: '/work-orders/send-work-status',
      toolName: 'send_work_status',
      description: 'Send a work-status update email to a contact for an opportunity. Costs credits.',
      scopes: ['work-orders:write'],
      isWrite: true,
      params: [
        { name: 'deal_id', type: 'string', required: true, description: '', in: 'body' },
        { name: 'recipient_email', type: 'string', required: true, description: '', in: 'body' },
        { name: 'recipient_name', type: 'string', required: true, description: '', in: 'body' },
        { name: 'custom_message', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/work-orders/send-work-status" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"deal_id":"...","recipient_email":"...","recipient_name":"..."}'`,
    },
    {
      method: 'GET',
      path: '/work-orders/:work_order_id',
      toolName: 'get_work_order',
      description: 'Fetch a single work order by UUID.',
      scopes: ['work-orders:read'],
      isWrite: false,
      params: [
        { name: 'work_order_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl \
  "${API_BASE_URL}/work-orders/:work_order_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'PATCH',
      path: '/work-orders/:work_order_id',
      toolName: 'update_work_order',
      description: 'Update a work order (status, notes, fields).',
      scopes: ['work-orders:write'],
      isWrite: true,
      params: [
        { name: 'work_order_id', type: 'string', required: true, description: '', in: 'path' },
        { name: 'status_id', type: 'string', required: false, description: '', in: 'body' },
        { name: 'notes', type: 'string', required: false, description: '', in: 'body' },
        { name: 'fields', type: 'object', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/work-orders/:work_order_id" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"status_id":"...","notes":"...","fields":"..."}'`,
    },
    {
      method: 'DELETE',
      path: '/work-orders/:work_order_id',
      toolName: 'delete_work_order',
      description: 'Delete a work order by UUID.',
      scopes: ['work-orders:delete'],
      isWrite: true,
      params: [
        { name: 'work_order_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/work-orders/:work_order_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
