// AUTOGENERATED by scripts/sync-from-api.ts — DO NOT EDIT BY HAND.
// Source of truth: ../../../TrustPager-Portal/supabase/functions/api/routes/work-order-config.ts
// To regenerate after API changes: npm run sync:api
// Hand-curated examples live in scripts/api-sync-examples/work-order-config.json

import { type ResourceGroup, API_BASE_URL } from './types.js';

export const WORK_ORDER_CONFIG: ResourceGroup = {
  id: 'work-order-config',
  label: 'WORK_ORDER_CONFIG',
  description: 'work-order-config endpoints.',
  endpoints: [
    {
      method: 'GET',
      path: '/work-order-statuses',
      toolName: 'list_work_order_statuses',
      description: 'List workspace work-order statuses.',
      scopes: ['work-orders:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/work-order-statuses" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/work-order-statuses',
      toolName: 'create_work_order_status',
      description: 'Create a work-order status.',
      scopes: ['work-orders:write'],
      isWrite: true,
      params: [
        { name: 'label', type: 'string', required: true, description: '', in: 'body' },
        { name: 'color', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/work-order-statuses" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"label":"...","color":"..."}'`,
    },
    {
      method: 'POST',
      path: '/work-order-statuses/reorder',
      toolName: 'reorder_work_order_statuses',
      description: 'Reorder work-order statuses.',
      scopes: ['work-orders:write'],
      isWrite: true,
      params: [
        { name: 'ids', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/work-order-statuses/reorder" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"ids":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/work-order-statuses/:status_id',
      toolName: 'update_work_order_status',
      description: 'Update a work-order status.',
      scopes: ['work-orders:write'],
      isWrite: true,
      params: [
        { name: 'status_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/work-order-statuses/:status_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/work-order-statuses/:status_id',
      toolName: 'delete_work_order_status',
      description: 'Delete a work-order status.',
      scopes: ['work-orders:delete'],
      isWrite: true,
      params: [
        { name: 'status_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/work-order-statuses/:status_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'GET',
      path: '/work-order-fields',
      toolName: 'list_work_order_fields',
      description: 'List workspace work-order custom fields.',
      scopes: ['work-orders:read'],
      isWrite: false,
      requestExample: `curl \
  "${API_BASE_URL}/work-order-fields" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'POST',
      path: '/work-order-fields',
      toolName: 'create_work_order_field',
      description: 'Add a work-order custom field.',
      scopes: ['work-orders:write'],
      isWrite: true,
      params: [
        { name: 'label', type: 'string', required: true, description: '', in: 'body' },
        { name: 'type', type: 'string', required: false, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/work-order-fields" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"label":"...","type":"..."}'`,
    },
    {
      method: 'POST',
      path: '/work-order-fields/reorder',
      toolName: 'reorder_work_order_fields',
      description: 'Reorder work-order fields.',
      scopes: ['work-orders:write'],
      isWrite: true,
      params: [
        { name: 'ids', type: 'array', required: true, description: '', in: 'body' },
      ],
      requestExample: `curl -X POST \
  "${API_BASE_URL}/work-order-fields/reorder" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"ids":"..."}'`,
    },
    {
      method: 'PATCH',
      path: '/work-order-fields/:field_id',
      toolName: 'update_work_order_field',
      description: 'Update a work-order field.',
      scopes: ['work-orders:write'],
      isWrite: true,
      params: [
        { name: 'field_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X PATCH \
  "${API_BASE_URL}/work-order-fields/:field_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
    {
      method: 'DELETE',
      path: '/work-order-fields/:field_id',
      toolName: 'delete_work_order_field',
      description: 'Delete a work-order field.',
      scopes: ['work-orders:delete'],
      isWrite: true,
      params: [
        { name: 'field_id', type: 'string', required: true, description: '', in: 'path' },
      ],
      requestExample: `curl -X DELETE \
  "${API_BASE_URL}/work-order-fields/:field_id" \
  -H "Authorization: Bearer YOUR_API_KEY"`,
    },
  ],
};
