/**
 * Backfill `toolName` field into hand-curated endpoint files that predate the parser.
 *
 * Strategy:
 *   1. Walk every parser-emitted endpoint file (header comment matches AUTOGENERATED).
 *   2. Build registry: (method, path) → toolName  (also: (method, alias_path) → toolName for canonical/legacy pairs).
 *   3. For each hand-curated file (no AUTOGENERATED header), find endpoints missing `toolName:`,
 *      look up via the registry, and inject `toolName: '<x>',` into the file in-place.
 *   4. Report endpoints that couldn't be resolved.
 *
 * Path alias pairs the parser doesn't model yet:
 *   /companies     <-> /customers      (canonical 2026-05-13)
 *   /opportunities <-> /deals          (canonical 2026-05-13)
 *
 * Run from D:/Dev/TrustPager-Docs:  npx tsx scripts/backfill-tool-names.ts
 */
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join } from 'path';

const ENDPOINTS_DIR = join(process.cwd(), 'src', 'data', 'endpoints');
const PARSER_HEADER = 'AUTOGENERATED by scripts/sync-from-api.ts';

// Canonical ↔ legacy path-prefix aliases. The values are tried in order.
const ALIASES: Record<string, string[]> = {
  '/companies': ['/customers'],
  '/opportunities': ['/deals'],
};

function aliasVariants(path: string): string[] {
  // Apply every canonical↔legacy swap independently AND in combination so
  // /companies/:id/opportunities can match /customers/:_/deals.
  const swaps: Array<[string, string]> = [];
  for (const [canonical, legacy] of Object.entries(ALIASES)) {
    for (const l of legacy) {
      swaps.push([canonical, l]);
      swaps.push([l, canonical]);
    }
  }
  // Build cross-product of "apply or skip each swap". 2^n where n = swap count.
  const out = new Set<string>([path]);
  for (let mask = 1; mask < (1 << swaps.length); mask++) {
    let candidate = path;
    let valid = true;
    for (let i = 0; i < swaps.length; i++) {
      if (!(mask & (1 << i))) continue;
      const [from, to] = swaps[i];
      if (candidate === from || candidate.startsWith(from + '/')) {
        candidate = candidate.replace(from, to);
      } else if (candidate.includes('/' + from.slice(1) + '/') || candidate.endsWith('/' + from.slice(1))) {
        // mid-path segment swap (e.g. .../opportunities at end or .../opportunities/...)
        candidate = candidate.replace(new RegExp(`/${from.slice(1)}(?=/|$)`), '/' + to.slice(1));
      } else {
        valid = false; break;
      }
    }
    if (valid) out.add(candidate);
  }
  return [...out];
}

// Normalize path param NAMES to `:_` so /companies/:id and /customers/:company_id
// match positionally. Preserves the slash structure and literal segments.
function normalizeParamNames(path: string): string {
  return path.replace(/:[A-Za-z_][A-Za-z0-9_]*/g, ':_');
}

function parseEndpoints(content: string): Array<{ block: string; method: string; path: string; hasToolName: boolean }> {
  const out: Array<{ block: string; method: string; path: string; hasToolName: boolean }> = [];

  // Multi-line endpoint blocks: { \n method: 'GET',\n path: '/foo',\n ... \n },
  const multiLineRe = /\{\s*\n([ \t]+method:\s*'([A-Z]+)',\s*\n[ \t]+path:\s*'([^']+)',[\s\S]*?)\n[ \t]+\},/g;
  for (const m of content.matchAll(multiLineRe)) {
    const block = m[0];
    out.push({
      block,
      method: m[2],
      path: m[3],
      hasToolName: /\btoolName:\s*'/.test(block),
    });
  }

  // Compact single-line endpoint blocks. Scan line-by-line and find any line that
  // begins with `{ method: 'X', path: 'Y'` and ends with `},`. This handles params:
  // [{...}] arrays which break naive brace-counting regexes.
  for (const rawLine of content.split('\n')) {
    const line = rawLine.trimEnd();
    const m = line.match(/^\s*(\{\s*method:\s*'([A-Z]+)',\s*path:\s*'([^']+)',.*\}),\s*$/);
    if (!m) continue;
    const block = m[1];
    out.push({
      block,
      method: m[2],
      path: m[3],
      hasToolName: /\btoolName:\s*'/.test(block),
    });
  }
  return out;
}

function buildRegistry(): Map<string, string> {
  const map = new Map<string, string>(); // key = `${method} ${normalizedPath}` → toolName
  for (const fileName of readdirSync(ENDPOINTS_DIR)) {
    if (!fileName.endsWith('.ts') || fileName === 'index.ts' || fileName === 'types.ts') continue;
    const content = readFileSync(join(ENDPOINTS_DIR, fileName), 'utf8');
    if (!content.includes(PARSER_HEADER)) continue;
    for (const ep of parseEndpoints(content)) {
      const m = ep.block.match(/\n\s*toolName:\s*'([^']+)'/);
      if (!m) continue;
      map.set(`${ep.method} ${normalizeParamNames(ep.path)}`, m[1]);
    }
  }
  return map;
}

function main() {
  const registry = buildRegistry();
  console.log(`[backfill] parser registry has ${registry.size} (method, path) → toolName entries`);

  let totalBackfilled = 0;
  const unresolved: Array<{ file: string; method: string; path: string }> = [];

  for (const fileName of readdirSync(ENDPOINTS_DIR)) {
    if (!fileName.endsWith('.ts') || fileName === 'index.ts' || fileName === 'types.ts') continue;
    const filePath = join(ENDPOINTS_DIR, fileName);
    const content = readFileSync(filePath, 'utf8');
    if (content.includes(PARSER_HEADER)) continue;  // skip parser-emitted

    const endpoints = parseEndpoints(content);
    const missing = endpoints.filter((ep) => !ep.hasToolName);
    if (missing.length === 0) continue;

    let updated = content;
    let backfilledHere = 0;
    for (const ep of missing) {
      let toolName: string | undefined;
      for (const variant of aliasVariants(ep.path)) {
        toolName = registry.get(`${ep.method} ${normalizeParamNames(variant)}`);
        if (toolName) break;
      }
      if (!toolName) {
        unresolved.push({ file: fileName, method: ep.method, path: ep.path });
        continue;
      }
      const blockEscaped = ep.block;
      const idx = updated.indexOf(blockEscaped);
      if (idx === -1) continue;
      const isCompact = !blockEscaped.includes('\n');
      // Inject toolName after the path field. Multi-line: own line. Compact: same line.
      const newBlock = isCompact
        ? blockEscaped.replace(
            /(path:\s*'[^']+',)/,
            `$1 toolName: '${toolName}',`,
          )
        : blockEscaped.replace(
            /(path:\s*'[^']+',)/,
            `$1\n      toolName: '${toolName}',`,
          );
      updated = updated.slice(0, idx) + newBlock + updated.slice(idx + blockEscaped.length);
      backfilledHere++;
    }

    if (backfilledHere > 0) {
      writeFileSync(filePath, updated);
      console.log(`[backfill] ${fileName}: backfilled ${backfilledHere} of ${missing.length}`);
      totalBackfilled += backfilledHere;
    }
  }

  console.log(`\n[backfill] total backfilled: ${totalBackfilled}`);
  if (unresolved.length > 0) {
    console.log(`[backfill] unresolved (${unresolved.length}):`);
    for (const u of unresolved) console.log(`  ${u.file}  ${u.method} ${u.path}`);
  }
}

main();
